kubernetes-sigs/cluster-api-provider-vsphere

cloud/vsphere/templates.go

In the near future we may make selection of CNI available to the users
However, we wanted to select a better default CNI at the moment
The choice of weave for CNI is based on some available comparison here:
https://chrislovecnm.com/kubernetes/cni/choosing-a-cni-provider/
Another factor for choosing weave here is that you don't need to run
an additional etcd for the CNI
Resolves #25

Update the CNI to weave

---

cloud/vsphere/provisioner/common/templates.go
cloud/vsphere/provisioner/terraform/terraform.go
cloud/vsphere/utils/utils.go

Now that we are adding a govmomi based implementation as well, the script templates as they stand today should be used by both govmomi and terraform implementations. Thus refactoring the template.go to be consumable with both implementations
Resolves #57

Refactor template.go out of terraform to be used as common code

---

cloud/vsphere/provisioner/common/templates.go

The systemd unit definition of the kubelet sources the file
/etc/default/kubelet for any env variables. The default file
generated for /etc/default/kubelet has an empty value like
`KUBELET_EXTRA_ARGS=`. This causes the kubelet to not use the
actual value of KUBELET_EXTRA_ARGS set in the override file
/etc/systemd/system/kubelet.service.d/20-cloud.conf

Fix the kubelet config for version 1.11 and above

---

Makefile

we want to be able to run unit tests by running a single command `make test`.
i have a immediate following pull request to setup a CI job that trigger `make test` 
/cc @frapposelli @sflxn

run dep ensure when run make test

---

cloud/vsphere/clusteractuator.go
cloud/vsphere/machineactuator.go
cloud/vsphere/provisioner/govmomi/create.go
cloud/vsphere/provisioner/govmomi/exists.go
cloud/vsphere/provisioner/govmomi/provisioner.go
cloud/vsphere/provisioner/govmomi/update.go
cloud/vsphere/provisioner/govmomi/utils.go
cloud/vsphere/utils/utils.go
cloud/vsphere/vsphereproviderconfig/types.go

Clusterctl create cluster was not able to properly create the target cluster.  It would sit
in an infinite loop, attempting to clone the VM template.  The fix was to not use annotations
for task ref and vm ref during create.  Instead, use provider status.  Once this fix was in,
the Target cluster would then sit in an infinite loop, attempting to clone the VM template.
The fix was to check for nodeRef in the actuator's Exists() function.
In addition, moved utils from provisioner/common to provisioner/govmomi as it's only ever
used by the govmomi actuator.
Fixes #70

Fix govmomi actuator's Create when using clusterctl

---

cmd/clusterctl/examples/vsphere/machines.yaml.template
cmd/clusterctl/examples/vsphere/machineset.yaml.template
pkg/apis/vsphereproviderconfig/types.go
pkg/apis/vsphereproviderconfig/v1alpha1/types.go
pkg/cloud/vsphere/clusteractuator.go
pkg/cloud/vsphere/provisioner/govmomi/create.go
pkg/cloud/vsphere/provisioner/govmomi/exists.go
pkg/cloud/vsphere/provisioner/govmomi/update.go
pkg/cloud/vsphere/provisioner/terraform/terraform.go
pkg/cloud/vsphere/utils/utils.go

With the new structure we should be able to:
* Support defining multiple nics
* Support providing dhcp/static IP configuration for each nic
* Support customizing multiple disks if present
* Adds a optional flag called `vsphereCloudInit` to indicate if
the template used has the vsphere datasource for cloud-init
present and enabled (see [vsphere cloud-init datasource](https://github.com/akutz/cloud-init-vmware-guestinfo/))
Note: This change does not change the existing behavior of using
the `MachineVariables` string map. This will be handled in the
subsequent patches.
Partially Resolves #24
Partially Resolves #28

Add a new MachineSpec for defining the instance on vsphere

---

Gopkg.lock
pkg/cloud/vsphere/provisioner/govmomi/create.go
pkg/cloud/vsphere/utils/utils.go

The MachineSpec.VMTemplate currently is treated as name of the VM to be searched. In certain cases the name of the VM can be duplicated inside a VC, thus we need a more precise mechanism to point to a VM to be used as a template. For this purpose we are now allowing the VMTemplate to also be a valid UUID that would then be matched with the VMs InstanceUUID property which is guaranteed to be unique.
The modified logic detects if the passed string looks like a valid UUID then it tried to find the VM by InstaceUUID if not found, then it fall back on treating the string as the VM name.
Resolves #109
Change-Id: Ia5e6ca600a71ca784b54336299818b6ec892b949

Overload the VMTemplate parameter for search purposes

---

Gopkg.lock
pkg/cloud/vsphere/provisioner/govmomi/create.go
pkg/cloud/vsphere/provisioner/govmomi/update.go
pkg/cloud/vsphere/utils/utils.go
vendor/github.com/cenkalti/backoff/LICENSE
vendor/github.com/cenkalti/backoff/backoff.go
vendor/github.com/cenkalti/backoff/context.go
vendor/github.com/cenkalti/backoff/exponential.go
vendor/github.com/cenkalti/backoff/retry.go
vendor/github.com/cenkalti/backoff/ticker.go
vendor/github.com/cenkalti/backoff/tries.go

* Updates the wait condition for the worker node to APIStatus
* Fix the kubeadm token caching issue by adding a jitter in the
re-queue interval
* Fix few minor typos
Resolves #94
Resolves #95
Change-Id: Ic3aaee93f807ebf4fd8ca3964d46510be627c2b2

Misc fixes

---

pkg/cloud/vsphere/provisioner/common/templates.go

In the `Machine` one can specify the labels, taints. In this patch we use the kubelet args to bootstrap the node with the provided taints and labels
Resolves #111
Change-Id: Id184e1148c8f6149c9faa40cb382bf740210bba5

Add labels to the nodes created via Machines

---

pkg/cloud/vsphere/provisioner/common/templates.go

Currently we are missing the namespace prefix from the "machine" annotation on the node. Without this fix the NodeRef will only populate for the `Machines` in the `default` namespace
Resolves #114
Change-Id: Ibc7e378cb95c03a0564c9e0ad9022174e9367204

Add the namespace to the "machine" annotation on the Node

---

pkg/cloud/vsphere/provisioner/common/templates.go

Currently the configure part of the init script is also installing
packages, which should not be the case. The install part of the script
should be installing anything needed during the configure part.
This split is further used when we want to use template that is
pre-loaded with all the binaries. In that case, we only want to run
the configure part which would bring up the services
This change also updates the kubeadm config to move to v1alpha2
so that now k8s 1.12.x can be supported as well
Resolves #121 
Resolves #97 
Change-Id: I720eaf54829dd3f756dbfedb7691c004c54fcd01

Make the install and configure part of the scripts match the intent

---

cmd/clusterctl/examples/vsphere/machines.yaml.template
docs/quickstart.md

The quickstart guide needs to be updated with information on how to
use the repo after the CRD migration.

Update quickstart guide for post-crd

---

Makefile
cmd/clusterctl/Dockerfile
scripts/e2e/bootstrap_job.template
scripts/e2e/bootstrap_job/clusterctl.sh
scripts/e2e/e2e.sh

With this patch, clusterctl will be compiled, packaged into container and uploaded to gcr during the build phase.  During the test phase, the container will be used to execute with the latest version of the code.
/cc @sflxn @sidharthsurana @dougm @frapposelli 
resolve #6

compile clusterctl for every e2e ci job

---

docs/ova/README.md
installer/build/bootable/build-main.sh
installer/build/bootable/config/builder.ovf
installer/build/build-ova.sh
installer/build/build.sh

To facilitate CI testing, we're adding two parameters to the `installer/build/build.sh` script:
- `CI_ROOT_PASSWORD`: sets a root password as default value in the OVA
- `CI_ROOT_SSH_KEY`: sets a root ssh public key as default value in the OVA
These parameters are to be used during CI only, and not intended to be used while generating a release artifact.
/cc @figo

Add CI parameters to OVA build

---

installer/build/build.sh

Remove the mount from the build script as it's not needed for the build to succeed.

Remove docker.sock mount from OVA build script

---

config/default/kustomization.yaml
config/default/vsphere_manager_image_patch.yaml
config/manager/manager.yaml
config/rbac/rbac_role.yaml
config/rbac/rbac_role_binding.yaml

Also change the prefix to generate the provider specific names
This is important as the current scheme of naming would clash
with the objects created for the core cluster-api deployment
This change will also make it possible to deploy both the core
cluster-api controllers and the vsphere provider controllers in
the same namespace if needed. By default these are deployed in
different namespaces.
Resolves #168
Change-Id: Ie6d82393129549bacd505060b43b5cfa7c8de1ef

Remove redundancies in the kustomize files

---

Gopkg.lock
pkg/cloud/vsphere/provisioner/common/templates.go
pkg/cloud/vsphere/provisioner/govmomi/create.go
pkg/cloud/vsphere/provisioner/govmomi/create_test.go
vendor/k8s.io/apimachinery/pkg/util/version/doc.go
vendor/k8s.io/apimachinery/pkg/util/version/version.go

separates kubeadm.conf in template by major version
- translates ControlPlane or Kubelet version into major version
- strips scheme and path from vsphere host in cases of misconfiguration
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/188

kubeadm.conf support for multiple k8s versions

---

pkg/cloud/vsphere/provisioner/govmomi/create.go
pkg/cloud/vsphere/provisioner/govmomi/delete.go
pkg/cloud/vsphere/provisioner/govmomi/exists.go
pkg/cloud/vsphere/provisioner/govmomi/update.go
pkg/cloud/vsphere/utils/utils.go

There is a chance in original code:  VM clone success, but "vmref" not been added to machine status, at the same time, "taskref" been removed.
this leads to unrecoverable state: Exists() return false since
"vmref" not there, "taskref" is gone, every reconcile loop will try to 
clone VM, eventually, vCenter will throw error. 
we need to pay extra attention to verifyAndUpdateTask() to make sure:
if VM clone success, only remove "taskref"
when "vmref" been added to machine status
Resolves: #139

Fix recurring VM re-clone issue

---

scripts/e2e/e2e.sh
scripts/e2e/wait_for_job.sh

need this hot fix to support the periodic job for OVA e2e, the job is already running at Prow,
it is failing due to e2e.sh does not handle this.
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cluster-api-provider-vsphere-ova-e2e/2/build-log.txt
not able to find out when test it locally, because local testing is still a simulation of Prow.
cc @sflxn  @frapposelli

add support for periodic job

---

.gitignore
Makefile
pkg/cloud/vsphere/constants/constants.go
pkg/cloud/vsphere/provisioner/govmomi/create.go
pkg/cloud/vsphere/provisioner/govmomi/delete.go
pkg/cloud/vsphere/provisioner/govmomi/exists.go
pkg/cloud/vsphere/provisioner/govmomi/update.go
pkg/cloud/vsphere/provisioner/govmomi/utils.go
scripts/e2e/e2e.sh

now cluster-api main has made it possible to let cluster object be NULL,
providers can choose to support or not support, but for CAPV, it panic because it assuming
cluster is not NULL, this change is to handle the situation.
a few bonus changes:
1) fix e2e.sh with right ${PROW_JOB_ID} name
2) fix sed usage at Makefile, so it works across Mac/Linux
cc @sflxn @frapposelli @vincepri

handle nil cluster at machine actuator

---

.gitignore
cmd/clusterctl/examples/vsphere/generate-yaml.sh
config/crds/kustomization.yaml
config/default/kustomization.yaml
config/manager/kustomization.yaml
config/rbac/kustomization.yaml
docs/self-service/README.md

With kustomize PR 700 merged, in order to avoid attacking, all
resources are needed to saved in its sub-folder.
Fixes: #205

Putting resources used by kustomization.yaml into its sub-folder

---

cmd/clusterctl/examples/vsphere/machineset.yaml.template

I think we should use the same kubelet version in master and workers nodes.
Modify machineset.yaml:
- modify kubelet verison the same 1.11.3
- add trustedCerts field

Unify machine spec of machine.yaml and machinset.yaml

---

pkg/cloud/vsphere/utils/utils.go

If a user submits an invalid cluster or machine providerspec, this provider's
controller will panic.  This is a simple fix to prevent the crash.  However,
the user experience is still problematic.  The user will get no indication
of success/fail until the user look at the controller logs.
Resolves #192

Prevent nil providerSpec from panicking

---

pkg/cloud/vsphere/provisioner/common/templates.go

For the node controller to update a machine's noderef, the node must have
an annotation cluster.k8s.io/machine=${MACHINE}.  CAPV's template currently
is adding that annotation with name 'machine' instead of 'cluster.k8s.io/machine'.
This change should allow the node controller to add a noderef to machine
objects.
Resolves #223

Resolved an annotation name changed

---

pkg/cloud/vsphere/provisioner/common/templates.go

Ubuntu updated the docker version on their server that causes kubeadm init to fail.
It is preventing clusterctl from creating target clusters.  Currently, we pull the
latest version of docker off of Ubuntu's servers, which at this time is 18.09.2.
This change will pin the docker version to 18.06.x.
Resolves #230

Pin docker to version 18.06 to ensure kubeadm's compatibility

---

Makefile
cmd/clusterctl/examples/vsphere/generate-yaml.sh

With the kustomize code changes, some resources, for example, 'commands'
is not supported, and new resources are introduced into the latest
code, so we add the kustomize version check.
Fixes: #214

Enable the latest Kustomize version check

---

docs/self-service/README.md
docs/self-service/cloud_init_with_guestinfo_datasource.md

For users to create machines that uses static IP, they must use a custom cloud init
image with the Guestinfo Datasource installed.  This commit documents the process
of manually creating that image and converting it into a VM template.
Resolves #185

Update docs with information on creating a custom cloud init

---

pkg/cloud/vsphere/provisioner/common/templates.go

With the latest k8s 1.14, there was a fix to resolve a CVE.  This required
kubernetes-cni 0.7.5 for k8s 1.14 and up.  This fix will first attempt to
install kubernetes-cni 0.7.5.  If the subsequent install of kubelet and
kubeadm fails, it will fallback kubernetes-cni to 0.6.0 and retry installing
the kubelet and kubeadm.
Resolves #238

Fix bootstrap script to fix kubernetes-cni issue in k8s 1.14

---

pkg/cloud/vsphere/provisioner/common/templates.go

Verified the command on the following distros:
ubuntu - trusty,xenial,artful,bionic
photon - 2.0,3.0
Resolves #239
Change-Id: I99a915874a894baea067983e62950fc4745073b8

Use a better shell command to grab the IP address

---

Makefile
README.md

Added 3 tables showing a version compatibility matrix against CAPI (main cluster
API), Kubernetes, and OSes.  Currently, these were gathered manually.
Resolves #222

Add version compatibility matrix against CAPI and k8s

---

cmd/clusterctl/examples/vsphere/cluster.yaml.template
docs/design/vsphereCredentials.md
pkg/apis/vsphereproviderconfig/v1alpha1/vsphereclusterproviderconfig_types.go
pkg/cloud/vsphere/constants/constants.go
pkg/cloud/vsphere/provisioner/govmomi/session.go
pkg/cloud/vsphere/provisioner/govmomi/utils.go

- Adds new field vsphereCredentialSecret that can be specified to
point to the secret that holds the credentials
Resolves #9
Change-Id: I8e43864302a51386f7f11725b0a966cc9e436c59

Add support for specifying vsphere credentials via secrets

---

pkg/cloud/vsphere/provisioner/govmomi/create.go

This PR implements the following:
- If the ResourcePool does not exist in vsphere, create it just prior to cloning the master/worker nodes.
- If a ResoucePool is not specified, deploy the target cluster directly onto the cluster/host default resource pool.
Testing performed on vSphere 6.7u2:
- using an existing Resource Pool
- creating a new Resource Pool
- deploying directly to a cluster
Assumptions:
- the template was created/converted on a host within the compute cluster (ie template is owned by or it's parent is a host within the compute cluster).
Other notes:
- This was only tested on cluster, but this should also work with the effort to support standalone ESX hosts.
Addresses issue: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/247

Implements ResourcePool creation and Deploy Direct to Cluster/Host

---

pkg/cloud/vsphere/provisioner/govmomi/create.go

This PR contains a bugfix.
cluster-api-provider-vsphere recently got the ability to read VSphere credentials from secret. Previously they were stored in plaintext in the ClusterProviderSpec.
However, when populating the CloudProviderConfig we would still only look for the credentials in the ClusterProviderSpec, disregarding the credential secret. If a username and password are not specified in the ClusterProviderSpec, we would inject empty username and password fields into the cloud-config on the cluster VMs.
This PR fixes that, getting the credentials to inject to CloudProviderConfig using the same mechanism as when creating govmomi sessions, i.e. preferring credentials from secret but falling back on the ClusterProviderConfig if no credential secret is defined.

populate CloudProviderConfig with credentials from secret

---

Dockerfile
cmd/clusterctl/Dockerfile
config/rbac/rbac_role.yaml
docs/self-service/README.md
docs/self-service/esx_provisioning.md
pkg/cloud/vsphere/provisioner/common/esx/scripts.go
pkg/cloud/vsphere/provisioner/common/templates.go
pkg/cloud/vsphere/provisioner/common/vc/scripts.go
pkg/cloud/vsphere/provisioner/govmomi/create.go
pkg/cloud/vsphere/provisioner/govmomi/create_test.go
pkg/cloud/vsphere/provisioner/govmomi/session.go
vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
vendor/github.com/spf13/cobra/cobra/cmd/licenses.go

Add standalone ESXi support.
- add machine provisioning on ESXi.
- fixed boot sequence on some images (e.g. xenial)
- fixed sudo on machines without DNS access
- fixed cloud provider bootstrap
- fixed rbac role preventing machine deletion
- refactored templates.go and the esx cloning code
Fixed boot sequence on some images by adding a serial port to allow random
number initialization.  This affect some images like Xenial.  It currently
adds a serial port to all machines if it doesn't already in the vm spec.
Fixed sudo access for machines without DNS access, which for most development
scenarios in nested ESXi on dev laptops.  Fixed cloud provider bootstrapping
on infrastructure that do not have cloud provider support (e.g. ESXi)
issue #177

Standalone esx

---

pkg/cloud/vsphere/clusteractuator.go
pkg/cloud/vsphere/provisioner/govmomi/utils.go
pkg/cloud/vsphere/utils/utils.go

CAPV at the moment fetches control plane machines arbitrarily which means `apiEndpoints` on a cluster resource can have the address of a VM from another cluster. This PR fetches control plane nodes by checking the cluster name label first to ensure only machines associated with a cluster is assigned as part of the apiEndpoints status of the cluster resource. 
Also renames master -> control plane where possible

Get control plane machines by cluster name

---

OWNERS_ALIASES

This patch is to add Andrew Kutz and Andrew Sy Kim to the OWNERS file via the alias "cluster-api-vsphere-maintainers".
cc @andrewsykim @frapposelli

Add akutz and andrewsykim to OWNERS

---

cmd/clusterctl/examples/vsphere/addons.yaml.template

This PR updates the `clusterctl` examples to use calico as the default CNI plugin. For users following the `clusterctl` examples, this means that only the _initial_ target cluster (a.k.a management cluster) created by the `kind` bootstrap cluster will use calico. All other target clusters created by the initial management cluster will not have a default CNI installed and must be added by the cluster admin.

Use calico CNI for the example initial target cluster

---

build/images/Makefile
build/images/packer/packer.json

This patch updates the image building process to allow for runtime customization of the image's boot timeout, its VNC properties, and the Packer flags via `PACKER_FLAGS` and the Makefile.
This patch also updates the default timeout to `10s` as `5s` is not long enough on VMware Workstation running headless on a Linux server.

Enable custom boot timeout, VNC, & packer flags

---

.gitignore
Makefile
hack/ensure-tools.sh

This patch installs kustomize v2.0.0 if the tool is missing and provides a centralized means to install build tooling in `hack/ensure-tools.sh`.

Install kustomize v2 if missing

---

hack/image-post-create-config.sh

This patch fixes an issue with `hack/image-post-create-config.sh`
where it failed on macOS due to it not supporting the `-w` flag for the
`base64` program.

Fix base64 bug in hack/image-post-create-config.sh

---

Makefile
cmd/clusterctl/examples/vsphere/capv_manager_image_patch.yaml.template
cmd/clusterctl/examples/vsphere/generate-yaml.sh
cmd/clusterctl/examples/vsphere/machines.yaml.template
cmd/clusterctl/examples/vsphere/machineset.yaml.template
config/default/.gitignore
config/default/kustomization.yaml

Adding the following env vars for generating yaml files for the clusterctl bootstrap cluster:
```
VSPHERE_DATACENTER
VSPHERE_DATASTORE
VSPHERE_NETWORK
VSPHERE_RESOURCE_POOL
VSPHERE_FOLDER
VSPHERE_TEMPLATE
VSPHERE_DISK
```

clusterctl: templatize more env vars for clusterctl yaml generation

---

config/default/kustomization.yaml
config/manager/manager.yaml

The generated machine ssh keys are no longer needed after https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/307

clusterctl: remove generated machine ssh keys

---

config/manager/manager.yaml

_If_ a management cluster is running on worker nodes and the vSphere provider manager runs on a worker node, it may delete the machine it is running on. In most cases, Kubernetes will reschedule this node but this should be preventable entirely by running the vSphere provider manager on only control plane nodes.

clusterctl: vsphere provider manager should only run on control plane nodes

---

installer/build/bootable/root/etc/profile.d/kubernetes.sh
installer/build/bootable/root/opt/ova/bin/kubeadm-provisioning.sh
installer/build/bootable/root/opt/ova/bin/kubernetes-watchdog.sh
installer/build/scripts/get_logs.sh
installer/build/scripts/provisioners/provision_kubernetes.sh
installer/ovatools/ova-ui/templates.go
pkg/cloud/vsphere/constants/constants.go
scripts/e2e/bootstrap_job/clusterctl.sh

Some code and script files lacked license headers.  This commit adds headers only to files which lacked any header at all.  It does not modify existing license headers.
Fixes #292

Add License Headers To Code And Script Files

---

scripts/e2e/e2e.sh

This patch removes support for the "OVA" arg to scripts/e2e.sh, which
previously triggered the building of a new installer image and OVF, then
pushed that OVF to use as a bootstrap VM. All unused functions within
the script are also removed.
This came up as part of #334. We will also need to update the Prow jobs to remove the "ova" flag passed to `scripts/e2e/e2e.sh`.
```release-note
NONE
```

Remove building of installer OVA from e2e.sh

---

Makefile

Run generate-yaml.sh in docker as the current user, otherwise generated yaml files belong to root which end up being unread-able to other users.
Fixes #
```release-note
NONE
```

clusterctl: generate yaml in docker as current user

---

docs/getting_started.md
docs/machine_images.md

docs: add getting started guide for bootstrapping a managemenet cluster with clusterctl

---

cmd/clusterctl/examples/vsphere/machines.yaml.template
cmd/clusterctl/examples/vsphere/machineset.yaml.template
scripts/e2e/bootstrap_job/spec/machines.template
scripts/e2e/bootstrap_job/spec/machineset.template

Disable dhcp6 by default. 
Fixes #
```release-note
```

clusterctl: disable dhcp6 by default

---

cmd/clusterctl/examples/vsphere/cluster.yaml.template
docs/getting_started.md
hack/generate-yaml.sh

Allows ssh authorized keys to be set in hack/generate-yaml.sh by setting the `SSH_AUTHORIZED_KEY` env var.
Fixes #
```release-note
```

hack/generate-yaml: templatize sshAuthorizedKeys

---

pkg/cloud/vsphere/services/govmomi/create.go
pkg/cloud/vsphere/services/kubeadm/configs.go
pkg/cloud/vsphere/services/userdata/controlplane.go
pkg/cloud/vsphere/services/userdata/controlplane_test.go

In https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/307 we temporarily removed the vSphere cloud provider, this PR adds it back using the updated custom kubeadm config mechanism. 
Fixes #
```release-note
Re-enable the vSphere cloud provider. 
```
/assign @akutz

re-enable in-tree vsphere cloud provider

---

cmd/clusterctl/examples/vsphere/machineset.yaml.template

Adds labels to example machineset, otherwise cluster api controller logs warnings like the following:
```
W0625 17:20:53.061470       1 machinedeployment_controller.go:353] No machine deployments found for MachineSet "workload-example-machineset-1" because it has no labels
W0625 17:22:45.634381       1 machinedeployment_controller.go:353] No machine deployments found for MachineSet "workload-example-machineset-1" because it has no labels
W0625 17:22:45.634421       1 machinedeployment_controller.go:353] No machine deployments found for MachineSet "workload-example-machineset-1" because it has no labels
```
The cluster API controller In [getMachineDeploymentsForMachineSet](https://github.com/kubernetes-s …

add machineset metadata labels

---

pkg/cloud/vsphere/services/govmomi/create.go
pkg/cloud/vsphere/services/userdata/controlplane.go
pkg/cloud/vsphere/services/userdata/controlplane_test.go

Based on the discussion here https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/343#discussion_r297422396, correctly using VM folder instead of resource pool in the vSphere cloud config. 
Fixes #
```release-note
```
cc @mylesagray

userdata: use VM Folder in cloud config

---

config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderconfig.yaml
config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderstatus.yaml
pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types.go
pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderstatus_types.go
pkg/cloud/vsphere/services/govmomi/net/net.go
pkg/cloud/vsphere/services/govmomi/net/net_test.go
pkg/cloud/vsphere/services/govmomi/update.go
pkg/cloud/vsphere/services/govmomi/util.go
pkg/cloud/vsphere/services/govmomi/vcenter/clone.go
scripts/e2e/bootstrap_job/spec/provider-components.template

This PR removes the UUID used to track the network device specs to network device mappings. Now the order of the devices added is assumed  to be the order of the devices retrieved later. This was confirmed via the test cases in the following gists:
* https://gist.github.com/dougm/6061dcf7bf44cc21fae185143923f1fa
* https://gist.github.com/dougm/6061dcf7bf44cc21fae185143923f1fa/revisions
This PR also removes any IP addresses from the list returned from a VM if the addresses are loopback, link local unicast, link local multicast, invalid, or unspecified.
**Which issue(s) this PR fixes**: NA
```release-note
NONE
```
cc @dougm 
/assign @andrewsykim

Net devices by order, remove invalid IP addrs

---

docs/getting_started.md

Documented additional command which allows readers to directly retrieve a workload cluster kubeconfig.  Previously this step was undocumented and left up to the reader to determine how to do it.

Provide Additional Detail For Retrieving Workload Cluster Kubeconfig

---

pkg/cloud/vsphere/actuators/machine/actuator.go
pkg/cloud/vsphere/constants/constants.go

This patch introduces a new annotation "capv.sigs.k8s.io/maintenance"
that currenly anyone can put on the Machine object to instruct the
actuator to skip any kind of reconciliation on the machine object.
This can be used for various situations like(only sample use cases):
- admin wants to perform maintenance on the underlying infra for which
they might need to power down VMs
- create bulk machine objects without the actuator creating them all at once,
but only have them realized as needed by removing this annotation
Change-Id: I5a22c7abbe819f34a05c482c19d8625a661eaeaf
Fixes #369
**Special notes …

Add support for Machine maintenance window

---

pkg/cloud/vsphere/services/govmomi/create.go
pkg/cloud/vsphere/services/govmomi/delete.go
pkg/cloud/vsphere/services/govmomi/exists.go
pkg/cloud/vsphere/services/govmomi/update.go
pkg/cloud/vsphere/services/govmomi/util.go

This patch fixes how the existence checks for VMs are handled since the MachineController doesn't reenqueue Exists calls that return a requeue error. Therefore all requeue logic had to be shifted into the CUD operations.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: NA
I haven't tested this locally at all yet. My morning has been nuts. I just wanted to push a WiP PR so that reviews could start. I plan to test and handle bugs after lunch.
```release-note
NONE
```
/assign …

Fix exists logic since Exist doesn't requeue

---

pkg/cloud/vsphere/services/metadata/constants.go

This patch fixes the issue where the cloud-init ethernets IDs were using invalid characters according to netplan. IDs are now simply "id$i" where "$i" is the index of the network device spec.
This issue was reported by @jpweber. 
```release-note
NONE
```

Fix the cloud-init ethernets IDs

---

config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderconfig.yaml
pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types.go
pkg/cloud/vsphere/context/machine_context.go
scripts/e2e/bootstrap_job/spec/provider-components.template

Allow preferred CIDRs to be set on a machine network spec which ensures addresses returned in kubeconfig for a given machine is in a known VM network. This is particularly useful for machines that set multiple network devices but only 1 device should be used for the API server address.
Fixes #
```release-note
```

add preferred apiserver CIDRs to network devices

---

pkg/cloud/vsphere/context/machine_context_test.go

Adds unit tests for fetching IP addresses from machine context. Follow-up to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/365 
Fixes #
```release-note
```
/assign @akutz

unit test IP addressese from machine context

---

docs/getting_started.md

In https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/344 we set `dhcp6: false` in all generated yaml used for clusterctl, the docs need to be updated to reflect that change. 
Fixes #
```release-note
```
/assign @akutz

docs/getting_started.md: disable dhcp6 in examples

---

pkg/cloud/vsphere/actuators/cluster/actuator.go

If for whatever reason the kubeconfig secret for a cluster being delete doesn't exist, then the delete call will hang forever. We should account for the case where the kubeconfig secret doesn't exist either because of a previous error or the initial delete was successful but delete was re-queued. 
```release-note
```

cluster actuator: don't block delete if kubeconfig secret doesn't exist

---

hack/generate-yaml.sh

The `CLUSTER_NAME` variable in `hack/generate-yaml.sh` is hard-coded at the moment, this changes `CLUSTER_NAME` to `DEFAULT_CLUSTER_NAME` so that `CLUSTER_NAME` from the calling environment can overwrite it properly. 
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/377
```release-note
```

hack/generate-yaml.sh: fix hard-coded cluster name

---

scripts/e2e/bootstrap_job/Makefile
scripts/e2e/e2e.sh

When running `make` with no arguments in scripts/e2e/bootstrap_job, the
default behavior was to build the image, push the image to gcr.io, and
delete the local copy of the image. That's not a useful default.
Instead, change the "all" target to just have "build" as a pre-req,
making "make" the equivalent of "make build". If someone wants to push
images, they can run "make push" instead. Deleting the local image is an
explicit step left to "make clean".
Fixes #
_Please confirm that if this PR changes any image versions, then that's the sole change this PR …

Modify -ci image makefile to default to build only

---

Makefile

`make clusterctl-in-docker` is broken:
```
$ GOOS=linux make clusterctl-in-docker
docker run --rm -v /home/ubuntu/go/src/sigs.k8s.io/cluster-api-provider-vsphere:/go/src/sigs.k8s.io/cluster-api-provider-vsphere \
-w /go/src/sigs.k8s.io/cluster-api-provider-vsphere \
-e CGO_ENABLED=0 -e GOOS="${GOOS:-linux}" -e GOARCH="${GOARCH:-amd64}" \
golang:1.12 \
go build -ldflags '-extldflags "-static" -w -s' \
-o bin/clusterctl."${GOOS:-linux}"_"${GOARCH:-amd64}" ./cmd/clusterctl
cp: cannot remove 'bin/clusterctl': Permission denied
Makefile:51: recipe for target 'clusterctl-in-docker' failed
make: *** [clusterctl-in-docker] Error 1
```
Can be fixed by cping the output binary inside the build container. 
**Which …

fix permissoin issue in make clusterctl-in-docker

---

pkg/cloud/vsphere/actuators/actuators.go
pkg/cloud/vsphere/services/govmomi/util.go

k8s.io/klogr does not log raw error values (it calls `json.Marshal` on the value) so we have to explicitly call `err.Error()` to pass the string value. 
Before:
```
I0628 14:43:20.470520       1 actuators.go:59] [cluster-actuator]/cluster.k8s.io/v1alpha1/default/workload-log-err/workload-log-err-controlplane-1 "level"=6 "msg"="requeue after error"  "error"={} "object"="default/workload-log-err"
```
After:
```
I0628 14:46:56.782602       1 actuators.go:59] [cluster-actuator]/cluster.k8s.io/v1alpha1/default/workload-log-err/workload-log-err-controlplane-1 "level"=6 "msg"="requeue after error"  "error"="unable to get control plane status for cluster \"default/workload-log-err\": unable to get kubeconfig …
```

properly log requeue error messages with klogr

---

scripts/ci-test.sh

Add KUBEBUILDER_CONTROLPLANE_START_TIMEOUT=30s to the ci-test.sh script,
which is invoked by CI. Hoping to address test flakiness.
attempts to fix #390 
```release-note
```

Bump etcd start timeout to 30s

---

pkg/cloud/vsphere/actuators/actuators.go
pkg/cloud/vsphere/context/cluster_context.go
pkg/cloud/vsphere/context/machine_context.go

This patch fixes a bug in the patch logic for clusters and machines. If the provider spec and status are not reencoded back into their original locations, no patch is generated for either. Please note this does not affect the cluster/machine spec/status -- only the provider analogues.
Fixes #
```release-note
```

Update object patch logic

---

Dockerfile
config/manager/manager.yaml
scripts/e2e/bootstrap_job/spec/provider-components.template

This patch updates the CAPV manager image to a static, distroless image. This saves space as well as enhances security by removing possible attack vectors.
Fixes #258
```release-note
* CAPV manager now based on Google's static, distroless image
```

Distroless manager image

---

docs/getting_started.md

Update docs to install the official clusterctl binary instead of building clusterctl. Avoids building `clusterctl` against master which may not always be compatible with the release version of the provider manager.
Fixes #
```release-note
```

docs/getting_started.md: install clusterctl release binary vs building it

---

cmd/manager/main.go
pkg/cloud/vsphere/actuators/cluster/actuator.go
pkg/cloud/vsphere/actuators/machine/actuator.go
pkg/cloud/vsphere/context/machine_context.go
pkg/cloud/vsphere/services/govmomi/update.go
vendor/modules.txt

This patch updates the ready-state logic for the Cluster and Machine objects. A machine is not marked as ready until it is possible to connect to the target cluster and verify the machine is represented
there as a node.
Additionally, this patch relocates the code to create the KubeConfig secret from the Cluster's Reconcile function to the Machine's Update function. This is because the KubeConfig secret must be created before a Cluster can verify its ready state. If the Cluster didn't create the KubeConfig until after it was ready, then a circular dependency would be created, and a Cluster would never appear as ready.
Finally, several existing calls have been changed to rely on the CAPI NodeRef/Remote packages in order to get a client for a target …

Ready-state logic changes

---

pkg/cloud/vsphere/services/govmomi/create.go
pkg/cloud/vsphere/services/kubeadm/configs_test.go
pkg/cloud/vsphere/services/kubeadm/noderegistration.go
pkg/cloud/vsphere/services/kubeadm/noderegistration_test.go

Kubeadm init and join Node Registration options currently overwrites values passed in through the provider config.  This fix replaces the NewNodeRegistration function so that it does not start with empty Node Registration Options

Fix Kubeadm Init and Join NodeRegistration Options

---

cmd/manager/main.go
pkg/cloud/vsphere/actuators/cluster/actuator.go
pkg/deployer/deployer.go

This package removes the functions GetIP and GetKubeConfig from the Cluster actuator and has it defer to pkg/deployer for the analogous logic. This removes any confusion about the two functions as they existed in the Cluster actuator. They were not to get any special values from secrets, etc. They were just to perform the exact same behavior as from the deployer package.
Fixes #
```release-note
```

Use pkg/deployer in the Cluster actuator

---

pkg/cloud/vsphere/actuators/cluster/actuator.go
pkg/cloud/vsphere/actuators/machine/actuator.go
pkg/cloud/vsphere/constants/constants.go
pkg/cloud/vsphere/context/cluster_context.go
pkg/cloud/vsphere/services/govmomi/create.go
pkg/cloud/vsphere/services/kubeclient/kubeclient.go
pkg/cloud/vsphere/services/userdata/controlplane.go
pkg/cloud/vsphere/services/userdata/controlplane_test.go

This patch changes the way the cloud provider obtains its credential information. Instead of directly via the cloud config file, a Kubernetes Secret object is created on the target cluster used by the cloud
provider. This is a much more secure design as credentials are no longer transported via the GuestInfo RPC mechanism as base64-encoded, plain-text data, over an unencrypted transport.
Fixes #194
```release-note
* The cloud provider …
```

Cloud provider credentials as secret

---

cmd/manager/main.go
pkg/cloud/vsphere/actuators/cluster/actuator.go
pkg/cloud/vsphere/actuators/machine/actuator.go
pkg/cloud/vsphere/config/config.go
pkg/cloud/vsphere/constants/constants.go
pkg/cloud/vsphere/services/govmomi/delete.go
pkg/cloud/vsphere/services/govmomi/update.go
pkg/cloud/vsphere/services/govmomi/util.go

This patch introduces support for a custom, default requeue period via the env var `REQUEUE_PERIOD` and/or flag `--requeue-period`. Both take a value parseable by time.ParseDuration. The default value is `20s`.
Fixes #417
Hi @moshloop,
After thinking on this some more, a global value **does** make sense. I conflated the idea of global with something else, and we'll chalk it up to a brain-fart. Thanks for staying on top of this! …

Support a custom, default requeue period

---

OWNERS
OWNERS_ALIASES

This change is due to kubernetes/community#3895 that folds all the cloud provider SIGs into sig-cloud-provider

Remove sig-vmware from OWNERS

---

hack/match-release-tag.sh

This patch adds a new script for matching a release tag.
Related to #426
```release-note
NONE
```

Match release tag script

---

scripts/e2e/e2e.sh

Fixes error seen here: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cluster-api-provider-vsphere-ova-e2e/1151904458888712193
This started happening once we set `-o nounset`, but I missed that it was happening because it's only happening for the periodic, not the pre-submit.
Fixes #
```release-note
```

Fix e2e unbound var PULL_PULL_SHA

---

config/rbac/rbac_role.yaml
pkg/cloud/vsphere/actuators/cluster/actuator.go
scripts/e2e/bootstrap_job/spec/provider-components.template

Cluster delete is failing because secret delete permission is missing. Drive by: Setters for extra config are returning errors which are not being handled, fix by removing error return as it never returns error.
Fixes #432
I'm replacing #432 with this as the author or that PR has not responded to feedback. Please note that the original authorship has been retained. The only intent here is to ensure the fix is merged in a timely manner. …

Cluster actuator needs delete permission for secret.

---

Makefile
scripts/e2e/bootstrap_job/Makefile
scripts/e2e/e2e.sh
scripts/e2e/hack/Makefile

This patch removes unused Makefile targets as a step towards using the
new hack/release.sh script. To that end, we also standardize the version
string retrieved via `git describe` across the project.
Fixes #
I believe this should still allow the e2e tests to work. I'm doing this is in small pieces so I don't break anything along the way. I tried doing more at first, but there are a lot of moving parts. This should be a simple one we can first.
**Release …

Removed unused Makefile targets

---

docs/getting_started.md
hack/tools/generate-yaml/Dockerfile

This patch fixes an issue with generating manifests using the manifests image due to Docker permissions.
Fixes #453
```release-note
NONE
```

Fix issue generating manifests due to Docker perms

---

docs/getting_started.md

Document a workaround for docker volume mounts not being accessible to the current host user. 
```
$ docker run --rm   --user "$(id -u):$(id -g)"   -v "$(pwd)/management-cluster":/out   -v "$(pwd)/envvars.txt":/out/envvars.txt:ro   gcr.io/cluster-api-provider-vsphere/release/manifests:v0.4.0-beta.1   -c management-cluster
./hack/generate-yaml.sh: line 179: /out/addons.yaml: Permission denied
```
Fixes # …

docs/getting_started.md: document workaround for linux mount permission issues

---

hack/release.sh

Since hack/release.sh uses both docker push and gsutil, we need to login
to docker explicitly as well as gcloud. We also configure gcloud docker
auth helper.
Fixes #
I feel like i"m close with the E2E test PR, but might as well get this working sooner rather than later. :)
```release-note
```
/assign @akutz

Fix login issues in hack/release.sh

---

Makefile
hack/release.sh
scripts/e2e/README.md
scripts/e2e/bootstrap_job.template
scripts/e2e/bootstrap_job/Makefile
scripts/e2e/bootstrap_job/clusterctl.sh
scripts/e2e/e2e.sh
scripts/e2e/hack/Makefile
scripts/e2e/hack/job.yml

This patch updates e2e.sh and related pieces to use images located at
gcr.io/cluster-api-provider-vsphere/pr instead of the previous location.
It also eliminates the need for a temporary 'clusterctl' container image
as part of the e2e process, because that binary is now being pushed as
part of the automated builds. Therefore we just download the binary
instead of building and pushing a new image just to copy the binary out
of it.
Fixes #
@akutz You'll see in the `e2e.sh` script the use of `-k` with `release.sh`. This is why I needed that change in Prow. The …

Change e2e script/job to use new image locations

---

docs/getting_started.md
hack/generate-yaml.sh
hack/tools/generate-yaml/Dockerfile

This patch fixes incompatibilities with generating manifests using Docker on macOS vs Linux. Changes include:
* Removes the need to pass in the host's user and group IDs
* Mounts `envvars.txt` to `/envvars.txt` in the container
* Paths printed during generation from inside the container are still valid externally on the host
* The current directory should always be mounted to `/out`
Here are two examples on macOS and Linux:
**macOS**
```shell
$ uname -s
Darwin
$ ls out/management-cluster
ls: out/management-cluster: No such file or directory
$ docker run --rm \
>   -v "$(pwd)":/out \
>   -v "$(pwd)/envvars.txt":/envvars.txt:ro \
>   akutz/capv-manifests:latest \
>   -c management-cluster
done generating ./out/management-cluster/addons.yaml
done …
```

Fixes YAML generation issues with Docker

---

pkg/cloud/vsphere/actuators/cluster/actuator.go

This PR contains a bugfix.
When creating the cloud provider credentials secret for target clusters, the username and password were being base64 encoded.
Since `StringData` is being used, this is not necessary. Instead, the already base64 encoded data was base64 encoded again.
This PR fixes this bug by passing the username and password directly to `StringData`.

Bugfix: Double base64 encoding of cloud provider credentials

---

pkg/cloud/vsphere/context/cluster_context.go
pkg/cloud/vsphere/context/machine_context.go
pkg/cloud/vsphere/context/machine_context_test.go
pkg/cloud/vsphere/services/govmomi/update.go

In the case where there are multiple network devices and one of them returns a valid control plane endpoint, the machine actuator could still error if the other network devices don't return an IP address. The actuator should succeed if at least one network device returns a valid address.
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/469
```release-note
* …
```

Do not error on multiple network devices if at least one has a valid IP address

---

scripts/e2e/bootstrap_job/Makefile
scripts/e2e/e2e.sh

This patch updates the E2E tests to no longer use a hardcoded path to
the GCR keyfile, instead taking the location for the the env var.
Fixes #
This patch requires https://github.com/kubernetes/test-infra/pull/13773 to merged first. Tests should fail until it is.
/hold
^ to wait for dependency
```release-note
```

Remove E2E use of hardcoded path to key file

---

docs/troubleshooting.md

Signed-off-by: Jim Weber <jpweber@gmail.com>
Updates the troubleshooting document to fix the example of Preferring an IP address. the property of `preferredAPIServerCidr` was in line that created errors. 
Fixes #479 
```release-note
NONE
```

moved preferredAPIServerCidr in troubleshooting doc to correct line

---

pkg/cloud/vsphere/services/userdata/controlplane.go
pkg/cloud/vsphere/services/userdata/node.go
pkg/cloud/vsphere/services/userdata/userdata.go

This PR make the appropriate changes to cloud-init to set the hostname properly of the machine created.
Fixes #
This fixes the hostname isse faced on Nimbus VMs.
```release-note
```

setting hostname of machines using cloud-init

---

pkg/cloud/vsphere/services/certificates/certificates.go

allows for time skew in pivot cluster workflow
Fixes #503 
_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes. Not changing image versions.
```release-note
Adjust NotBefore on certificate generation to allow slight time skew.
```

allow for time skew in cert generation

---

docs/getting_started.md

This PR updates the getting started guide to reflect a few in-progress notes about the state of v1a2:
* Instructions for building `clusterctl` until the CAPI project publishes the artifact
* References the `ci/manifests` image instead of `release/manifests` since the latter is based on v1alpha1
Fixes #
This PR should be reverted once CAPI v1alpha2 and CAPV v1alpha2 are both released.
```release-note
```

Update getting started guide with info about v1a2'isms

---

examples/controlplane/controlplane.yaml

This PR modifies the generated yaml to have have the `files` and `preKubeadmCommads` section to write the hostname of the machine. 
This is related to the issue: https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/116 and 
Fixes #
```release-note
```

Manifests generation update

---

examples/controlplane/controlplane.yaml
examples/generate.sh

/kind bug
This patch adds the missing cloud provider configuration to the control plane machine's kubeadm config data.
Fixes #
```release-note
```

Add missing cloud provider config

---

pkg/cloud/vsphere/services/userdata/controlplane.go
pkg/cloud/vsphere/services/userdata/node.go

This PR is needed so that CAPV machine images are backward compatible between v1a1 and v1a2.
Fixes #499 
```release-note
cloud-init user data uses runcmd instead of kubeadm module
```

switching from kubeadm module to runcmd in cloud-init userdata

---

pkg/cloud/vsphere/services/govmomi/create.go

This PR allows a user to select the CRI socket to use. If no choice is provided then it defaults to containerd.
Fixes #
```release-note
* Selectable CRI socket, defaults to containerd
```

Selectable CRI socket

---

pkg/cloud/vsphere/services/govmomi/create.go

For kubeadm join, we should be reading CRISocket from the Join field. 
Fixes #
```release-note
```

use Join NodeRegistration for CRI socket path on kubeadm join

---

examples/generate.sh

/kind bug
This patch uses the correct CABPK image URI.
Fixes #
```release-note
* Fixes the kubeadm bootstrapper v0.1.0 image URI
```

Update generation script w correct CABPK image

---

examples/controlplane/controlplane.yaml

**What this PR does / why we need it**: This PR adds the following labels:
```
labels:
cluster.x-k8s.io/control-plane: "true"
cluster.x-k8s.io/cluster-name: "${CLUSTER_NAME}"
```
to be able to list vspheremachines that are part of a cluster through the function `GetVSphereMachinesInCluster()`.
Without this change, in #538 the loadbalancer_controller is not able to list vspheremachines  which result in the creation of a load balancer without a corresponding pool of machines/ips attached to it
Fixes #
```release-note …
```

add label to be able to list vspheremachines that are part of cluster

---

docs/getting_started.md
examples/cluster/cluster.yaml
examples/generate.sh

When kubeadconfig controller reconciles. It needs dnsDomain field. 
This documents in https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/blob/master/README.md
The current manifest generation does not provide that field, which caused below error on cabpk
```validation failure list:\nspec.clusterConfiguration.networking.dnsDomain in body is required"  "controller"="kubeadmconfig" "request"={"Namespace":"default","Name":"management-cluster-controlplane-0”}```
This pull request will add that field and fix ^^ issue 
Fixes #
_Please confirm …

Add service domain to the cluster config

---

scripts/e2e/bootstrap_job.template
scripts/e2e/bootstrap_job/clusterctl.sh
scripts/e2e/e2e.sh
scripts/e2e/generate-e2e-spec.sh

**What this PR does / why we need it**: As we do not build clusterctl anymore this PR updates the link to download the one released for CAPI
**Which issue(s) this PR fixes**: Fixes #562
/assign @akutz @figo 
```release-note
NONE
```

fix e2e: broken link to download clusterctl

---

pkg/cloud/vsphere/services/govmomi/vcenter/clone.go

Use the VirtualEthernetCardMacTypeManual constant for setting the NIC address type. 
Fixes #
```release-note
NONE
```

use govmomi types.VirtualEthernetCardMacType for NIC address type

---

.gitignore

This PR adds the `vendor` folder to `.gitignore` to prevent people from accidentally adding `vendor` to the Git index.
```release-note
NONE
```

Add the vendor directory to .gitignore

---

docs/getting_started.md
examples/generate.sh

The default version changed to 1.14.4: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/examples/generate.sh#L214
As I thought the default KUBERNETES_VERSION version is 1.13.6 without specifying it. It caused the error when kubeadm join api-server
```
Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "10.197.120.215:6443"
[discovery] Successfully established connection with API Server "10.197.120.215:6443"
[join] Reading configuration from the cluster...
[join] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[kubelet] Downloading configuration for the kubelet from the "kubelet-config-1.13" ConfigMap in the …
```

The default version changed to 1.14.4 but docs does not change

---

examples/default/addons.yaml
examples/pre-67u3/addons.yaml

In v1.16, the extensions/v1beta1 API group is removed and the calico addons still referencing that API group should also be removed. Thanks for catching this @figo 
Fixes #
```release-note
Default Calico addons should use API group apps/v1 instead of extensions/v1beta1
```

update calico addons to use apps/v1 instead of extensions/v1beta1

---

examples/default/addons.yaml
examples/pre-67u3/addons.yaml

Follow-up fix for https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/579, need to specify match selectors as part of apps/v1 update for Deployments. 
Fixes #
```release-note
Fix default calico addons missing match selectors for Deployments. 
```

add missing deployment selectors in calico addon

---

examples/default/controlplane/controlplane.yaml
examples/generate.sh
examples/pre-67u3/controlplane/controlplane.yaml

kubeadm using "k8s.gcr.io" by default, we default it to same
default value, although this change allow user to set it to different value.
Signed-off-by: Hui Luo <luoh@vmware.com>
Fixes #
```release-note
* Allow specification of a custom, default image repository
```

Allow user to set kubeadm clusterConfiguration imageRepository

---

api/v1alpha2/cloudprovider/encoding_test.go
api/v1alpha2/cloudprovider/types.go
pkg/cloud/vsphere/services/cloudprovider/csi.go

Supports adding the `cluster-id` field in the cloud config which is required by vSphere CSI driver. Uses the format "<cluster-namespace>/<cluster-name>" which is guaranteed to be unique on the management cluster. 
```release-note
Supports adding the `cluster-id` field in the cloud config which is required by vSphere CSI driver.
```

support cluster-id in cloud config which is required by vSphere CSI driver

---

pkg/cloud/vsphere/services/cloudprovider/csi.go

The [recommended manifests](https://github.com/kubernetes-sigs/vsphere-csi-driver/tree/master/manifests/1.14/deploy) for the DaemonSet and StatefulSet of the vSphere CSI driver  set `hostNetwork: true` on the pod spec. However, this causes issues wherever the statefulset is scheduled since the livenessprobe from both pods use conflicting ports.  
```shell
$ kubectl -n kube-system get po
NAME                                                    READY   STATUS    RESTARTS   AGE
calico-kube-controllers-7bfdd87774-b745l                1/1     Running   0          3m10s
calico-node-6n4sd                                       1/1     Running   0          3m10s
calico-node-bkvhj …
```

vSphere CSI daemonset and statefulset should use non-conflicting health ports for liveness

---

examples/generate.sh

kustomize (for reasons I don't know yet) removes double quotes on generate yaml fields. As a result, the `sshAuthorizedKeys` field in the kubeadm config would have a null value instead of the expected string value. To work around this, we can use single quotes for the SSH key value so kustomize will keep the single quoted string value instead of a null value.  
Fixes #589 
```release-note
Fix …
```

fix null field in SSH authorized keys due to kustomize removing double quotes

---

examples/generate.sh

Kustomize removes double quotes from generated manifests so we have to intentionally add single quotes for variables that may could generate invalid yaml. For our case, the resource pool variable can start with "*" which would result in invalid yaml unless we quote it. 
Fixes #
```release-note
manifests: single quote resource pool in manifest generation since it can begin with special …
```

single quote resource pool in manifest generation since it can begin with special characters like *

---

examples/default/cluster/cluster.yaml

The CNS docker images were moved from `cloudnativestorage/vsphere-block-csi-driver` to `vmware/vsphere-block-csi-driver`. Our manifest generation tool should reflect this change.
Fixes #
```release-note
CNS docker images were moved from cloudnativestorage/vsphere-block-csi-driver -> vmware/vsphere-block-csi-driver
```

CNS docker images were moved from cloudnativestorage/vsphere-block-csi-driver -> vmware/vsphere-block-csi-driver

---

docs/getting_started.md
examples/default/machinedeployment/machinedeployment.yaml

Fixes to CAPV docs:
* fixes the existing getting started guide to use the correct KubeadmConfig
* fix a bug in the manifest generator where the kubelet still set `--cloud-provider=vsphere` as the default. 
* fix invalid resource pool in examples
Fixes #
```release-note
Fix CAPV docs to:
* use updated KubeadmConfig with --cloud-provider=external 
* fix invalid resource pool in examples
```

Fixes to CAPV Docs

---

examples/default/cluster/cluster.yaml
pkg/cloud/vsphere/services/cloudprovider/csi.go

Sets `insecure: true` by default in the manifest generator, since CAPV doesn't really manage vCenter certificates yet. The option to set `insecure: false` still exists by updating it in the VSphereCluster resource.
Fixes #
```release-note
default `insecure: true` in the cloud provider since CAPV doesn't manage vCenter certificates yet
```

default insecure: true in the cloud provider since CAPV doesn't manage vCenter certificates yet

---

docs/getting_started.md

Follow-up doc fix from https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/599. CNS docker images were moved from `cloudnativestorage` -> `vmware`. The generated examples should reflect this. 
Fixes #
```release-note
NONE
```

update vSphere CNS images in getting started guide

---

config/manager/manager.yaml

Adds toleration for well-known taints like node-role.kubernetes.io/master to released CAPV manager manifest.
Fixes kubernetes-sigs/cluster-api#1486
```release-note
Adds toleration for well-known taints like node-role.kubernetes.io/master to released CAPV manager manifest.
```

add well-known tolerations to released CAPV manager manifest

---

docs/getting_started.md

Removes instructions for building `clusterctl` from getting started as v1a2 bin is built on `ClusterAPI` main repo.
As discussed in PR #613 
```release-note
Removes clusterctl build instructions
```

Remove clusterctl build instructions

---

api/v1alpha2/cloudprovider/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
examples/default/cluster/cluster.yaml
pkg/cloud/vsphere/services/cloudprovider/csi.go

There are two image repos that hard coded in `csi.go`: `livenessprobe` and `csi-node-driver-registrar`. This PR parameterized those two image repos so that we could pass them as a parameter in `cluster.yaml`. 
Tested by deploying a 3 worker nodes cluster, replaced `livenessProbeImage` and `registrarImage` fields to point to my personal image repo in `cluster.yaml` and it is working. Please double check

Parameterized livenessProbe image and registrar image

---

config/default/manager_credentials_patch.yaml
config/manager/kustomization.yaml
examples/default/provider-components/capv_manager_bootstrap_credentials.yaml
examples/default/provider-components/kustomization.yaml
examples/pre-67u3/provider-components/capv_manager_bootstrap_credentials.yaml
examples/pre-67u3/provider-components/kustomization.yaml

**What this PR does / why we need it**: This  PR drops the bootstrap credentials from the infrastructure-components. This should make `infrastructure-components.yaml` non-specific to an environment. 
**Which issue(s) this PR fixes** : Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/608
/assign @andrewsykim 
```release-note
```

drop capv-manager-bootstrap-credentials from infrastructure-components.yaml

---

pkg/cloud/vsphere/services/govmomi/service.go
pkg/cloud/vsphere/util/machines.go
pkg/cloud/vsphere/util/machines_test.go

Use `Machine.Name` instead of `VSphereMachine.Name` for VM names in vSphere. That way the hostname and name of the VM are matching. 
Fixes #623 
```release-note
use Machine.Name for VM name instead of VSphereMachine.Name
```

use Machine.Name for VM name instead of VSphereMachine.Name

---

examples/default/addons.yaml
examples/pre-67u3/addons.yaml

Removes StorageClass from addons.yaml, which removes any confusion from users thinking that CAPV is responsible for managing StorageClasses. StorageClasses should be created by the user or some operator that runs on top of the cluster. 
Fixes #360 
```release-note
Remove StorageClass from addons file, users should manage their own StorageClasses based on the CSI documentation. 
```

remove StorageClass from addons file

---

Makefile

**What this PR does / why we need it**: This PR allows us to pass a fixed version when generating `infrastructure-components.yaml`. it works using : `make release-manifests VERSION=x.y.z` 
**Which issue(s) this PR fixes** : Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/609
/assign @andrewsykim 
```release-note
NONE
```

allow passing a VERSION when generating infrastructure-components.yaml

---

config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml

**What this PR does / why we need it**: The CRD test was failing because the generated CRDs have an updated link
to idempotency conventions.
Fixes #
```release-note
```
/assign @andrewsykim

Fix idempotency convention link

---

pkg/cloud/vsphere/services/cloudprovider/csi.go

Follow-up to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/640, adds liveness probe check to CSI spec. 
```release-note
```

add liveness probe check to CSI deployments

---

pkg/cloud/vsphere/services/govmomi/service.go

**What this PR does / why we need it**: This fix checks vm existence even if the machineRef is not set, this covers the case where a vm delete happens fast enough through vcenter
**Which issue(s) this PR fixes** : Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/622
/assign @andrewsykim @akutz 
```release-note
NONE
```

check vm existence even if machineRef is not set

---

examples/generate.sh

We recently removed the -u flag from the manifest generator  but forgot to remove it from the usage output
Fixes #
```release-note
```

remove -u from generate manifests usage output

---

Dockerfile
scripts/e2e/e2e.sh

Bump default golang version to 1.12.10 to address CVE-2019-16276
Set golang_version argument, user can always build with specific
golang version by passing --build-arg golang_version:golang:1.x.x
Signed-off-by: Hui Luo <luoh@vmware.com>
**Which issue(s) this PR fixes** 
N/A
N/A
```release-note
```
cc @akutz @andrewsykim @jiatongw @frapposelli

Bump default golang version to 1.12.10 to address CVE-2019-16276

---

examples/generate.sh

/kind bug
This patch fixes an error when using the `-P` flag with the generator to set the CAPI manager's log level. The getopts string was missing a `:` character after the `P`, and so the shell was saying `OPTARG` was an unbound variable since the `-P` flag didn't pick up its value.
```release-note
* Fixes bug when using the -P flag with the manifest generator image
```

Fixes error when using -P flag with generator

---

hack/tools/generate-yaml/Dockerfile
hack/tools/manifests-base/Dockerfile
hack/tools/manifests-base/Makefile

/kind feature
This patch updates the manifest base image to use Git 2.20 and Kustomize 3.5.1 since the former was causing an error with Kustomize remote builds according to @yastij.
Fixes #
```release-note
* Update manifest base image to Git 2.20 and Kustomize 3.5.1
```

Update manifest base image & manifest image

---

controllers/vspheremachine_controller.go

fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/692

use equate-empty in comparing machine status

---

docs/getting_started.md

Modify Getting started guide to add a warning for careful handling of .ova suffix in envvars.txt file when VM template is created using vSphere 
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/671
```release-note
```

Add warning to getting started guide to carefully handle the .ova suffix

---

api/v1alpha2/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
docs/troubleshooting.md
pkg/util/constants.go
pkg/util/machines_test.go

/kind bug
/assign @akutz
`Cloud-Init Network Config Version 2` fails to use `Predictable Network Interface Names`. Instead it uses the `Cloud-Init Device Configuration ID` as the interface name. [Bug #1855945](https://bugs.launchpad.net/cloud-init/+bug/1855945) 
As a workaround, this PR adds `SetName` as an optional parameter to the `NetworkDeviceSpec`. When `SetName` is not specified, `cloud-init metadata` is configured with `set-name: "eth*"` where * equals the Device ID index. When `SetName` *is* specified, `cloud-init set-name` uses this value.
Summary:
- Adds `SetName` to `NetworkDeviceSpec`
- Adds `SetName` to `vspheremachines` and `vspheremachinetemplates` CRDs
- Adds templating for `set-name` to `pkg/util/constants.go` 
- Adds & updates …

Set network interface name with cloud-init set-name

---

hack/tools/openvpn/Dockerfile
hack/tools/openvpn/Makefile
hack/tools/openvpn/openvpn.sh

/kind feature
This patch introduces support for building a container image with a built-in OpenVPN client. This is useful for testing.
Fixes #
```release-note
```

A Dockerfile with a built-in OpenVPN client for testing

---

docs/getting_started.md
examples/default/controlplane/controlplane.yaml
examples/default/machinedeployment/machinedeployment.yaml
examples/pre-67u3/controlplane/controlplane.yaml
examples/pre-67u3/machinedeployment/machinedeployment.yaml

Subsequent runs of cloud-init, post the initial start-up, sometimes cause the machine hostname to be renamed to `localhost`. This is due to the way `cloud-init` `DataSourceVMwareGuestInfo.py` reconciles the hostname from multi-line entries within `/etc/hosts`.
```python
>>> socket.getaddrinfo('generic-cluster-1-controlplane-0', None, 0, socket.SOCK_DGRAM, 0, socket.AI_CANONNAME)
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, 'localhost', ('127.0.0.1', 0))]
```
https://github.com/vmware/cloud-init-vmware-guestinfo/blob/9e69060170b5b4210ec60ba2f09caf644617d91b/DataSourceVMwareGuestInfo.py#L544-L545
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when …

/etc/hosts update fixes cloudinit vmware reconcile

---

OWNERS
OWNERS_ALIASES

Add cluster-api-maintainers as approvers and reviewers to
OWNERS_ALIASES. This is consistent with both cluster-api and
cluster-api-provider-aws.
Fixes #
```release-note
NONE
```

Add cluster-api-maintainers to OWNERS_ALIASES

---

pkg/util/machines.go
test/e2e/capv_resource_generators.go
test/e2e/capv_test.go
test/e2e/framework/control_plane.go
test/e2e/suite_test.go

**What this PR does / why we need it**: 
This PR updates the e2e test that validates CAPV can deploy a multi-node, control plane to use the `KubeadmControlPlane` model.
**note**: This still keeps the single-node control plane test
```release-note
NONE
```

Refactor multi-node, control plane e2e test to use KubeadmControlPlane

---

config/default/kustomization.yaml

This PR adds clusterctl labels to all CAPV components generated when running `make release-manifests`. It removes the labels from selectors within the controller-manager deployment and services.
Ref kubernetes-sigs/cluster-api#1989
Here are some corresponding PRs made into CAPI and CAPA:
https://github.com/kubernetes-sigs/cluster-api/pull/2070
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1488
```release-note
Add …
```

Add clusterctl labels to CAPV components

---

examples/generate.sh

This defaulting avoid having a kubelet with 1.16.2 and 1.15.3 control plane
which is not supported
**What this PR does / why we need it**: This PR fixes a bug in the manifest generation, now If `KUBERNETES_VERSION` is not specified we default to v1.16.2 instead of v1.15.3, this avoids having a 1.16 kubelet and a 1.15 control plane which makes `kubeadm init` fail
```release-note
```

default the kubernetes version to v1.16.2 in the manifest generation

---

Makefile
hack/e2e.sh
test/e2e/suite_test.go

**What this PR does / why we need it**: This PR dump logs and other info of the bootstrap cluster into the artifacts directory
**Which issue(s) this PR fixes**: part of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/734
```release-note
```

dump the bootstrap cluster logs into the artifacts directory

---

test/e2e/capv_test.go
test/e2e/framework/control_plane.go

**What this PR does / why we need it**: This PR moves from waiting KCP nodes to be initialized to checking if they're provisioned 
```release-note
```

wait for KCP nodes to be provisioned

---

examples/default/cluster/cluster.yaml
pkg/services/cloudprovider/csi.go

**What this PR does / why we need it**: This PR bumps the CSI version to the latest release. This should avoid breaking setups in VMC, as its SDDCs are being upgraded to vsphere 7.0 which is not compatible with the current CSI version.
**Which issue(s) this PR fixes** Fixes #
```release-note
bump the vsphere csi driver to the newest release 1.0.2
```

bump csi version to the latest release

---

test/e2e/capv_test.go

**What this PR does / why we need it**: This PR removes deploying workers to speed up CI. it works locally but takes too much time on prow
```release-note
```

remove deploying workers to speed CI

---

hack/e2e.sh

This PR switch the e2e to use a centOS-based OVA. it's an attempt to remove flakes seen in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/730 and https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/725
Probably caused by https://github.com/kubernetes-sigs/image-builder/issues/90#issuecomment-579296188
```release-note
```

switch e2e to use a centOS-based OVA

---

api/v1alpha3/vspheremachine_types.go
api/v1alpha3/zz_generated.deepcopy.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
controllers/vspheremachine_controller.go

**What this PR does / why we need it**: This PR renames status fields related to errors reason and messages to match CAPI's expectation
```release-note
```

rename errorreason/message fields in vsphereMachine status

---

config/default/kustomization.yaml

This PR backports the clusterctl labels to v1alpha2 version of CAPV.
Ref https://github.com/kubernetes-sigs/cluster-api/pull/2112
Ref https://github.com/kubernetes-sigs/cluster-api/issues/1989
[Slack conversation for context](https://kubernetes.slack.com/archives/C8TSNPY4T/p1582129372253200)
**Note**
Please test against a CAPV cluster since I don't have resources to manually e2e test it.
```release-note
Backport clusterctl provider labels …
```

Backport clusterctl labels to CAPV components

---

clusterctl-settings.json

What this PR does / why we need it:
This PR fixes clusterctl-settings.json after changes introduced by https://github.com/kubernetes-sigs/cluster-api/pull/2355
```release-note
NONE
```
/assign @vincepri
/assign @yastij

fix-clusterctl-settings.json

---

examples/default/cluster/cluster.yaml
pkg/services/cloudprovider/csi.go

**What this PR does / why we need it**: cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/738
```release-note
```

cherry-pick of #738: bump csi version to the latest release

---

examples/generate.sh
go.mod
go.sum

**What this PR does / why we need it**: This PR updates CAPI and CABPK. This change is required to be able to upgrade to v1alpha3
```release-note
update CAPI to v0.2.10 and CABPK v0.1.6
```

update CAPI and CABPK dependencies

---

controllers/vspherecluster_controller.go

**What this PR does / why we need it**: This PR checks that all VSphereMachines are gone before deleting the VsphereCluster. This avoids dead-locking [here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/controllers/vspheremachine_controller.go#L142)
**Which issue(s) this PR fixes** : Fixes #761 
/assign @randomvariable @ncdc 
```release-note
Before deleting a VSphereCluster check if all the corresponding VSphereMachines are gone
```

check that vsphereMachines are deleted before deleting the vsphereCluster

---

config/webhook/kustomization.yaml
config/webhook/namespace.yaml

**What this PR does / why we need it**: This PR removes an extra namespace that is not used in the `config/` directory
```release-note
NONE
```

remove capv-webhook-system namespace from config/ directory

---

pkg/util/kubeadm.go

**Which issue(s) this PR fixes**: Fixes #769
/assign @detiber 
```release-note
kubeadmconfig is now fetched using the machine namspace instead configRef.Namespace
```

⚠️ always use the machine's namespace to fetch the kubeadmconfig

---

pkg/services/cloudprovider/csi.go

**What this PR does / why we need it**: This aligns the DefaultCSIMetadataSyncerImage with other versions. This needs to be cherrypicked
Fixes #
/assign @randomvariable @detiber 
```release-note
```

bump DefaultCSIMetadataSyncerImage to right patch version

---

config/manager/manager.yaml
main.go
pkg/manager/manager.go

Add liveness / readiness probes
similar did here: https://github.com/kubernetes-sigs/cluster-api/pull/2156
Fixes #
```release-note
manager: Add liveness/readiness probes
```
/cc @vincepri

✨manager: add liveness/readiness probes

---

docs/getting_started.md

Now there's actual releases, don't need to specify the versions in the clusterctl commands.
Also, adds a note that other tools other than `govc` can be used

Simplify getting started

---

config/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
hack/tools/go.mod
hack/tools/go.sum

**What this PR does / why we need it**: This PR updates controller-gen to `v0.2.6-0.20200226180227-d6efdcdd90e2` and unblocks CI failures seen after moving to the rc-3 and uncovered by #812
Fixes #
```release-note
```

update controller-gen to v0.2.6-0.20200226180227-d6efdcdd90e2

---

pkg/services/cloudprovider/csi.go

Fixed the value of DefaultCSIControllerImage to point to the right image for the vsphere-csi-controller container.
Reference manifest at https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/master/manifests/1.14/deploy/vsphere-csi-controller-ss.yaml#L42.
Signed-off-by: George Goh <gohge@vmware.com>
The value for DefaultCSIControllerImage should point to the CSI driver, and not syncer.
Fixes #
NONE

Fixed the value of DefaultCSIControllerImage pointing to the right image

---

api/v1alpha2/vspherecluster_webhook.go
api/v1alpha2/vspheremachine_webhook.go
api/v1alpha2/vspheremachinetemplate_webhook.go
config/webhook/manager_webhook_patch.yaml
main.go
pkg/manager/manager.go

Actually enables the conversion webhooks, and corrects the port in the manifest.
Fixes #814 
```release-note
:bug: Enable conversion webhooks
```

Fix and enable conversion webhooks

---

hack/tools/haproxy/ansible/roles/cloudinit/tasks/main.yml
hack/tools/haproxy/ansible/roles/haproxy/tasks/main.yml
hack/tools/haproxy/packer.json

**What this PR does / why we need it**: This PR adds variables for the dataplane and guestinfo URLs to enable air gap build
/assign @ncdc @figo @dims 
```release-note
```

add variable for dataplane and guestinfo urls to enable air gap builds

---

pkg/services/govmomi/vcenter/clone.go

**What this PR does / why we need it**: This PR removes overriding the of the annotation
**Which issue(s) this PR fixes** : Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/811
```release-note
```

remove annotation overriding to preserve the template's annotations

---

pkg/services/govmomi/vcenter/clone.go

**What this PR does / why we need it**: This PR removes clonespec from the logs as contains some sensitive information
**Which issue(s) this PR fixes** : Fixes #809 
```release-note
```

strip clonespec from logs

---

config/default/credentials.yaml
config/default/manager_credentials_patch.yaml
main.go
pkg/manager/manager.go
pkg/manager/options.go

**What this PR does / why we need it**: This PR moves `capv-controller-manager` to file-based secret injection
**Which issue(s) this PR fixes** : Fixes #776
```release-note
capv-controller-manager now reads credentials from a file. default path is /etc/capv/credentials.yaml
```

inject CAPV credentials as a file

---

pkg/manager/manager.go
pkg/manager/options.go

**What this PR does / why we need it**: This PR fixes an unmarshaling issues and adds errors swallowing so that the `capv-controller-manager` can start in a webhook mode without credentials
```release-note
```

fix file-based credentials injection

---

controllers/vspheremachine_controller.go

**What this PR does / why we need it**: This PR let delete go through for vsphereMachine if we don't find a vsphereVM
Fixes #836 835 
/assign @randomvariable @frapposelli 
```release-note
let vsphereMachine delete go through if we are not able to find a corresponding vspherevm
```

let delete go through if we are not able to find the vspherevm

---

controllers/haproxyloadbalancer_controller.go
controllers/vspherecluster_controller.go

**What this PR does / why we need it**: when we are trying to reconcile network or load balancer, some times we are waiting for some fields to read, when they're not set we return withtout errors or requeue. This PR add requeues for these cases 
Fixes #
/cc @frapposelli @vincepri 
```release-note
```

requeue when we are waiting and not returning an error

---

api/v1alpha3/cloudprovider_encoding.go

This PR fixes the MarshalCloudProviderArgs() method for CPI, adds initialization for the map and fixes the args passed to the CPI

Fix MarshalCloudProviderArgs() for CPI

---

pkg/haproxy/config.go

This PR aligns HA proxy health-check thresholds to the one used in CAPA https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/9913ac8dbb96ed9bcffa6eba75b886cd4ef8c20b/pkg/cloud/services/elb/loadbalancer.go#L263-L269
```release-note
Align HA proxy health-check thresholds to the one used in CAPA for a better consistency across providers
```
/assign @randomvariable

increase haproxy health-check thresholds

---

pkg/services/govmomi/service.go

**What this PR does / why we need it**: This PR does not swallow errors for reconcileNetworkStatus 
```release-note
```

do not swallow errors reconcileNetworkStatus

---

hack/tools/haproxy/ansible/roles/sysprep/tasks/main.yml

Sometimes when HAproxy starts, the `network-online` unit will go online before an ipv4 is successfully acquired. This will lead the certificate generation process to use an ipv6 LLA `fe80:` as it's the only IP available at the time, this will fail the script as it doesn't know how to parse an ipv6 address.

avoid LLA with default dhcp settings in haproxy

---

controllers/haproxyloadbalancer_controller.go

This PR does two things:
1- It filters out IPv6 addresses from the backend endpoints for haproxy, this is a short-term fix that will need to be removed when #859 is addressed
2- Waits for the new control plane node to be ready before adding it to the list of backend endpoints, avoiding the case where the IP is added to HAproxy *during* the join phase and the joining node ends up talking to itself via HAproxy
```release-note
IPv6 support is disabled in HAProxyLoadBalancer
```
/assign @yastij @randomvariable 
/cc @akutz @dims @vuil

Make BackEndpointsForCluster() more robust

---

controllers/haproxyloadbalancer_controller.go
controllers/vspherecluster_controller.go
controllers/vspheremachine_controller.go
controllers/vspherevm_controller.go
main.go
pkg/manager/constants.go
pkg/manager/options.go

**What this PR does / why we need it**: This PR wires the controllers with `--max-concurrent-reconciles` flag and bumps its default value.
/assign @vincepri 
```release-note
wire --max-concurrent-reconciles with the controllers and bump its default value
```

wire max-concurrent-reconciles with higher default

---

pkg/util/constants.go
pkg/util/machines.go
pkg/util/machines_test.go

**What this PR does / why we need it**: This PR adds the ability the set `wait-on-network` to wait for ipv4 and/or ipv6 addresses 
Related to https://github.com/vmware/cloud-init-vmware-guestinfo/pull/35
/cc @frapposelli @randomvariable 
```release-note
set `wait-on-network` to wait for ipv4 and/or ipv6 addresses
```

add logic to wait for IPv4 and/or IPv6

---

hack/tools/haproxy/ansible/roles/cloudinit/tasks/main.yml

This PR adds an ansible task to remove a canary file for cloud-init that prevents network from being configured by data passed to cloud-init.

fix cloudinit network in haproxy ova

---

docs/getting_started.md

**What this PR does / why we need it**: This PR preps for the v0.6.3 release by linking to the latest HAProxy OVA
Fixes #
```release-note
```

point to the new CAPV HAProxy OVA

---

hack/tools/haproxy/kickstart.json

Use of hardware entropy sources is less contentious than using haveged in #879 
Fixes #
```release-note
* Enable rngd for entropy gathering
```

Add rng-tools as default entropy gatherer to HAProxy

---

hack/tools/haproxy/kickstart.json

This patch sets the default password expiry to -1, which makes it be equivalent to never. The default in PhotonOS is 90 days, which would lead to long-term issues with both the root account and any accounts created by cloud-init. Even though passwords are not used to access the image, an expired password means that admins logging in (even via SSH keypair, the only way) are prompted to change a password.
We also set the PhotonOS root account back to its [default](https://github.com/vmware/photon/blob/7b2f140e6496c7baaae4c99df9c1c9fdadabb9d3/installer/ks_config.txt#L156-L175). Though it's kind of a funny "default" -- if you don't set text or crypted fields in the kickstart, the installer aborts as they are required fields. 🤷‍♂
There is no reason to …

haproxy: set PhotonOS password expiry to never

---

pkg/context/fake/fake_vm_context.go
pkg/services/govmomi/vcenter/clone.go

**What this PR does / why we need it**: This PR fixes a corner case where clone tasks are done before patching a `vspherevm`'s statuts. 
Whenever a task is done, we send a notification to the vspherevm controller to reconcile the `vspherevm`, so potentially we can end up in a situation where we are reconciling with a stale status 
Fixes #
```release-note
NONE
```

patch early to avoid concurrent clones

---

pkg/services/cloudprovider/csi.go

This PR removes `ImagePullPolicy: Always` for csi images.
If `ImagePullPolicy: Always` forced, some csi images can't be pulled in an air-gapped environment.
```
$ kubectl get po -n kube-system
NAME                                               READY   STATUS             RESTARTS   AGE
coredns-76d6dbd6f6-7h6xs                           1/1     Running            0          10m
coredns-76d6dbd6f6-vd2wm                           1/1     Running            0          10m
etcd-vsphere-quickstart-vh6cr                      1/1     Running            0          9m39s
kube-apiserver-vsphere-quickstart-vh6cr            1/1     Running            0          9m38s
kube-controller-manager-vsphere-quickstart-vh6cr   1/1     Running            0          9m34s …
```

remove csi ImagePullPolicy for air-gapped environments

---

controllers/haproxyloadbalancer_controller.go
controllers/vspheremachine_controller.go
controllers/vspherevm_controller.go
pkg/services/govmomi/errors.go
pkg/services/govmomi/util.go
pkg/services/govmomi/vcenter/clone.go

**What this PR does / why we need it**: This PR fixes some rare race condition(s) where you could potentially end up overwriting the `spec.biosUUID` field, leading to a cloning loop
/hold
holding for some more testing
```release-note
fix a race condition that leads to drop the bios uuid
```

Fix race condition that leads to dropping the biosuuid

---

controllers/haproxyloadbalancer_controller.go
controllers/vspheremachine_controller.go
controllers/vspherevm_controller.go
pkg/services/govmomi/errors.go
pkg/services/govmomi/util.go
pkg/services/govmomi/vcenter/clone.go

Cherry pick of #926 on release-0.6.
#926: Fix race condition that leads to dropping the biosuuid

Automated cherry pick of #926: Fix race condition that leads to dropping the biosuuid

---

controllers/vspheremachine_controller.go

Use DataSecretName to get Bootstrap (cloudinit) data
Fixes #923

Use DataSecretName to get Bootstrap data

---

controllers/vspheremachine_controller.go

Cherry pick of #925 on release-0.6.
#925: Use DataSecretName to get Bootstrap data

Automated cherry pick of #925: Use DataSecretName to get Bootstrap data

---

controllers/vspherevm_controller.go
pkg/services/govmomi/vcenter/clone.go

**What this PR does / why we need it**: This PR adds back the fix introduced in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/883 and that we removed in #926, the rational behind this was that patching in the `vspherevm_controller` was early enough. But it seems like it's not from what was reported by a user.
```release-note
re-apply the concurrent clones fix
```

re-apply the conccurent clones fix

---

controllers/vspherevm_controller.go
pkg/services/govmomi/vcenter/clone.go

Cherry pick of #946 on release-0.6.
#946: re-apply the conccurent clones fix

Automated cherry pick of #946: re-apply the conccurent clones fix

---

api/v1alpha3/types.go
api/v1alpha3/vspheremachine_webhook.go
api/v1alpha3/vspheremachine_webhook_test.go
api/v1alpha3/vspheremachinetemplate_webhook.go
api/v1alpha3/vspheremachinetemplate_webhooks_test.go
api/v1alpha3/vspherevm_webhook.go
api/v1alpha3/vspherevm_webhook_test.go
api/v1alpha3/webhooks.go
api/v1alpha3/zz_generated.deepcopy.go
config/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
config/webhook/kustomization.yaml
config/webhook/kustomizeconfig.yaml
config/webhook/manifests.yaml
config/webhook/webhookcainjection_patch.yaml

**What this PR does / why we need it**: This PR adds validation logic to CAPV, this prevents any users from creating resources/updating fields that shouldn't be and checks formatting in some cases
**Which issue(s) this PR fixes** : Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/853
```release-note
add validating webhook for VSphereMachines, VSphereVMs, VSphereMachineTemplates and VSphereClusters
```

add support for validating webhooks

---

.golangci.yml
api/v1alpha3/vspheremachine_webhook.go
api/v1alpha3/vspheremachine_webhook_test.go
api/v1alpha3/vspherevm_webhook.go
api/v1alpha3/vspherevm_webhook_test.go

**What this PR does / why we need it**: follow-up of #970 that fixes a case breaking `clusterctl move` + improves formatting
Fixes #
```release-note
```

fix validating webhooks to avoid breaking clusterctl move

---

controllers/vspherevm_controller.go
pkg/services/govmomi/util.go

CAPV has support to assign static IP to VSphereMachine, but the static IP itself can be assigned by different means. For eg., one such implementation can be using a third party controller to modify VSphereMachine to add static IP after the object is created.
Irrespective of the implementation choice to assign static IP, if DHCP is disabled, the CAPV controllers have to wait for static IPs to be available and then continue to provision VMs.
Currently, if both DHCP4 and DHCP6 are disabled and a staticIP is set in HAProxyLB's Network.Devices.IpAddrs, the VSphereVM for HAProxyLB goes to 'Ready' without any IPAddress in the status. The HAProxyLB then never goes to 'Ready' since its indefinitely waiting for the VSphereVM's IPAddress.
This PR checks if …

wait for staticIP to be set in VSphereVM

---

Makefile
packaging/flavorgen/cmd/root.go
packaging/flavorgen/flavors/flavors.go
packaging/flavorgen/flavors/generators.go

**What this PR does / why we need it**: This PR adds support for a kube-vip flavor, two env variables are introduced:
`CONTROL_PLANE_ENDPOINT_IP`: the VIP we want to use
`VIP_NETWORK_INTERFACE`: the network interface we want to bind the VIP to (e.g. `eth0`)
```release-note
add support for a kube-vip flavor
```

add support for the kube-vip flavor

---

api/v1alpha3/vspheremachine_webhook.go
api/v1alpha3/vspheremachine_webhook_test.go
api/v1alpha3/vspherevm_webhook.go
api/v1alpha3/vspherevm_webhook_test.go

**What this PR does / why we need it**: This PR relaxes the validating webhooks to be able to update the devices, this avoids breaking IPAM use cases
Fixes #
```release-note
```

🐛 relax constraints on the validating webhooks to update ips and enable IPAM use cases

---

controllers/vspherevm_controller.go

**What this PR does / why we need it**: This PR waits for the `VSphereVM` to report Addresses before marking it as Ready
**Which issue(s) this PR fixes**  Fixes #938 
/assign @vincepri 
```release-note
wait to report Addresses on the VSphereVM before marking it as ready
```

wait to have IP addresses reported before making a VSphereVM as ready

---

packaging/flavorgen/flavors/generators.go

**What this PR does / why we need it**: This PR bumps kube-vip to 0.1.7 and cleans up some unused variables
Fixes #
/assign @gab-satchi 
```release-note
bump kube-vip to 0.1.7
```

bump kube-vip to 0.1.7

---

config/default/credentials.yaml

**What this PR does / why we need it**: This PR adds quotes are the username and password in our credentials yaml file, this avoids issues with entries that starts with special chars like "@"
**Which issue(s) this PR fixes** : Fixes #980 
/assign @vincepri  
```release-note
```

add quotes around username/password

---

Makefile
packaging/flavorgen/cmd/root.go
packaging/flavorgen/flavors/flavors.go

This PR provides an example `clusterctl` `flavor` for deploying CAPV cluster with an external load balancer that fronts the control plane endpoints (kube-apiservers). This is an alternative to the HAProxy Load Balancer based deployment.
This flavor requires that the load balancer be configured out-of-band, prior to the CAPV cluster deployment.
**Which issue(s) this PR fixes** *
Fixes #904 
Not sure in what format or where in the repo this should best reside. Could this flavor template eventually form part of the release?
```release-note
```

External Load Balaner Flavor example

---

packaging/flavorgen/flavors/generators.go

**What this PR does / why we need it**: This PR fixes a bug in our templating, where if you supplied a custom network interface name to kube-vip, it wouldn't start (we weren't setting `DeviceName` into the `VSphereMachineTemplate`).
After giving more thoughts for a quickstart template we don't need to template that kind of things.
Fixes #
/assign @gab-satchi 
```release-note
```

hardcode network interface to eth0 in the cluster-template.yaml

---

Makefile
README.md
hack/tools/mdlint/Dockerfile
hack/tools/mdlint/Makefile

I happened to be messign with the markdownlint container in another
project, and decided it was a good opportunity to update this. The
exception added to the README is due to a change in the linter not
allowing raw HTML by default, but I felt like that it was okay to have
in the README.
Fixes #
I've already pushed v0.23.2 of this container to gcr.io, so local `make` commands will work and pull the right version. Once this is merged, I will make the change in `test-infra` to use the new container as well. I've also verified that running this iwth the old …

update mdlint to v0.23.2

---

packaging/flavorgen/flavors/flavors.go
packaging/flavorgen/flavors/generators.go

This PR makes the haproxy and the external-load balancer templates to trigger CSI installation back (as it was before https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/986).
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/992
This PR changes release manifests
```release-note
Fix a regression preventing CSI installation when using the haproxy and the external-load balancer template
```

Fix CSI installation for non default templates

---

pkg/services/govmomi/util.go

**What this PR does / why we need it**: This PR fixes an NPE where we access the description before checking if `nil` or not
/assign @fabriziopandini 
```release-note
check the description before using it into a condition
```

check the description before using it in a condition

---

pkg/util/constants.go
pkg/util/machines_test.go

This PR selectively adds dhcp flags in the machine's cloud-init metadata, only when either of them is set to true. This is to handle the centos 7 cloud-init issue where dhcp is not disabled in static IP mode, resulting in an additional DHCP IP.
Fixes #996 
```release-note
NONE
```

add dhcp4 and dhcp6 flags in cloud-init metadata only when either of them is set to true

---

pkg/services/govmomi/errors.go
pkg/services/govmomi/service.go
pkg/services/govmomi/util.go

**What this PR does / why we need it**: This PR fixes a bug where the deletion flow of a `VSphereVM` is blocked if its folder doesn't exist.
**Which issue(s) this PR fixes**: Fixes #1000 
/assign @vincepri @fabriziopandini 
```release-note
let deletion go through when the folder of a VSphereVM doesn't exist
```

let deletion go through when the folder of a VSphereVM doesn't exist

---

examples/default/cluster/cluster.yaml
packaging/flavorgen/flavors/generators.go
pkg/services/cloudprovider/cloud-controller-manager.go
test/e2e/data/infrastructure-vsphere/cluster-template.yaml

This PR bumps vSphere cloud provider version to v1.2.0 as it has some good improvements / bug fixes. v1.2.0 should be compatible with any Kubernetes versions v1.1.0 supported.
Fixes #1002 
This PR changes vSphere cloud provider from v1.1.0 to v1.2.0
```release-note
bump the CPI from 1.1.0 to 1.2.0
```

bump vSphere cloud provider  version to 1.2.0

---

api/v1alpha3/vspherevm_webhook.go
api/v1alpha3/vspherevm_webhook_test.go

**What this PR does / why we need it**: This PR relaxes the validating webhooks for the VSphereVMs to allow updating the bootstrapRef. This is needed to avoid errors reported in #1008 after upgrading from v0.6.6 to v0.7.0. We introduced an update to the `bootstrapRef` logic in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/925 to support custom bootstrap data.
**Which issue(s) this PR fixes** : Fixes #1008
```release-note
relax the validating webhooks to allow updating the bootstrapRef of VSphereVMs
```

relax the validating webhooks to allow updating the bootstrapRef of VSphereVMs

---

Makefile
metadata.yaml

Adds a metadata.yaml outlined by the [docs](https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#metadata-yaml) so users aren't forced to update clusterctl in order to use a new CAPV release.
Fixes #999 
```release-note
NONE
```

Adds metadata.yaml for clusterctl contracts

---

packaging/flavorgen/flavors/generators.go
templates/cluster-template.yaml
test/e2e/data/infrastructure-vsphere/kustomization/cluster-resource-set-label.yaml
test/e2e/data/infrastructure-vsphere/kustomization/cluster-resource-set.yaml
test/e2e/data/infrastructure-vsphere/kustomization/cluster-template.yaml

This PR adapt templates/flavor generator to the syntax of envsubst (without spaces inside ${}).
This makes it possible to use templates both with clusterctl - which tolerated spaces but not requires them - and the plain envsubst.
```release-note
Change templates to use the envsubst syntax for variables (without spaces inside ${})
```

Use envsubst syntax

---

pkg/services/govmomi/vcenter/clone.go
pkg/services/govmomi/vcenter/clone_test.go

Prevent users from hitting an undescriptive error message, while attempting to clone a VM from a template with a required disk size less than the disk space specified on the template.
Fixes #1030 
```release-note
NONE
```

Add check for template disk size

---

packaging/flavorgen/flavors/generators.go

**What this PR does / why we need it**: This PR bumps kube-vip to `0.1.8` and sets the leader election params to the default values
```release-note
bump kube-vip to v0.1.8 and adjust leader election params
```

bump kube-vip to 0.1.8 and adjust leader election params

---

test/e2e/README.md
test/e2e/config/vsphere-ci.yaml

**What this PR does / why we need it**: This PR moves the E2Es to test against 1.19
/assign @fabriziopandini @gab-satchi 
```release-note
```

move E2Es to kubernetes 1.19.1

---

docs/migrations.md

**What this PR does / why we need it**: This PR adds steps to migrate from `HAProxyLoadBalancer` to a `kube-vip` setup
```release-note
```

document migration path from haproxy to kube-vip

---

test/e2e/common.go
test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/e2e/e2e_suite_test.go

**What this PR does / why we need it**: This PR is a followup to the CAPI v0.3.11 upgrade, it fixes the e2e and moves the CI to v0.3.11
```release-note
```

upgrade CI to CAPI v0.3.11 and fix e2e

---

OWNERS
OWNERS_ALIASES

Move ncdc to emeritus status
(cherry picked from commit de3aa74797fd152b3a6d6b81c10552a9929f4f0c)
Fixes #
```release-note
NONE
```

[0.7] Move ncdc to emeritus status

---

api/v1alpha3/cloudprovider_types.go
api/v1alpha3/haproxyloadbalancer_types.go
api/v1alpha3/vspherecluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml

**What this PR does / why we need it**: This PR is a followup to #1045 to kickoff deprecation of fields
**Which issue(s) this PR fixes**:  Fixes #
```release-note
Deprecate CPI/CSI, HAProxyLoadBalancer and the insecure mode from v1alpha3. Removal planned in v1alpha4
```

deprecate API fields in v1alpha3 for future removal

---

api/v1alpha3/types.go
api/v1alpha3/vspheremachine_webhook.go
api/v1alpha3/vspheremachinetemplate_webhook.go
api/v1alpha3/vspherevm_webhook.go
config/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
pkg/services/govmomi/vcenter/clone.go

**What this PR does / why we need it**: This PR introduces the support of storage policies within CAPV. The current plan is to enforce with webhooks that datastore shouldn't be set at the same time as storage policy name
**Which issue(s) this PR fixes**: Fixes #1043 
```release-note
```

support storage policies in CAPV

---

api/v1alpha3/vspheremachine_webhook.go
api/v1alpha3/vspheremachinetemplate_webhook.go
api/v1alpha3/vspherevm_webhook.go
pkg/services/govmomi/vcenter/clone.go

**What this PR does / why we need it**: This PR relaxes storage policy setting, as users might want to target a specific datastore within a given storage policy
Fixes #
```release-note
```

relax storage policy constrains and enable datastore too

---

config/default/credentials.yaml
pkg/manager/options_test.go

This patch escapes the vCenter credentials while reading them from the credential file. This makes sure that samAccountUsername formats work as well.
Fixes #1071
n/a
```release-note
Adds escaping logic for vCenter credentials
```

Adds escaping logic for vCenter credentials

---

Makefile
docs/development.md

Includes copying the `metadata.yml` over to the overrides directory when running this target. Updates the documentation to include dev semver if not present in the file.
Fixes #1075
n/a
```release-note
NONE
```

Updates the dev-manifests target

---

Dockerfile
config/manager/manager_auth_proxy_patch.yaml

Uses nonroot user for CAPV
Fixes #1089
Porting a similar PR from CAPI
```release-note
Uses nonroot user for CAPV for successful deployment when PSPs are enabled 
```

Updates image to use nonroot user for CAPV

---

controllers/vspheremachine_controller.go

Updates the vSphereMachine controller logic to use the WaitingForCPAvailableReason if the machine is waiting for bootstrap data because the CP is not yet functional.
Fixes #1037
Similar to [this change](https://github.com/kubernetes-sigs/cluster-api/pull/3726) in the CAPD provider
```release-note
Updates vSphereMachine condition status to report for Control Plane to be ready
```

Modifies vSphereMachine condition status to report for CP to be ready

---

controllers/vspheremachine_controller.go

Updates the vSphereMachine controller logic to use the WaitingForCPAvailableReason if the machine is waiting for bootstrap data because the CP is not yet functional. 
This is a **backport of the PR** #1102 to the 0.7 branch.
Fixes #1037
n/a
```release-note
Updates vSphereMachine condition status to report for Control Plane to be ready
```

Adds new reason to vspheremachine condition

---

pkg/services/cloudprovider/cloud-controller-manager.go

Adds the necassesary rights to the ClusterRole for the CCM lock to function
Fixes #1113 
```release-note
Fixes ClusterRole for CCM
```

Add missing coordination.k8s.io to ClusterRole for CCM

---

pkg/services/govmomi/service.go

Patches the vSphereVM object to commit the task reference after kicking off power on/off tasks. There's a race condition where a reconcile can happen before the patch is committed in the defer block and that new reconcile can send out duplicate tasks to power on/off VM.
original issue was just around power on but during testing discovered that the issue is possible for both on/off tasks. 
Fixes #1122 
```release-note
NONE
```

Patches VsphereVM after initiating power on/off tasks

---

pkg/services/govmomi/service.go

Cherry pick of #1125 on release-0.7.
#1125: Patches VsphereVM after initiating power on/off tasks

Automated cherry pick of #1125: Patches VsphereVM after initiating power on/off tasks

---

pkg/services/cloudprovider/cloud-controller-manager.go

What this PR does / why we need it:
Adds the necassesary rights to the ClusterRole for the CCM lock to function
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #1113
Release note:
Fixes ClusterRole for CCM

Add missing coordination.k8s.io to ClusterRole for CCM [Cherry-pick into master]

---

controllers/vspherecluster_controller.go
packaging/flavorgen/flavors/flavors.go
pkg/services/cloudprovider/csi.go

Update vsphere-csi-driver release to the latest v2.1.0 version
Fixes #1078 
- Adds a ConfigMap that csi uses to configure feature states
- Update container images to new release
```release-note
Update vsphere-csi-driver to v2.1.0
```

Update vsphere-csi-driver release to v2.1.0

---

controllers/vspherecluster_controller.go
packaging/flavorgen/flavors/flavors.go
pkg/services/cloudprovider/csi.go

Cherry pick of #1081 on release-0.7.
#1081: Update vsphere-csi-driver release to v2.1.0

Automated cherry pick of #1081: Update vsphere-csi-driver release to v2.1.0

---

packaging/flavorgen/flavors/generators.go
pkg/services/cloudprovider/cloud-controller-manager.go

**What this PR does / why we need it**: This PR bumps our manifest generation to the latest cloud-provider-vsphere version
Fixes #
/assign @gab-satchi 
```release-note
```

bump cloud-provider-vsphere to v1.18.1

---

.golangci.yml
go.mod
hack/e2e.sh
test/e2e/README.md
test/e2e/config/vsphere-ci.yaml
test/e2e/e2e_suite_test.go
test/e2e/log_collector.go

This patch enables log collection for E2E tests
Fixes #734
n/a
```release-note
Enables log collection for E2E tests
```

Enable log collection for E2E tests

---

pkg/services/govmomi/vcenter/clone.go

**What this PR does / why we need it**: This PR fixes a panic where datastoreRef was nil that was introduced in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1118, it also randomize the picking of the compatible datastore, to avoid blocking when the first compatible datastore is full
```release-note
```

fix panic and randomize chosen datastore when using storage policies

---

api/v1alpha3/vspherevm_webhook.go
api/v1alpha3/vspherevm_webhook_test.go

Add the ability to alter vSphereVM thumbprints 
Fixes #1134
```release-note
allow changing of thumbprints of exing clusters without redepolying
```

Add ability to alter vSphereVM thumbprints and tests for it

---

api/v1alpha3/vspherevm_webhook.go
api/v1alpha3/vspherevm_webhook_test.go

Add the ability to alter vSphereVM thumbprints 
Fixes #1134
```release-note
allow changing of thumbprints of exing clusters without redepolying
```

[cherry-pick into master] Add ability to alter vSphereVM thumbprints and tests for it 

---

Dockerfile
go.mod
hack/tools/go.mod

This patch updates the golang version to `1.15.8`
Fixes #1140
n/a
```release-note
Update underlying golang version to 1.15.8
```

Updates golang version to 1.15.8

---

api/v1alpha3/condition_consts.go
controllers/vspherevm_controller.go
controllers/vspherevm_controller_test.go
pkg/context/fake/fake_controller_manager_context.go

This patch introduces a new reason to indicate that the `VMProvisionedCondition` is halted because of static IP Address allocation.
Fixes #1116 
n/a
```release-note
Adds a new reason for VMProvisionedCondition
```

Adds new reason for VMProvisionedCondition

---

api/v1alpha3/condition_consts.go
controllers/vspherevm_controller.go
controllers/vspherevm_controller_test.go
pkg/context/fake/fake_controller_manager_context.go

This patch backports #1115 to the release-0.7 branch
n/a
```release-note
Adds a new reason for VMProvisionedCondition
```

Adds new reason for VMProvisioning condition

---

pkg/services/govmomi/service.go
pkg/services/govmomi/vcenter/clone.go

This PR fixes an issue where host based storage policies couldn't be applied to VMs during the clone process. With these changes, the storage policy is reconciled separately after the clone VM, reconcile network and reconcile metadata completes. 
Fixes #1146 
The reconcile function returns early if the VM is powered on. This is to avoid the scenario where the storage policies have already been reconciled and the VM is in a running state but the user either attaches extra disks or uses CSI to provision new disks with a different storage policy. The capv …

Reconcile storage policy after cloning the VM

---

pkg/util/machines.go
pkg/util/machines_test.go

Adds a check for the length of the network status before generating the metadata string
Fixes #1155
```release-note
NONE
```
/hold

Checks for length of network statuses while generating metadata

---

README.md

The links to OVAs are broken because the point to http when they need to point to https
Fixes #
/assign @timothysc
```release-note
```

fix image links from http to https

---

docs/proposal/20210311-single-controller-multitenancy.md

/kind design
Proposing a way to allow CAPV to accommodate multiple tenants within a single instance
#1123 
Thanks to the AWS and Azure folks for pioneering the multi-tenancy efforts in their respective providers. @devigned @randomvariable @nader-ziada @sedefsavas

First draft of multi-tenancy proposal

---

packaging/flavorgen/cmd/root.go
packaging/flavorgen/flavors/crs/cpi.go
packaging/flavorgen/flavors/crs/csi.go
packaging/flavorgen/flavors/crs/util.go
packaging/flavorgen/flavors/env/envsubts_consts.go
packaging/flavorgen/flavors/flavors.go
packaging/flavorgen/flavors/generators.go
packaging/flavorgen/flavors/util/helpers.go
test/e2e/data/infrastructure-vsphere/kustomization/cluster-resource-set-label.yaml
test/e2e/data/infrastructure-vsphere/kustomization/cluster-resource-set.yaml

A rebased version of #1059 by @yastij 
This PR moves our templates to deploying the CPI through CRS and refactors flavorgen for better re-usability across its packages
- uses v1alpha4 types
Fixes #
```release-note
NONE
```

Copy of PR1059 - move CPI over to CRS and refactor flavorgen

---

controllers/vspherecluster_controller.go
controllers/vspherecluster_controller_test.go

**What this PR does / why we need it**: This PR fixes a bug in multi-tenancy. When the secret is missing, the vspherecluster controller should continue and remove the finalizer from the deleting `VSphereCluster` to unblock deletion
```release-note
remove the vspherecluster finalizer when the secret does not exist
```

remove the vspherecluster finalizer when the secret does not exist

---

controllers/vsphereclusteridentity_controller.go

sets condition for VSphereClusterIdentity once it's ready for use
Fixes #
```release-note
NONE
```

sets ready condition for VSphereClusterIdentity

---

api/v1alpha4/vspheremachine_webhook.go
api/v1alpha4/vspheremachine_webhook_test.go

This adds checks so that networks in vSpherMachines are also validated on update and not just on create
none
```release-note
Validate vSphereMachine Network assignment also upon update, not just on create
```

add checks for network validation on update in vSphereMachine

---

api/v1alpha3/vspheremachine_webhook.go
api/v1alpha3/vspheremachine_webhook_test.go

Backports https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1192 into alpha 3
Fixes #
none
```release-note
Validate vSphereMachine Network assignment also upon update, not just on create
```

add checks for network validation on update in vSphereMachine #1192 of a3

---

api/v1alpha3/condition_consts.go
controllers/vsphereclusteridentity_controller.go
controllers/vsphereclusteridentity_controller_test.go

Fixes #1200 
```release-note
fixes issue with VSphereClusterIdentity attempting to update a secret when it's not found.
```

vsphereclusteridentity returns early when secret isn't found

---

controllers/vspherecluster_controller.go
controllers/vspherevm_controller.go
main.go
pkg/constants/constants.go
pkg/context/controller_manager_context.go
pkg/manager/manager.go
pkg/manager/options.go
pkg/services/govmomi/create_test.go
pkg/services/govmomi/vcenter/clone_test.go
pkg/session/session.go

This PR adds session.Keepalive to vimclient 
Fixes # 
Ref PR https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1072 
```release-note
```

add keepalive roundtripper to vimClient

---

api/v1alpha4/vspherecluster_types.go
api/v1alpha4/vspheremachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml

Adds additional print columns to VSphereCluster and VSphereMachine for v1alpha4 types. Porting the changes from #1041 
Fixes #1119
```release-note
Adds additional columns to VSphereCluster & VSphereMachine types
```

Printcolumn added in VSphereCluster and VSphereMachine

---

main.go
pkg/manager/manager.go
pkg/manager/options.go
test/helpers/envtest.go

This patch removes duplicates code and reuses types from controller-runtime
Fixes n/a
n/a 
```release-note
NONE
```

Refactor manager and options to use controller-runtime structs

---

controllers/vspheredeploymentzone_controller_domain.go
controllers/vspheremachine_controller.go
controllers/vspherevm_controller_test.go
pkg/services/govmomi/cluster/cluster_suite_test.go
pkg/services/govmomi/cluster/rule.go
pkg/services/govmomi/cluster/service.go
pkg/services/govmomi/cluster/vmgroup.go
pkg/services/govmomi/cluster/vmgroup_test.go
pkg/services/govmomi/metadata/metadata.go
pkg/services/govmomi/service.go

This patch fixes a couple of bugs in the failure domain implementation:
1. VSphere DRS enforces host placement according to affinity rules before powering on the VM. Since the VM was being added after being powered on, the host placement wasn't being enforced. Add the VM to the VM group before powering it on, makes sure that the placement constraint is enforced.
2. Instead of re-creating the same category with a new associable type (which is not supported by Vsphere), we are now patching the category to update the associable type for a category.
3. Updating the failure domain on the VSphereMachine is not allowed, hence removed it.
Fixes #1217 
None …

Failure Domain: Fixes VM Placement on Hosts

---

docs/proposal/20201103-failure-domain.md

Adds the missing category flag `-c` in the failure domain proposal.
n/a
```release-note
NONE
```

Fixes govc attach command

---

controllers/vspherecluster_controller.go
controllers/vspherecluster_controller_test.go

We now check the connectivity regardless of whether CloudProviderConfiguration is set on the spec.
That property has been deprecated and it is valuable to check this connectivity early and surface this on the VSphereCluster status rather than just on VSphereVMs.
This also fixes a bug where the status could be set to "False" if the secret was not found and then never properly set to "True" once the secret becomes present.
This fixes #1209 for the `release-0.7` branch. 
This fix was originally proposed against the `master` branch via PR #1214. However, it was noted in that PR that  #1095 already includes a fix for this issue on master so that is likely to be merged instead, at which point #1214 may be closed or …

Fix VSphereCluster VCenterAvailable condition

---

Dockerfile

Bumps golang from 1.16.0 to 1.16.7.
Signed-off-by: Geetika Batra <geetikab@vmware.com>
Fixes #
```release-note
```

Bumps golang from 1.16.0 to 1.16.7.

---

OWNERS
OWNERS_ALIASES

Updating the OWNERS file, and making the following proposals in the process:
* @MaxRink and @vrabbi to become reviewers
* @gab-satchi and @srm09 to become co-maintainers
* @frapposelli to move to emeritus (thanks for all the contributions!)
and then some cleanup, which is mostly making the list of Cluster API maintainers and SIG Cluster Lifecycle leads up to date.
```release-note
NONE
```
/hold
for consensus

Update OWNERS files

---

docs/getting_started.md

This change adds documents the `VSPHERE_STORAGE_POLICY` variable that needs to be explicitly set in `clusterctl.yaml`. 
Fixes #1183 
```release-note
NONE
```

📖add details about VSPHERE_STORAGE_POLICY to doc

---

feature/feature.go
feature/gates.go
main.go

Currently CAPV doesn't have cpability of adding features via
feature gates. This change would add feature gate machinery.
Signed-off-by: Geetika Batra <geetikab@vmware.com>
Fixes #
```release-note
```

Add feature gate machinery

---

packaging/flavorgen/flavors/util/helpers.go

This PR adds the `VSphereStoragePolicy` field from `VSphereMachineTemplate` to the `stringVars` slice. This enables the flavorgen workflow to add `""` around the `VSPHERE_STORAGE_POLICY` which in turn enables `viper`(used by clusterctl to replace env varaibles) to recognize `""` as strings and not `null`.
Fixes #1244 
```
NONE
```

🐛 add vsphereStoragePolicy to stringVars slice

---

packaging/flavorgen/flavors/generators.go
test/e2e/data/infrastructure-vsphere/capi-upgrades/v1alpha3/cluster-template.yaml
test/e2e/data/infrastructure-vsphere/capi-upgrades/v1alpha4/cluster-template.yaml

Updates the `kube-vip` image path for cluster templates
n/a
```release-note
NONE
```

Bumps kube-vip to v0.3.5 and update templates

---

test/e2e/capi_upgrade_test.go

Signed-off-by: Sagar Muchhal <muchhals@vmware.com>
This patch temporarily disables clusterctl upgrade tests
Fixes # n/a
```release-note
NONE
```

Skipping clusterctl upgrade tests

---

api/v1alpha3/vspherevm_types.go
api/v1alpha3/zz_generated.conversion.go
api/v1alpha3/zz_generated.deepcopy.go
api/v1alpha4/vspherevm_types.go
api/v1alpha4/zz_generated.conversion.go
api/v1alpha4/zz_generated.deepcopy.go
api/v1beta1/vspherevm_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
controllers/vspherevm_controller.go
pkg/services/govmomi/util.go

Cherry pick of #1279 on master.
#1279: fix aggressive reconciliation on task failures

Automated cherry pick of #1279: fix aggressive reconciliation on task failures

---

api/v1beta1/types.go
api/v1beta1/vspherefailuredomain_types.go
api/v1beta1/vspherefailuredomain_webhook_test.go
api/v1beta1/vspheremachine_webhook.go
api/v1beta1/vspheremachine_webhook_test.go
config/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
config/webhook/manifests.yaml
controllers/vspheredeploymentzone_controller_domain_test.go
pkg/services/govmomi/create_test.go
pkg/services/govmomi/vcenter/clone_test.go
pkg/session/session.go

based on @farodin91's work in #1274
The datacenter defaulting was moved from the session creation logic to the default values of the VSphereMachine resource. This way it's possible to create a session without a datacenter, which should fix the connectivity check of VSphereClusters that use a vCenter that doesn't have a default datacenter.
It also adds a test for the VSphereFailureDomain default webhook as I initially also added defaulting there, which doesn't make sense.
Fixes #1266 
```release-note
Move datacenter defaulting to VSphereMachine
Fix VSphereCluster never reaching …
```

Move datacenter defaulting to resource defaults

---

controllers/vspherecluster_controller.go
controllers/vspherecluster_controller_test.go

Deletion of orphaned VSphereMachine (VSphereMachine object without Machine object owner references) during VSphereCluster object deletion.
Fixes #
This is a special scenario wherein the Machine objects are deleted before they can set owner references on the VSphereMachine object. This leads to the object being orphaned and the VSphereCluster object deletion is stuck forever.  
```release-note
```

🐛 Adds deletion logic for orphaned VSphereMachines

---

pkg/manager/options.go
pkg/manager/options_test.go
test/e2e/log_collector.go
test/helpers/envtest.go
test/helpers/webhook.go

The ioutil package has already been deprecated in golang 1.16, please see [go1.16#ioutil](https://golang.org/doc/go1.16#ioutil). So we also need to replace all the ioutil with os and io.

Replace ioutil with io and os

---

pkg/manager/options.go
pkg/manager/options_test.go
test/e2e/log_collector.go
test/helpers/envtest.go
test/helpers/webhook.go

Cherry pick the PR [pull/1286](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1286) to release-0.8.

Replace ioutil with os and io for release-0.8

---

packaging/flavorgen/flavors/generators.go

Cherry pick of #1291 on release-0.7.
#1291: Updates the kube-vip image path in templates
```release-note
```

Automated cherry pick of #1291: Updates the kube-vip image path in templates

---

controllers/vspherecluster_controller.go
controllers/vspherecluster_controller_test.go

Cherry pick of #1284 on release-0.8.
#1284: Adds logic for deletion of orphaned VSphereMachine
```release-note
```

Automated cherry pick of #1284: Adds logic for deletion of orphaned VSphereMachine

---

api/v1alpha3/types.go
api/v1alpha4/vspherefailuredomain_types.go
api/v1alpha4/vspherefailuredomain_webhook_test.go
api/v1alpha4/vspheremachine_webhook.go
api/v1alpha4/vspheremachine_webhook_test.go
config/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
config/webhook/manifests.yaml
controllers/vspheredeploymentzone_controller_domain_test.go
pkg/services/govmomi/create_test.go
pkg/services/govmomi/vcenter/clone_test.go
pkg/session/session.go

Cherry pick of #1277 on release-0.8.
#1277: move datacenter defaulting to resource defaults

Automated cherry pick of #1277: move datacenter defaulting to resource defaults

---

test/e2e/data/cni/calico/calico.yaml

This patch updates the image paths used to deploy Calico while running the e2e tests.
Fixes # n/a
n/a
```release-note
NONE
```

Updates path of calico images for E2E tests

---

controllers/vspheremachine_controller.go

The clusterToVSphereMachines mapper gets a list of machines in a cluster
and enqueues objects using the Machine's name instead of the corresponding
VSphereMachine's name. If the VSphereMachine and Machine object are named differently,
the controller can't reconcile the VSphereMachine object since it tries
to find it by the wrong name. This commit changes the mapper to get and enqueue VSphereMachine objects
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1307
_Please confirm that if this PR changes any image versions, then that's …

Enqueue VSphereMachine in clusterToVSphereMachines mapper

---

controllers/vspheremachine_controller.go

Cherry pick of #1306 on release-0.8.
#1306: Enqueue VSphereMachine in clusterToVSphereMachines mapper
```release-note
```

Automated cherry pick of #1306: Enqueue VSphereMachine in clusterToVSphereMachines mapper

---

controllers/vspheremachine_controller.go

After `clusterctl move` for self-managed CAPV clusters, worker machines take around 10-15 minutes to go to "Running" phase. 
It could be due to the following reasons:
1. During `clusterctl move`, the Status fields are removed. So none of the CAPI objects retain the status fields, including the Cluster object. Once the Cluster.Spec.Paused field is unset after move, controllers begin to reconcile and the status fields get set again.
2. The [capv vsphereMachine controller](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/controllers/vspheremachine_controller.go#L316) while reconciling the VsphereMachine object checks for the `Cluster.Status.InfrastructureReady` field before proceeding, which will be `false` immediately after …

Add watch on cluster.status.infrastructureReady to reconcile vsphereMachine when cluster infrastructure is ready

---

api/v1alpha3/vspheredeploymentzone_conversion.go
api/v1alpha3/vspherefailuredomain_conversion.go
api/v1alpha4/vspheredeploymentzone_conversion.go
api/v1alpha4/vspherfailuredomain_conversion.go
api/v1beta1/vspheredeploymentzone_conversion.go
api/v1beta1/vspheredeploymentzone_types.go
api/v1beta1/vspherefailuredomain_conversion.go
controllers/controllers_suite_test.go
controllers/vspheredeploymentzone_controller.go
controllers/vspheredeploymentzone_controller_test.go
controllers/vspheremachine_controller.go
controllers/vspheremachine_controller_unit_test.go
controllers/vspherevm_controller.go
pkg/util/machines.go
pkg/util/machines_test.go
test/helpers/envtest.go

This patch includes the following changes:
- Updates the key to be set for failure domain lookup to be the name of the VSphereDeploymentZone
- Adds conversion functions for VSphereDeploymentZone & VSphereFailureDomain types
- Implements deletion logic for VSphereDeploymentZone CRs.
Fixes #1300 
```release-note
- Updates the key to be set for failure domain lookup to be the name of the VSphereDeploymentZone
- Adds conversion functions for VSphereDeploymentZone & VSphereFailureDomain types
- Implements deletion logic for VSphereDeploymentZone …
```

Implement deletion logic for VSphereDeploymentZone

---

docs/getting_started.md

`clusterctl config`  command was deprecated, it should be adjusted to `clusterctl generate`
https://github.com/kubernetes-sigs/cluster-api/pull/4778
Fixes #
```release-note
NONE
```

Fix clusterctl subcommand typo in getting_started

---

go.mod
go.sum

Revision v0.0.0-20211118193625-3a50e2e58c47 of
github.com/vmware-tanzu/vm-operator no longer exists. Update to latest
master since there isn't a recent tag.
Signed-off-by: Johanan Liebermann <jliebermann@microsoft.com>
Fixes #
```release-note
```

fix vm operator deps

---

test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/e2e/data/infrastructure-vsphere/kustomization/base/cluster-resource-set-csi-insecure.yaml
test/e2e/data/infrastructure-vsphere/kustomization/base/kustomization.yaml

CI fixes for private vCenter URL, supersedes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1346
n/a
```release-note
NONE
```

Changes for private vCenter URL in CI

---

test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/e2e/data/infrastructure-vsphere/kustomization/cluster-resource-set-csi-insecure.yaml
test/e2e/data/infrastructure-vsphere/kustomization/kustomization.yaml

Signed-off-by: Sagar Muchhal <muchhals@vmware.com>
(cherry picked from commit 9280be79bcbf440edf56f11c71515b0be8cf5a9e)
Cherry picking [this](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/commit/9280be79bcbf440edf56f11c71515b0be8cf5a9e) commit to release-0.8
```release-note
NONE
```

Cherry pick #1370 to release 0.8

---

test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/e2e/data/infrastructure-vsphere/kustomization/base/cluster-resource-set-csi-insecure.yaml
test/e2e/data/infrastructure-vsphere/kustomization/base/kustomization.yaml

Cherry pick of #1370 on release-1.0.
#1370: Changes for private vCenter URL in CI
```release-note
```

Automated cherry pick of #1370: Changes for private vCenter URL in CI

---

config/rbac/aggregate_label_to_cluster_role_patch.yaml

This PR adds `""` around `true` in the `config/rbac/aggregate_label_to_cluster_role_patch.yaml` file. Without them, the `envsubst` was causing an error during `tilt up`. 
```release-note
NONE
```

add quotes to aggregate label role patch yaml

---

Makefile

The `PATH` assignment is currently breaking on WSL when `$(PATH)` contains parentheses, e.g. when the variable contains a substring such as the following: `/mnt/c/Program Files (x86)/`
None
None
```release-note
NONE
```

Quote PATH variable

---

Makefile

Not having a default value for `--e2e.artifacts-folder` breaks the e2e tests when run locally (Prow overrides this flag with the `ARTIFACTS` env var).
None
None
```release-note
NONE
```

Set default e2e artifact folder

---

apis/v1alpha3/vspheremachine_conversion.go
apis/v1alpha3/vspheremachinetemplate_conversion.go
apis/v1alpha3/vspherevm_conversion.go
apis/v1alpha3/zz_generated.conversion.go
apis/v1alpha4/vspheremachine_conversion.go
apis/v1alpha4/vspheremachinetemplate_conversion.go
apis/v1alpha4/vspherevm_conversion.go
apis/v1alpha4/zz_generated.conversion.go
apis/v1beta1/types.go
apis/v1beta1/zz_generated.deepcopy.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
pkg/services/govmomi/vcenter/clone.go
pkg/services/govmomi/vcenter/clone_test.go

The VirtualMachineCloneSpec only allow 1 disk on the vm when cloning. This restricts using certain OSes that ship with more than 1 disk by default, like Bottlerocket or Ceph. This change to spec allows to specify more than 1 disk and its sizes, so that capv can clone and create multi-disk vms.
* Adds API changes to specify more than 1 disk on the `VirtualMachineCloneSpec`. 
* New field `AdditionalDisksGiB` is an array of type `int32` to represent additional disks on the vm
CAPV will ignore any additionalDisks specified on spec, but not part of template. That is, CAPV will not spin up any additional disks.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …

Support multiple disks on OVA for full clone mode

---

Makefile
test/e2e/capv_quick_start_test.go
test/e2e/e2e_suite_test.go
test/e2e/storage_policy_test.go

Adding Ginkgo focus variable to facilitate running different sets of E2E tests in CAPV prow jobs
Fixes # n/a
This does not change the default behavior of any tests, this will be used later in the prow jobs.
```release-note
NONE
```

Adds conditional ginkgo foucs to e2e job

---

api/v1alpha3/vspheredeploymentzone_conversion.go
api/v1alpha3/vspherefailuredomain_conversion.go
api/v1alpha4/vspheredeploymentzone_conversion.go
api/v1alpha4/vspheredeploymentzone_types.go
api/v1alpha4/vspherefailuredomain_conversion.go
controllers/controllers_suite_test.go
controllers/vspheredeploymentzone_controller.go
controllers/vspheredeploymentzone_controller_test.go
controllers/vspheremachine_controller.go
controllers/vspheremachine_controller_unit_test.go
controllers/vspherevm_controller.go
pkg/util/machines.go
pkg/util/machines_test.go
test/helpers/envtest.go

This patch includes the following changes:
- Updates the key to be set for failure domain lookup to be the name of the VSphereDeploymentZone
- Adds conversion functions for VSphereDeploymentZone & VSphereFailureDomain types
- Implements deletion logic for VSphereDeploymentZone CRs.
It is a back port of #1316 with changes to API versions for VSphereDeploymentZone conversions
Fixes #1359 
```release-note
- Updates the key to be set for failure domain lookup to be the name of the VSphereDeploymentZone
- Adds conversion functions for VSphereDeploymentZone & …
```

Backport deletion logic for VSphereDeploymentZone

---

docs/getting_started.md
packaging/flavorgen/flavors/env/envsubts_consts.go
packaging/flavorgen/flavors/generators.go

Hardcoding `eth0` as the kube-vip interface breaks environments where interface names other than `eth0` are used.
kube-vip supports interface autodetection as of `v0.4.0`, which can be leveraged.
Fixes #1374 
```release-note
Don't hardcode kube-vip interface
```

Introduce override for kube-vip interface

---

controllers/vspherevm_controller.go

Cherry pick of #1272 on release-0.8.
#1272: handle nil vsphere machine for vsphere vm
```release-note
```

Automated cherry pick of #1272: handle nil vsphere machine for vsphere vm

---

Makefile
apis/v1alpha3/conversion.go
apis/v1alpha4/conversion.go
hack/tools/tools.go
pkg/services/vimmachine.go

- `verify-boilerplate`: updated the Copyright section in the required files
- `verify-gen`: added this target to verify go generated files are up to date
- `verify-modules`: added this target to verify go modules are up to date
Fixes #1388

Align CAPV Makefile targets with CAPI

---

Makefile
hack/e2e.sh
test/e2e/capi_upgrade_test.go

Use the `GINKGO_SKIP` args to add `-skip` flag (to the `ginkgo run` command) for each space separated arguments passed to the variable. This alongwith GINKGO_FOCUS var enables us to run/skip specific e2e tests
This has been borrowed from the CAPI E2E test setup which eliminates the
need to create multiple sh files to run specific tests.
Fixes n/a
Once the PR is merged, the follow up task would be to create test-infra jobs to run `conformance` and `clusterctl-upgrade` tests in their own jobs.
```release-note
NONE
```
**Example**
To skip say the PR Blocking test (the PR Blocking tests should have the label [PR-Blocking] in its `Describe` directive), we can use: …

Adds a provision to skip E2E tests

---

go.mod
go.sum
test/helpers/envtest.go
test/helpers/mod.go
test/helpers/mod_test.go

Fixes CAPI CRD path lookup for envtests
fixes #1410 
```release-note
NONE
```

Fixes CAPI CRD path lookup for envtests

---

pkg/services/network/network.go
pkg/services/network/network_test.go

**What this PR does / why we need it**: The virtualnetwork name is derived from vspherecluster name. While configuring VirtualMachine's virtualnetwork, the virtualnetwork name is derived from cluster
Fixes #
```release-note
```

fix virtualnetwork name in configureVirtualMachine

---

Makefile
controllers/serviceaccount_controller_intg_test.go
hack/boilerplate/boilerplate.py
hack/verify-api-conversion.sh

#1387  introduced a new make target `verify-conversions`. This PR adds a script which will be run as a pre-submit job to verify that the conversion is implemented for all API types. 
Test-infra issue - #https://github.com/kubernetes/test-infra/issues/25075  
Once this PR is merged, we could probably combine all the `verify` targets under a single make target. Similar to what @sbueringer suggested #https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1363#issuecomment-1021933590
```release-note
NONE
```

✨ add script to run `verify-conversions` make target

---

packaging/flavorgen/flavors/generators.go

This bumps kube-vip to `v0.4.1`.
None
```release-note
Update kube-vip to v0.4.1
```

Bump kube-vip to v0.4.1

---

test/e2e/capi_upgrade_test.go

Re-enabling the cluster upgrade tests that had been disabled earlier
fixes #1369

Re-enable cluster upgrade e2e tests

---

Makefile
hack/ci-test-coverage.sh

Currently there is no way to check test coverage.
This PR will adds provision for the same.
Signed-off-by: geetikab@vmware.com <geetikab@vmware.com>
Fixes #
```release-note
```

Adds provision to check test coverage

---

test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml

This PR changes the CAPI components version in order to fix the CI failures
```release-note
NONE
```

Fixes CAPI components for upgrade tests

---

config/rbac/aggregate_kcp_label_to_clusterrole_patch.yaml
config/rbac/kustomization.yaml

This PR adds the `kubeadm.controlplane.cluster.x-k8s.io/aggregate-to-manager: "true"` label to the ClusterRole. This is to ensure that the KCP is allowed to create `vsphereMachineTemplates` and `vsphereMachines`.
Fixes #1345
cc: @weikaipan 
```release-note
NONE
```

🌱 add aggregate cluster-role label to the KCP manager role

---

controllers/vspheredeploymentzone_controller.go
controllers/vspheredeploymentzone_controller_test.go

This PR fixes a panic while deleting the deployment zone when machines are using it.
Fixes #1424 
n/a
```release-note
Fixes panic while deployment zone deletion
```

Fixes panic while deployment zone deletion

---

apis/v1alpha3/zz_generated.conversion.go
apis/v1alpha4/zz_generated.conversion.go
pkg/services/govmomi/util.go
pkg/services/govmomi/util_test.go
test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/e2e/data/shared/metadata.yaml

This PR fixes the clusterctl upgrade tests which test API conversions between `v1alpha3 -> v1beta1` and `v1alpha4 -> v1beta1` types.
As part of the tests, a bug was identified which caused the workload clusters upgraded from alpha to beta version to not get deleted since patching of the VSphereVM objects was failing due to zero value for `.status.RetryAfter` being set to `null` which was not a valid string. The issue was due to a bug in the K8s 1.19 release line which was fixed in the 1.20 release line onwards.
This patch updates the template to point to a v1.20.1 k8s version template
```release-note
NONE
```

Update k8s version template for CI runs

---

test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml

**What this PR does / why we need it**: #1434 introduced an extra space in the e2e image names.
None
None
```release-note
NONE
```

Remove extra space in e2e image names

---

test/e2e/capi_machine_deployment_rollout_test.go

Currently, there is no e2e test for Machine Deployment Rollout.
This PR adds the same.
Fixes #
```release-note
```

Adds e2e test for Machine Deployment Rollout test

---

test/e2e/capv_clusterclass_quickstart_test.go

As part of the ClusterClass flavorgen PR, I made the tests `PR-Blocking` in order to get immediate feedback from the prow jobs. But we don't need these tests to be PR-Blocking. This PR takes care of that.

🌱 make clusterclass test non `PR-Blocking`

---

Makefile
test/e2e/README.md

Replace GC_KIND variable with SKIP_RESOURCE_CLEANUP

---

Makefile
test/e2e/README.md

**What this PR does / why we need it**
Adds `USE_EXISTING_CLUSTER` as an environment variable to the Makefile. This variable is passed to the e2e test command where it enables using an existing cluster instead of creating a new one.:
Fixes #1439.
`nil`

Add USE_EXISTING_CLUSTER variable for e2e tests

---

metadata.yaml

Fixes #1464 
```
Fix #1464 "clusterctl cannot find release 1.1.0" by adding missing 1.1 releaseseries data to metadata.yaml.
```

🐛 Fixes clusterctl metadata for v1.1.x release

---

docs/releasing.md

This updates the release doc to include the step to verify the presence of an entry in the `metadata.yaml` file when releasing a new minor version.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1464
```release-note
NONE
```

📖 Adds info to update metadata.yaml during release generation

---

metadata.yaml

Cherry pick of #1465 on release-1.1.
#1465: Add missing 1.1 releaseseries data to metadata.yaml.
```release-note
```

🐛 Automated cherry pick of #1465: Fixes clusterctl metadata for v1.1.x release

---

pkg/util/machines.go

This patch removes the reference to `ObjectMeta.ClusterName` field from the codebase.
Fixes #1481
Removes the field being used in the error message, no behavioral change
```release-note
Removes usage of deprecated ObjecteMeta field
```

Removes usage of deprecated ObjecteMeta field

---

pkg/services/vmoperator/control_plane_endpoint.go
pkg/services/vmoperator/vmopmachine.go
pkg/services/vmoperator/vmopmachine_test.go

There are old version of cluster created by CAPW that depends on `capw` labels on `VirtualMachine` for some functionality. For example CloudProviderVsphere depends on this https://github.com/kubernetes/cloud-provider-vsphere/issues/608
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1483
The deprecation process hasn't been decided yet. Once it's decided, will update in the original issue.
```release-note
Add …
```

Add legacy `capw` labels to VirtualMachine for backward compatibility

---

controllers/vspherecluster_reconciler.go
controllers/vspherecluster_reconciler_test.go
controllers/vsphereclusteridentity_controller.go

This PR does this following - 
- Check if the older VSphereClusterIdentity is present and delete it during the reconcileDelete phase. This is to make sure that clusters upgraded from v1alpha3 to v1alpha4/v1beta1 can be deleted once the finalizers are removed
- Check only the group and kind(and not the version) while setting ownerRef on VSphereClusterIdentity
- Remove explicit secret deletion from VSphereClusterReconciler (this already happens during the delete reconcile loop of VSphereClusterIdentity)
Fixes #1482
```release-note
NONE
```

🐛 Delete legacy finalizer, fix setting ownerRef for `VSphereClusterIdentity `

---

controllers/vspherecluster_controller.go
controllers/vspherecluster_controller_test.go
controllers/vsphereclusteridentity_controller.go

This PR backports the secret deletion fix from `v1.1.0`. More more details, please refer to [this](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1486) PR
Fixes #
```release-note
```

🐛 Backport secret deletion fix to v1.0.0 from PR #1486

---

docs/proposal/20210823-gpu-support.md

This commit adds a proposal which enables GPU support
in CAPV using.
Signed-off-by: Geetika Batra <geetikab@vmware.com>
Fixes #
```release-note
```

Proposal for GPU and PCI passthrough support

---

pkg/identity/identity.go
pkg/identity/identity_test.go

Fixes # Breaks down the  GetCredentials method into ValidateIdentity, CreateSecretKey, GetKey, GetNamespceKey
```release-note
```

Refactored GetCredentials Method

---

go.mod

This PR adds a `replace` directive for `sigs.k8s.io/cluster-api`, which is required because of our dependence on the `cluster-api/test` package which uses a relative import for `cluster-api`. Reference: https://github.com/vmware-tanzu/tanzu-framework/issues/1590.
Currently, running `go mod tidy` / `make modules` or `go get -d ./...` returns (tested on go `1.16.0` and `1.17.0`):
```
go: sigs.k8s.io/cluster-api/test@v1.1.3 requires
sigs.k8s.io/cluster-api@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
make: *** [Makefile:236: modules] Error 1
```
With this patch applied, we should no longer expect this outcome.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …

Add replace directive for `cluster-api` in `go.mod`

---

pkg/record/recorder_test.go

Adds missing tests for `recorder.Eventf()` and `recorder.Warnf()`. These functions are similar to `recorder.Event()` and
`recorder.Warn()` (already tested) and are used to log events to the event recorder but with message formatting with `fmt.Sprintf`
under the hood.
Fixes #1419
Signed-off-by: ditsuke <ditsuke@protonmail.com>

Add missing tests for the `pkg/record`

---

pkg/services/govmomi/extra/extra_suite_test.go

**What this PR does / why we need it**
This PR adds test cases for the public methods under the services/govmomi/extra package. These methods are used to
set cloud init data (used on VM startup) and to set other configuration keys. The new tests cover:
Passed a string => string map, this method should append all these key, value pairs to the config as `types.OptionValue` structs.
Passed byte arrays, these methods are expected to:
- Store the data in a `guestinfo.userdata`/`guestinfo.metadata` key with a single pass of base64 encoding.
- Add a key to indicate the encoding format.
- Ensure the data passed is encoded with exactly a single pass of base64, which includes checking for existing
base64 encoding and undoing them before encoding again with 1x base64.
**Which issue(s) this PR …

Add tests for the `services/govmomi/extra` package

---

Makefile
hack/tools/mdlint/Dockerfile
hack/tools/mdlint/Makefile

The v0.31.1 release of markdownlint was created in Feb 2022. This
updates our mdlint container to use this latest version.
Testing locally by creating image with:
```
cd hack/tools/mdlint
make
docker images # Just to check
cd ../../..
make lint-markdown
```

Update mdlint to v0.31.1

---

README.md

Removes incorrect office hours UTC time. Instead lists only the Pacific timezone and adds a time converter instead.
n/a
n/a
```release-note
NONE
```

Removes misleading UTC time for office hours

---

controllers/vmware/test/controllers_suite_test.go
go.mod
go.sum
main.go
pkg/manager/manager.go
pkg/manager/manager_test.go
pkg/manager/options.go

Add filesystem watch on the file storing credentials for
capv-manager-bootstrap-credentials
Unit tests added
**What this PR does / why we need it**: This PR adds a filesystem Watch for the CAPV bootstrap credentials that updates the file under /etc/capv/credentials.yaml. If there's any update the manager is updated accordingly through the Watch events notifier. 
Fixes #1275 
```release-note
NONE
```

Add notifier for CAPV credentials file

---

pkg/services/govmomi/metadata/metadata_suite_test.go

**What this PR does / why we need it**
Adds test cases for public methods from the metadata package. The metadata package's exposed methods are used in creating tags and tag categories for `VSphereFailureDomain` objects.
Passed a valid metadata context, a category name and associable resource type the method should:
- If a category with the same name doesn't already exist -- create a new category with a matching name and and associable resource type. The method should also return a valid non-empty category ID which can be used to reference the ID through the context's tag manager. 
- If a category with the same name exists -- update the category by merging in any new associable resource type. The category ID returned must be the same as the existing category's ID.
Passed a valid metadata …

Add tests for the `services/govomi/metadata` package

---

test/e2e/config/vsphere-ci.yaml
test/e2e/e2e_suite_test.go
test/e2e/govmomi_test.go

Some of the e2e test runs on testgrid keep failing due to failures in the test listed in `storage_policy_test.go` file. The reason for the failure is that the govmomi Client object we use to assert some conditions times out due to inactivity. As part of an earlier PR, a `Keep-Alive` handler was added to the client which did not seem to solve the issue. The reason was that the groutine for the handler needs an explicit call to `client.Login()` method to get activated. 
This patch slightly modifies the creation of the govmomi Client object and adds an explicit call to login after adding the keep alive handler and also logs out the session once the test is finished.
n/a
```release-note
NONE
```

Start the Keep Alive handler for VSphere client used in e2e tests

---

controllers/vspherecluster_reconciler.go
controllers/vspherecluster_reconciler_test.go
controllers/vsphereclusteridentity_controller.go
controllers/vsphereclusteridentity_controller_test.go
pkg/identity/identity.go
pkg/identity/identity_test.go

This change allows that secrets can be owned by external tools such as sealed secret.
Fixes #1431 
```release-note
Allow secrets to be owned by external tools
```

Allow secrets to be owned by external tools

---

Makefile

Our makefile links to a blog on writing well-documented makefiles. This blog was moved to a new location recently, breaking our reference.

chore: Fix reference link in Makefile

---

config/manager/manager.yaml
controllers/vspherecluster_reconciler.go
controllers/vspheredeploymentzone_controller.go
controllers/vspherevm_controller.go
main.go
pkg/session/session.go

We now use the `keep-alive` functionality by default, eliminating the need for it to be an opt-in flag. Thus this PR:
Fixes #1520

Move the `keep-alive` functionality out of the feature flag (+ deprecate the flag)

---

Makefile
hack/tools/Makefile
hack/tools/go.mod
hack/tools/tools.go

We were lacking a target to generate apidiffs in our Makefile. Upstream, CAPI already had such a target referenced in the parent issue. This target will make it c convenient to check for and keep track of our public API changes.
`apidiff` might report `git tree is dirty` in Windows environments. I've reproduced this on CAPI, and its likely either an issue with my environment or an upstream issue in [joelanford/go-apidiff](https://github.com/joelanford/go-apidiff). I've verified that this PR works in clean UNIX environments and will investigate the issue independent of this PR.
Fixes #1445

chore: Add apidiff target to Makefile

---

hack/ci-apidiff.sh

This PR adds a script that runs our new `apidiff` make target. We'll need this
script to run apidiff as a prowjob.
Fixes #1445
#1525 added the make target. I'm opening a PR in `kubernetes/test-infra` to add apidiff as one of our optional PR jobs.

🌱 Add script to run go-apidiff in a CI context

---

controllers/serviceaccount_controller.go
controllers/serviceaccount_controller_intg_test.go
controllers/serviceaccount_controller_suite_test.go
controllers/serviceaccount_controller_unit_test.go
controllers/servicediscovery_controller.go
controllers/svcdiscovery_controller_intg_test.go
controllers/svcdiscovery_controller_unit_test.go
pkg/builder/flags.go
pkg/builder/intg_test_context.go
pkg/builder/test_suite.go
pkg/builder/unit_test_context.go
pkg/context/fake/fake_util.go
pkg/context/fake/fake_vmware_cluster_context.go

- Update the logic to get remote cluster config using the name of the CAPI cluster. This was working previously since there was an assumption that the name of the `Cluster` and `VSphereCluster` object is the same which has changed with the advent of `ClusterClass`.
- Updates the provider service account and service discovery controllers to work with different names of cluster and infra cluster objects.
**Which issue(s) this PR fixes** :
Fixes #1514 
```release-note
Fixes logic to fetch credentials of remote cluster
```

🐛 Fixes logic to fetch credentials of remote cluster

---

controllers/session_test.go
pkg/session/session.go

feature enablekeepalive
currently session.Tagmanger is initialized separately from vim.Client and there is not keep-alive added to it.
this PR adds keep-alive support to session.Tagmanager rest.Client 
Fixes #1362 
```release-note
```

🌱 Adds keep alive support for the session tag manager client

---

controllers/vspherecluster_reconciler_test.go
controllers/vspheredeploymentzone_controller_domain_test.go
controllers/vspheredeploymentzone_controller_test.go
controllers/vspherevm_controller_test.go
pkg/services/govmomi/cluster/rule_test.go
pkg/services/govmomi/cluster/service_test.go
pkg/services/govmomi/cluster/vmgroup_test.go
pkg/services/govmomi/create_test.go
pkg/services/govmomi/find/object_test.go
pkg/services/govmomi/metadata/metadata_suite_test.go
pkg/session/session_test.go
test/helpers/envtest.go
test/helpers/vcsim/builder.go
test/helpers/vcsim/simulator.go

This patch moves the vcsim builder to a different package under `test/helpers` directory to remove cyclic dependency/
Fixes the issue raised in the [PR comment](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1336#issuecomment-1121405785)
```release-note
NONE
```

🌱 Moves vcsim builder code to remove cyclic dependency

---

packaging/flavorgen/flavors/generators.go

This PR bumps the `kube-vip` version to `v0.4.2`. More details about this version [here](https://github.com/kube-vip/kube-vip/releases/tag/v0.4.2)
Fixes #1528 
```release-note
Bump kube-vip to v0.4.2
```

🌱 Bump kube-vip to v0.4.2

---

config/base/kustomization.yaml
config/base/manager_role_aggregation_patch.yaml
config/rbac/aggregate_kcp_label_to_clusterrole_patch.yaml
config/rbac/aggregate_labels.yaml
config/rbac/aggregate_role.yaml
config/rbac/kustomization.yaml
config/rbac/role.yaml
controllers/vmware/vspherecluster_reconciler.go

This patch adds an aggregration rule for the CAPV manager role which can be used to add permissions to the CAPV manager ClusterRole on the fly. External clients such as addons providers for CPI/CSI can use this label to add permissions to the manager dynamically, thereby reducing the need to  hardcode these permissions in CAPV.
It also cleans up the patch files to add the CAPI and KCP aggregation labels to the CAPV manager role.
Fixes #1526 
Fixes #1523 
**Special notes for the reviewer**:
The aggregation rule will help the clients creating ProviderServiceAccount objects to add the permissions specified in the `spec.Rules` field to the CAPV manager ClusterRole. Without these permissions, the CAPV manager fails to …

🌱 Updates CAPV manager cluster role

---

config/supervisor/add-configmap-env-vars.yaml
config/supervisor/kustomization.yaml
test/integration/integration-dev.yaml

This patch adds the required environment variables to the `capv-controller-manager` Deployment used by the ProviderServiceAccount reconciliation loop to lookup the name and namespace of the Configmap to add the ServiceAccount info to.
Fixes #1533 
This PR makes changes to the deployment manifest that gets generated for the supervisor types.
```release-note
Adds CM environment variables to CAPV deployment for Supervisor types
```

🌱 Adds CM environment variables to CAPV manifest

---

pkg/services/interfaces.go
pkg/services/network/constants.go
pkg/services/network/dummy_provider.go
pkg/services/network/netop_provider.go
pkg/services/network/network_test.go
pkg/services/network/nsxt_provider.go

This patch uses the legacy label used by CAPW to identify the default network. This legacy label is used as a fallback in case we cannot find a default network with the newer CAPV label.
Fixes #1493
n/a
```release-note
Re-introduces legacy default network label selector
```

🌱 Re-introduces legacy default network label selector

---

metadata.yaml

Adds entry for release v1.2.0 to metadata file
```release-note
NONE
```

🌱 Adds release 1.2.0 to metadata file

---

Dockerfile
Makefile
docs/development.md
test/e2e/config/vsphere-ci.yaml
test/integration/integration-dev.yaml

This PR uses buildx to create multi-platform images, both for amd64
and arm64. This enables creating bootstrap clusters on Macs with M1
chips, which require pulling arm64 based images.
Fixes #
```release-note
Support running CAPV controller manager on arm64
```

build: Support arm64 images

---

controllers/vspheremachine_controller.go
pkg/context/vmware/machine_context.go
pkg/services/interfaces.go
pkg/services/vimmachine.go
pkg/services/vmoperator/vmopmachine.go
pkg/util/testutil.go

This patch fixes the nil reference for logger in the network provider which was causing the controllers to panic.
Fixes #1543 
Instead of creating the `ClusterContext` while fetching the object, this patch creates a `ClusterContext` which gets returned when the `GetClusterContext()` method gets called.
```release-note
Fixes nil reference for logger in network provider
```

🐛 Fixes nil reference for logger

---

pkg/services/govmomi/create.go
pkg/services/govmomi/create_test.go
pkg/services/govmomi/vcenter/clone.go

Fixes a flake in unit tests for `pkg/services/govmomi` that has been affecting a lot of our PRs in recent months.
Fixes #1391
I imagine there's likely a more concise way of waiting on the VM's creation. Please drop a hint and I'll be happy to work on it.

Fix flake in unit tests for the `services/govmomi` package

---

controllers/vspherecluster_reconciler.go
controllers/vspherecluster_reconciler_test.go

This PR adds the logic to remove the FailureDomainsAvailable condition from the `VSphereCluster` object if the failure domain CRs are deleted.
Fixes #1542 
n/a
```release-note
Removes failure domain available condition from Cluster
```

🌱 Removes failure domain condition from Cluster

---

pkg/services/vmoperator/control_plane_endpoint.go

Adds the correct role name to the legacy label `capw.vmware.com`
Fixes #1559
n/a
```release-note
Fixes role name for worker nodes
```

🐛 Fixes role name for worker nodes

---

apis/v1alpha3/conversion_test.go
apis/v1alpha3/zz_generated.conversion.go
apis/v1alpha4/zz_generated.conversion.go
apis/v1beta1/types.go
apis/v1beta1/vspherevm_webhook.go
apis/v1beta1/vspherevm_webhook_test.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
config/webhook/manifests.yaml
packaging/flavorgen/flavors/generators.go

Windows VM name greater than 15 characters can cause issues when multiple machines join a domain and end up with the same NetBIOS name due the OS shrink of the name and same cluster prefix.
This PR adds a new field to identify the machine OS and mutate the VM name via Mutation Webhook when the OS=Windows. The same approach is being used on CAPZ.
Fixes #1292
This is a reopen of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1052
```release-note
Adding OS field on VirtualMachineCloneSpec and renaming of Windows VMs when …
```

OS field and Windows VM name shrink

---

Makefile
docs/gpu-pci.md

This PR adds documentation for GPU PCI implementation.
Signed-off-by: geetikab@vmware.com <geetikab@vmware.com>
Fixes #
```release-note
```

Documentation for GPU with PCI

---

pkg/services/vmoperator/resource_policy.go
pkg/services/vmoperator/resource_policy_test.go

This PR updates the resource policy creation logic to use the name of the Cluster object, instead of the `VSphereCluster` object which is not deterministic in case of topology controller. Hence, using the Cluster object name makes it deterministic for the purpose of UX.
Fixes #
n/a
```release-note
Uses cluster name for resource policy creation
```

🌱 Uses cluster name for resource policy creation

---

pkg/services/vmoperator/vmopmachine.go
test/integration/integration_suite_test.go

This patch updates CAPV to use the VM Operator CloudInit bootstrap method instead of ExtraConfig. This change ensures there is no race between VM Tools and CloudInit since using ExtraConfig will cause Guest OS Customization
to configure the network, resulting in a reboot while CloudInit is running. Specifying CloudInit as the bootstrap provider ensures VM Operator uses CloudInit to bootstrap the network.
Please note this patch will only work in vSphere 7P05+.
NA
This is required for uTKG.
_Please confirm that if this PR changes any image versions, then that's …

Use CloudInit bootstrap w VM Operator

---

.gitignore
controllers/serviceaccount_controller.go
controllers/servicediscovery_controller.go
pkg/services/network/nsxt_provider.go
pkg/services/vimmachine.go
pkg/services/vmoperator/control_plane_endpoint.go
pkg/services/vmoperator/resource_policy.go
pkg/services/vmoperator/vmopmachine.go

This patch updates instances of CreateOrUpdate to CreateOrPatch in order to avoid being destructive during mutation of existing resources. This patch also updates a few instances of the `MutateFn` to ensure labels/annotations/ownerrefs are updated instead of replaced when appropriate.
This patch also updates the project's `.gitignore` file to ignore the manager binary that gets created at the root of the project if `go build` is used to build the manager.
None
_Please confirm that if this PR changes any image versions, then that's the sole change this PR …

Switch to CreateOrPatch; ignore manager binary at root of project

---

pkg/services/vmoperator/constants.go
pkg/services/vmoperator/vmopmachine.go
pkg/services/vmoperator/vmopmachine_test.go
pkg/util/testutil.go
pkg/util/vmware/util.go
test/integration/cluster_lifecycle_test.go
test/integration/sanity_test.go

This patch removes the logic for creating a new ConfigMap resource for Supervisor VMs. Instead CAPV simply points the Supervisor resources to the existing CAPI bootstrap secrets.
Previously Supervisor integration required setting the ControlPlaneEndpoint value in Cloud-Init metadata.
However, this was recognized as vestigial as the KubeadmBootstrap controller automatically grabs the
ControlPlaneEndpoint from the Cluster.Spec.ControlPlaneEndpoint field if the value is not explicitly specified.
For more information please see the following links:
1. The CAPV Cluster reconciler does not proceed until there is a control plane endpoint https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/cc735927f7c7671dc8f30bc796474fa62555a127/controllers …

Reuse CAPI bootstrap secret with Supervisor

---

pkg/services/vmoperator/vmopmachine.go

The Supervisor integration broke with the CreateOrPatch PR when the PVC OwnerRefs were set to VSphereCluster and not the VSphereMachine.
None
cc @sidharthsurana 
```release-note
* Fixes owner of PVCs attached to VsphereMachines to be the VsphereMachine and not the VsphereCluster
```

Fix PVC OwnerRef bug for Supervisor

---

pkg/services/vmoperator/vmopmachine.go

The CSI zone annotation must be set when using a zonal storage class,
which is required when the cluster has multiple (3) zones.
Single zone clusters (legacy/default) do not support zonal storage and must not
have the zone annotation set.
Follow up to #1573

Only set PVC zone annotation when zonal storage classes are required

---

controllers/vspherevm_controller.go
hack/e2e.sh

Reaped nodes (which are **Not Ready**) by MHC show up in the output of kubectl get nodes. The name of the k8s node is same to the name of the owning CAPI Machine. This PR is a workaround which explicitly attempts to delete the node after the `VSphereVM` deletion. This PR builds on top of #1521 
Fixes #1519 
```release-note
Best effort deletion of k8s node when deleting VM
```

🐛 Delete node explicitly upon deletion of vm

---

test/e2e/capi_upgrade_test.go
test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml

- Update the k8s version used by the templates v1.23.5
- Update the thumbprint of the vCenter
- Marks the upgrade test as pending since v1alpha4 and v1alpha3 API versions are EOL now.
n/a
n/a
```release-note
NONE
```

Updates CI config for E2E tests

---

test/e2e/README.md

This PR fixes a few issues with markdown tables in `test/e2e/README.md`.

Fix markdown tables in test/e2e/README.md

---

.github/workflows/golangci-lint.yaml

Adds golang linter Github Action 
n/a
This will make upgrading golang versions easier since currently we have to make a separate PR to `test-infra` repo to update the golang version used in the base images.
```release-note
NONE
```

✨ Adds golang linter GH action

---

test/e2e/data/cni/calico/calico.yaml

**What this PR does / why we need it**: This PR updates the Calico manifest used by the e2e tests to `v3.24.0`. It also fixes #1605.
Fixes #1605
This is a large diff. To ensure it is up to date with upstream, run the following:
```
curl https://raw.githubusercontent.com/johananl/cluster-api-provider-vsphere/johananl/e2e-update-calico/test/e2e/data/cni/calico/calico.yaml > pr.yaml
curl https://raw.githubusercontent.com/projectcalico/calico/v3.24.0/manifests/calico.yaml > upstream.yaml
diff upstream.yaml pr.yaml && echo "OK"
```
To test this PR, follow the reproduction instructions of #1605 and …

🌱 Update Calico in e2e tests to v3.24.0

---

config/manager/manager.yaml
main.go

Changes the names of the flags to align with the k8s components
Below are the flags that have been altered:
```
--metrics-addr ==> --metrics-bind-addr
--enable-leader-election ==> --leader-elect
```
Fixes #1438 
n/a
```release-note
Align flag names with upstream Kubernetes & CAPI components
```

⚠️ Align flag names with upstream Kubernetes & CAPI components

---

config/rbac/role.yaml
controllers/vspherevm_controller.go

Currently, the core group members such as controller manager does not have enough access to perform operations such as query and delete. The kubebuilder directive added would give the permissions to do so.
Signed-off-by: geetikab@vmware.com <geetikab@vmware.com>
fixes: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1620
Fixes #
```release-note
```

Adds RBAC permissions for nodes in core group

---

controllers/vspheremachine_controller.go
pkg/services/vimmachine.go

This fixes a panic that was caused because of a race condition between the VSphere machine controller creating the VM which was causing another reconcile event being requeued for the same object. The other reconcile event was sometimes failing to find the created VSphereVM from the earlier request and trying to create the same object and failing with an already exists error.
Now, the VSphereMachine controller omits the create events for the VSphereVM objects since the controller is the author of those objects and should not be notified for the same event.
Fixes #1372
**Special notes for your …

🐛 Fixes panic when reconciling VSphereMachine objects

---

apis/v1beta1/condition_consts.go
controllers/vspherevm_controller.go
controllers/vspherevm_controller_test.go
pkg/context/fake/fake_vm_context.go
pkg/services/fake/vmservice.go

Adds a new reason on the VSphereVM object's condition to convey that the Machine is waiting on the IP address. This is set if the VSphereVM has no IP addresses reported in its state.
Fixes #1490
```release-note
Exposes reason to convey VSphereVM waiting for IP address
```

🌱 Exposes a new reason for VMProvisionedCondition

---

.github/workflows/golangci-lint.yaml

Since the golang versions for the release-1.3 and the main branches are different, setting up a workflow with inputs specific to the branch.
n/a
Supersedes  #1625
```release-note
```

Adds linting workflow for 1.3 branch

---

controllers/vspheremachine_controller.go
pkg/services/vimmachine.go

Cherry pick of #1622 on release-1.3.
#1622: Fixes panic when creating VSphereVM
```release-note
```

Automated cherry pick of #1622: Fixes panic when creating VSphereVM

---

docs/proposal/node-affinity-and-anti-affinity.md

Proposal for node affinity and anti-affinity
Fixes #
```release-note
```
/hold

📖 Proposal for node anti affinity

---

apis/v1alpha3/conversion_test.go
apis/v1alpha3/vspherevm_conversion.go
apis/v1alpha3/zz_generated.conversion.go
apis/v1alpha4/vspherevm_conversion.go
apis/v1alpha4/zz_generated.conversion.go
apis/v1beta1/vspherevm_types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
config/manager/manager.yaml
config/rbac/role.yaml
controllers/node_controller.go
controllers/vspheremachine_controller.go
feature/feature.go
main.go
pkg/constants/constants.go
pkg/services/govmomi/service.go
pkg/services/interfaces.go
pkg/services/vimmachine.go
pkg/services/vimmachine_test.go
pkg/services/vmoperator/vmopmachine.go
test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/e2e/node_labeling_test.go

This patch adds the following:
- Exposing ESXi host information onto the VSphereVM object
- Exposing ESXi host information as a label onto the Machine object `node.cluster.x-k8s.io/esxi-host: <host-address>`
- Copying the labels prefixed with `node.cluster.x-k8s.io` from the Machine to the Node objects (this will eventually be deprecated in favor of CAPI v1.3.0 release)
This functionality is exposed under a feature flag which is turned off by default.
Fixes #1633
n/a
```release-note
Adds logic to label nodes with special prefixes
```

✨ Adds logic to label nodes with special prefixes

---

controllers/clustermodule_reconciler.go
controllers/clustermodule_reconciler_test.go
pkg/clustermodule/error.go
pkg/clustermodule/service.go

This patch adds the logic to fall back to the default resource pool, if no resource pool is specified, during cluster module creation. It also checks whether the resource pool is owned by a compute cluster or a standalone host. In case of the owner being a standalone host, a warning is introduced on the VSphereCluster object and the cluster creation proceeds.
Fixes #1640
```release-note
Adds default resource pool logic for cluster module creation
```

🐛  Adds default resource pool logic for cluster module creation

---

controllers/clustermodule_reconciler.go
controllers/clustermodule_reconciler_test.go
pkg/clustermodule/error.go
pkg/clustermodule/service.go

Cherry pick of #1641 on release-1.4.
#1641: Adds default resource pool logic
```release-note
```

🐛 Automated cherry pick of #1641: Adds default resource pool logic

---

apis/v1beta1/vspherevm_webhook.go
apis/v1beta1/vspherevm_webhook_test.go

Cherry pick of #1644 on release-1.4.
#1644: Allow mutation of OS field and only when it's empty

Automated cherry pick of #1644: Allow mutation of OS field and only when it's empty

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/verify-pr.yml
CONTRIBUTING.md

This patch fixes the permissions for the PR Verify workflow. It also updates the pull request template to include the instructions to add an icon to the PR title.
Fixes  _the failing the PR Verify workflow_
n/a
```release-note
NONE
```

🌱 Adds write permission for PR Verify workflow

---

apis/v1beta1/vspherevm_webhook.go
apis/v1beta1/vspherevm_webhook_test.go

**What this PR does / why we need it**: This PR allows defaulting/mutation of the OS field, this is needed to fix errors when upgrading the controller
**Which issue(s) this PR fixes** : Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1643
```release-note
```

🐛 Allow mutation of OS field and only when it's empty

---

main.go

Introduces a new flag to set the TLS version to the webhook server.
Fixes #1639
Added defaulting to TLS 1.2 as a separate commit to facilitate backport
```release-note
Flag to configure the min TLS version of the webhook server
```

✨Set minimum TLS version for webhook server

---

hack/release.sh

Fixes the bash file used in the post-deploy job in upstream prow.
Fixes #
n/a
```release-note
NONE
```
/area ci

🐛 Fixes docker build command for post deploy job

---

controllers/serviceaccount_controller.go
controllers/serviceaccount_controller_suite_test.go
controllers/serviceaccount_controller_unit_test.go

This patch changes the default behavior of waiting for the generation of a default secret for the service account and propagate that over to the guest cluster.
Instead, alongwith the service account a secret of type "kubernetes.io/service-account-token" is created to host the token for the service account. The controller waits for the realization of this secret and then propagates this data over to the guest cluster.
This is required since 1.24 disables the auto generation of a default token secret for every service account created.
Fixes #1651 
```release-note
Creates an …
```

✨ Creates an explicit token secret for service account

---

main.go

Cherry pick of #1648 on release-1.3.
#1648: Introduces new flag for setting min TLS version
```release-note
```

⚠️ Automated cherry pick of #1648: Introduces new flag for setting min TLS version

---

controllers/serviceaccount_controller.go
controllers/serviceaccount_controller_suite_test.go
controllers/serviceaccount_controller_unit_test.go

Cherry pick of #1653 on release-1.3.
#1653: Creates token secret for service account
```release-note
```

Automated cherry pick of #1653: Creates token secret for service account

---

apis/v1alpha3/vspherecluster_types.go
apis/v1alpha3/vspheremachine_types.go
apis/v1alpha4/vspherecluster_types.go
apis/v1alpha4/vspheremachine_types.go
apis/v1beta1/vspherecluster_types.go
apis/v1beta1/vspheremachine_types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml

Currently, the printercolumn of vspherecluster and vspheremachine doesn't contain `age` as colume
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1661
```release-note
The printer column of vspherecluster and vspheremachine now display the `age` of the object
```

:seedling: Add 'age' to printercolumn of vspherecluster and vspheremachine

---

controllers/clustermodule_reconciler.go
controllers/clustermodule_reconciler_test.go
pkg/clustermodule/service.go
pkg/clustermodule/service_test.go
pkg/clustermodule/session.go
pkg/context/fake/constants.go
pkg/context/fake/fake_cluster_context.go

This patch adds a check for the following when creating cluster modules:
1. If the infra machine template kind used by MD/KCP object points to a different template kind (not VSphereMachineTemplate)
2. If the machine clone spec in the VSphereMachineTemplate points to a different vCenter URL than the VSphereCluster object. Basically, the case where some worker nodes for a cluster are deployed on a different vCenter instance.
Fixes #1647 and  1669
```release-note
🌱 Skip creation of cluster modules in certain cases
```

🌱 Skip creation of cluster modules in certain cases

---

controllers/clustermodule_reconciler.go
controllers/clustermodule_reconciler_test.go
pkg/clustermodule/service.go
pkg/clustermodule/service_test.go
pkg/clustermodule/session.go
pkg/context/fake/constants.go
pkg/context/fake/fake_cluster_context.go

Cherry pick of #1670 on release-1.3.
#1670: Skip creation of cluster modules
```release-note
```

🌱 Automated cherry pick of #1670: Skip creation of cluster modules

---

pkg/services/govmomi/service.go

This patch increases the verbosity level for some log statements which are assoicated to optional fields, thus reducing the amount of log data generated on continuous reconciles.
Fixes n/a
Just thins out the log data emitted from the CAPV controller manager logs.
```release-note
Increases verbosity level for some logs
```

🌱 Increases verbosity level for some logs

---

controllers/vspheremachine_controller.go
pkg/util/label.go
pkg/util/label_test.go

This patch sanitizes the labels to be set on the Machine object to be conformant to the label value guidelines set in the k8s official docs. It also adds a validation to check if the sanitized label is conformant using the library functions from the apimachinery.
Fixes #1674
With the anti affinity feature, we also included the logic to propagate ESXi host info to the CAPI Machine object which then gets transferred over to the k8s nodes. Since, the ESXi host information is added as a label, it should follow the label value  conventions set by the k8s docs.
```release-note
Adds ESXi host info label validation and sanitization logic
```

🐛 Adds ESXi host info label validation and sanitization logic

---

controllers/vspheremachine_controller.go
pkg/util/label.go
pkg/util/label_test.go

Cherry pick of #1675 on release-1.4.
#1675: Adds label validation & sanitization logic
```release-note
```

🐛 Automated cherry pick of #1675: Adds label validation & sanitization logic

---

Makefile
docs/gpu-pci.md
templates/cluster-template-external-loadbalancer.yaml
templates/cluster-template-topology.yaml
templates/cluster-template.yaml
templates/clusterclass-template.yaml

**What this PR does / why we need it**: Maintain generated flavors in the repo. This allows generating workload clusters using the `--from` flag of `clusterctl generate` which is useful during development.
This practice is used in other providers such as CAPA and CAPZ. Furthermore, it is **expected** that all providers publish the generated templates in the repo. From the CAPI [docs](https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#provider-repositories):
>Additionally, the provider repository SHOULD contain the following files:
>
>- Workload cluster templates
None
**Special notes for your reviewer**: Are we running …

Maintain flavors in template directory

---

.gitignore
Makefile
test/e2e/anti_affinity_test.go
test/e2e/common.go
test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/e2e/data/infrastructure-vsphere/kustomization/base/kustomization.yaml
test/e2e/data/infrastructure-vsphere/kustomization/commons/remove-storage-policy.yaml
test/e2e/data/infrastructure-vsphere/kustomization/storage-policy/kustomization.yaml
test/e2e/node_labeling_test.go
test/e2e/storage_policy_test.go

This patch removes the usage of storage policy for all e2e tests and instead makes provisions to use it for the storage policy e2e test only.
n/a
n/a
```release-note
Removes storage policy usage from all e2e tests
```
/kind cleanup

🌱 Removes storage policy usage from all e2e tests

---

Makefile
test/e2e/common.go
test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/e2e/data/infrastructure-vsphere/kustomization/hw-upgrade/kustomization.yaml
test/e2e/hardware_upgrade_test.go

This PR adds an E2E test to verify the hardware version upgrade functionality merged in #1673 
Fixes #1685 
n/a
```release-note
Adds E2E test for VMX version upgrade feature
```

🌱 Adds E2E test for VMX version upgrade feature

---

controllers/vspherevm_controller.go
controllers/vspherevm_controller_test.go
pkg/context/fake/fake_controller_manager_context.go
pkg/services/fake/vmservice.go

This patch removes the hard dependency of finding the cluster module information when deleting a VM. If the information is missing, due to broken owner reference links, then we should let the controller proceed with VM deletion.
Fixes #
```release-note
Removes hard dependency on cluster module info for VM deletion
```

🐛 Removes hard dependency on cluster module info for VM deletion

---

controllers/clustermodule_reconciler.go

Signed-off-by: killianmuldoon <kmuldoon@vmware.com>
Fix a nil-pointer crash when InfrastructureRef isn't set on the Cluster.
This is part of the ClusterModule reconciler.

🐛 Check for nil Cluster InfrastructureRef in ClusterModule reconcile

---

controllers/vmware/test/controllers_suite_test.go
controllers/vmware/test/controllers_test.go

It enables the unit test scenario with "DummyLBNetworkProvider" which was formally commented out.
Fixes #1324

:seedling: Re-enable LB network provider unit-tests

---

.github/dependabot.yml

Fixes dependenabot config to exclude CAPI and other `sigs.k8s.io` modules like `kind` and `cluster-api/test` which we handle manually.
n/a
n/a
```release-note
NONE
```

🌱 Fixes dependenabot config to exclude CAPI

---

go.mod
go.sum

when trying to build on main we were seeing an error:
`github.com/vmware-tanzu/vm-operator/api@v0.0.0-20221121185334-8c4d5ac76c83: invalid version: unknown revision 8c4d5ac76c83`
it seems that the revision is not currently in the vm-operator repo so we need to pin to a new version.
Fixes #1733 
```release-note
NONE
```

🐛  update the version of vm-operator

---

README.md

- This patch updates the README with the latest patch versions of the 1.23, 1.24 and 1.25 k8s release lines.
- Dropped support for building centos images, if users want to use them, head over to the image-builder project and follow the documentation.
Fixes #1727
```release-note
NONE
```

📖 Adds new CAPV templates

---

pkg/services/network/netop_provider.go

Fixes logger output for legacy network label
n/a
n/a
```release-note
NONE
```

🌱 Fixes logger output for legacy network label

---

pkg/util/fetch_object.go
pkg/util/fetch_object_test.go

During the VM reconciliation, the controllers track down the parent of the Machine objects using the owner reference hierarchy. The owner reference checks were comparing the Group as well as the API version to determins and fetch the owner.
Currently, the API version used for comparison was selected from the storageVersion of the CAPI objects on the API server. Due to this, any objects created via an earlier CAPI version, say v1alpha3, which sets the owner reference API version to group name + v1alpha3 were not being found since no such object would exist. A similar object with the updated API type is stored in the api server.
This drift happens since CAPI does not update the owner references of the objects when moving to newer API versions. There …

🌱 Drops version check when tracking owners
