.github/dependabot.yml

Updates the dependabot configuration to ignore the cluster-api/test dependency
n/a
n/a
```release-note
NONE
```

🌱 Updates dependabot config to ignore CAPI test dependency

---

main.go
pkg/session/session.go
pkg/session/session_test.go

On controller startup, the reconciliation loops for the VSphereCluster and VSphereVM objects make a call to the seesion.GetOrCreate function to look for existing sessions. Without the mutex guarding the access to the function, all the objects end up creating a session, and the last created session which gets saved in the cache gets used for future API calls and the other sessions are left to idle.
Also, altered the logout logic to destroy the session using the govmomi method calls directly.
Another improvement made here was to destroy the sessions on manager shutdown so that CAPV does not leave over any sessions on manager exit.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close …

🐛 Fix vCenter session leaks

---

apis/v1beta1/vspherevm_webhook.go
apis/v1beta1/vspherevm_webhook_test.go
pkg/context/fake/fake_machine_context.go
pkg/services/vimmachine.go
pkg/services/vimmachine_test.go

Renaming the vsphereVM object in the Webhook will cause wrong patching in the controller later, fixing the bug and renaming it directly in the controller on creation time.
Fixes #
```release-note
Fixes Windows vspherevm rename when VSphereMachine OS is Windows.
```

:bug: Renaming the Windows VM name on creation

---

pkg/services/govmomi/service.go
pkg/services/govmomi/service_test.go

IPAddressClaims must be fulfilled before a VM can be powered on. This
could take some time depending on the IPAM Provider. By creating these
claims first we can give the provider time to fulfill these while the VM
is cloning, reducing the overall wait time for a VM to be ready.
Fixes #1690 
We rebased on the e2e tests PR #1667 to validate this work, but dropped that commit before opening this PR
```release-note
NONE
```

✨ reconcile IPAddressClaims earlier

---

apis/v1beta1/condition_consts.go
go.mod
go.sum
pkg/services/govmomi/pci/device.go
pkg/services/govmomi/pci/device_test.go
pkg/services/govmomi/service.go
pkg/services/govmomi/service_test.go
pkg/services/govmomi/vcenter/clone.go
pkg/services/govmomi/vcenter/clone_test.go

This patch reorders the process of attaching PCI devices to the VM. Previously, the PCI devices were attached during the VM cloning operation, but the PCI device attachment requires a minimum hardware version of vmx-17.
Instead of forcing the template to be hardcoded with a minimum hardware version, CAPV introduced the capability of upgrading the hardware version of the VM post clone operation succeeds. This would mean that the PCI devices need to be attached after the upgrade hardware VM task is finished and the hardware version of the VM has been successfully upgraded to some compatible version specified by the user.
Fixes #1749
The govmomi dependency has been updated to …

🐛 Reorder PCI device attachment operation

---

test/integration/integration-dev.yaml

Move over from `k8s.gcr.io` to `registry.k8s.io` registry links for the integration tests job
Fixes n/a
```release-note
NONE
```

🌱 Updates image links for integration test job

---

apis/v1beta1/condition_consts.go
go.mod
go.sum
pkg/services/govmomi/pci/device.go
pkg/services/govmomi/pci/device_test.go
pkg/services/govmomi/service.go
pkg/services/govmomi/service_test.go
pkg/services/govmomi/vcenter/clone.go
pkg/services/govmomi/vcenter/clone_test.go

Manual cherry picking the PR #1775 to the `release-1.5` branch since manual intervention was required due to [merge conflicts](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1775#issuecomment-1428539678).
Fixes #1749 
n/a
```release-note
Reorder PCI device attachment operation
```

🐛 [release-1.5] Cherry pick Reorder PCI device attachment operation

---

pkg/services/cloudprovider/cloud-controller-manager.go
pkg/services/cloudprovider/csi.go
templates/cluster-template-external-loadbalancer.yaml
templates/cluster-template-ignition.yaml
templates/cluster-template-topology.yaml
templates/cluster-template.yaml

In k8s v1.25, the control-plane node role label is not "master" anymore, but "control-plane".
This turns into vsphere-cloud-provider to never be able to progress, because vsphere-cloud-controller can never run on nodes with only control-planes and never set the proper nodeID.
Related to https://github.com/kubernetes-sigs/cluster-api/issues/3279
```release-note
Add the right tolerations for Kubernetes v1.25+
```

:bug: Fix toleration config on templates

---

pkg/services/govmomi/service.go

Propagate error on vm clone failure to be reflected on capv controller log.
Fixes #1797
```release-note
```

:bug: log error on vm clone failure

---

pkg/session/session.go

Set user agent for vimclient of capv "k8s-capv-useragent" to help troubleshooting.
Fixes #1805
```release-note
```

:sparkles: set user agent for vimclient

---

pkg/services/govmomi/vcenter/clone.go
pkg/services/govmomi/vcenter/clone_test.go

The primary disk size is [optional](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/48a9daca388238ea942c407b0752c4eeaeb09204/apis/v1beta1/types.go#L151), according to the API.
Prior to this commit, if the user did not set an explicit primary disk size, VM creation would fail with a validation error.
This PR sets the primary disk size to the base template primary disk size when the user does not set an explicit primary disk size.
Fixes # …

:bug: Calculate default primary disk size from base template

---

Makefile

Ginkgo 2.0 removed the support of custom reporters when running the test suite, and instead provided it as a command line argument on the command itself. This patch makes sure that the report of the test suite gets created in the artifacts folder.
n/a
Before Gingko 2.0 test grid reported the test runs as following
After the upgrade, the test grid report shows as below:
```release-note
NONE
```

🌱 Adds junit reporter to the ginkgo command

---

pkg/services/govmomi/service.go
pkg/services/govmomi/service_test.go

while there are unbound ip address claims the condition will show the count of bound to total claims, giving some feedback on how much work is left
Fixes #1689 
```release-note
when using AddressesFromPools the vSphereMachine status will reflect how many claims are awaiting addresses
```

✨ ipam display count of address claims bound in condition

---

go.mod
pkg/services/govmomi/pci/device.go

This patch fixes the import statement to use the correct `context` package from the standard go library.
Fixes #1836 
n/a
```release-note
Removes unnecessary import golang.org/x/net
```

🌱 Removes unnecessary import golang.org/x/net

---

packaging/flavorgen/flavors/generators.go
templates/cluster-template-ignition.yaml
templates/cluster-template-topology.yaml
templates/cluster-template.yaml

Updates the kube-vip version in templates to v0.5.11
Fixes #1834 
Changes to the generated templates that will be shipped with the next release
```release-note
Updates kube-vip to v0.5.11
```

✨ Updates kube-vip to v0.5.11

---

.github/dependabot.yml

Since the dependencies under the hack/tools directory are managed by go.mod, we should instruct dependabot to also look for updates to those dependencies as well. Raised as a follow up to #1843 
n/a
n/a
```release-note
NONE
```

🌱 Updates dependabot config to scan hack/tools directory

---

test/e2e/config/vsphere-dev.yaml
test/e2e/multivc_test.go

This test case is to validate multiple vCenter support of CAPV, which means it will distribute management cluster in vCenter 1 and workload cluster in vCenter 2. So far it can only be run from downstream as it needs 2 vCenter to be pre-provisioned and I've verified the test case. And now this PR is ready for code review. Once the code review is complete, then anyone can leverage it to test multivc support downstream. Additionally, once the test infrastructure supports two vCenters, this test case can also be run upstream.
The original PR is https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1736, I've talked with @adam-jian-zhang  to use this PR to move forward.
```release-note
Add a e2e test case that validates …
```

🌱 Add a e2e test case that validates the multiple vCenter support of CAPV

---

hack/tools/go.mod
hack/tools/go.sum
hack/tools/tools.go

The auto bump of the govmomi dependency in `hack/tools` keeps failing due to unnecessary imports in the `go.mod` file. Cleaning this up should free up automation errors in the future.
Ref: #1875 
n/a
```release-note
[hack/tools] Fixes govmomi dependency imports
```

🌱 [hack/tools] Fixes govmomi dependency imports

---

test/e2e/mhc_remediation_test.go

The thought is to skip this test since this test requires a sepcialized setup and using the CAPI defaults which work for CAPD might not be suitable for CAPV since provisioning takes slightly longer in vSphere.
This test will need to be reworked to create a HA control plane and then mark a node for remediation. A new issue is opened to track this work in #1871 
n/a
```release-note
NONE
```
/area testing

🌱 E2E: Marking KCP remediation test as Pending

---

controllers/vspherecluster_controller.go

This patch moves the watches on the `KubeadmControlPlane` object under the node anti affinity feature flag. These watches will now be set only when using the NodeAntiAffinity feature flag which implicitly depends upon the Kubeadm control plane provider. 
Fixes #1863 
```release-note
Moves KCP watch population under feature flag
```

🐛 Moves KCP watch population under feature flag

---

controllers/node_controller.go

During B/R operations, the cluster owner ref is somethimes not present immediately. This might throw an error which when unhandled causes the controller to crash.
This patch handles the error case and requeues the reconcile request for a later time.
The main motivation behind fixing this is to make sure a backport can be made to the `release-1.6` and `release-1.5` branches, the last active branches which will have support for CAPV based node labeling.
Fixes #1884 
```release-note
```

🐛 Handles cluster owner ref error for node controller

---

controllers/vspherevm_ipaddress_reconciler.go
controllers/vspherevm_ipaddress_reconciler_test.go

This PR ensures that IPAddressClaims get an annotation with a reference to the cluster they belong to. This will allow pausing of claim reconciliation when the cluster is paused, such as during a move from the bootstrap clusters to the management clusters.
This is related to https://github.com/telekom/cluster-api-ipam-provider-in-cluster/pull/105, which will use this annotation to check the cluster paused state when reconciling claims.
Fixes #
**Release …

:sparkles: ensure IPAddressClaims are created with a cluster annotation

---

controllers/vspherevm_ipaddress_reconciler.go
controllers/vspherevm_ipaddress_reconciler_test.go

Fixes error made in #1857 where we were previously setting the annotation on an IPAddressClaim based on a non-existent annotation on the VSphereVM.
This change uses labels which we have manually verified to be set correctly on a running kind cluster.
```release-note
```

🌱 Set the ClusterName label on IP claims instead of setting the annotation

---

config/rbac/role.yaml
controllers/vspherevm_ipaddress_reconciler.go

change update -> patch
During manual testing of IPAM features, a panic was encountered. The testing involved setting a label on a previously created IPAddressClaim. The controller failed to patch the claim, causing the claim to be nil. The claim became nil because the rbac permissions did not include patch. A previous incantation of the controller used udpate, and when the code was switched to patch, the rbac permissions has been left unchanged. This PR updates the controller's permissions to include patch.
Fixes #
_Please confirm that if this PR changes any …

🐛 Update IPAddressClaim rbac for patch

---

config/manager/manager.yaml
controllers/vspherecluster_reconciler.go
controllers/vspheredeploymentzone_controller.go
controllers/vspherevm_controller.go
main.go
pkg/clustermodule/session.go
pkg/constants/constants.go
pkg/session/session.go

Thie patch re-introduces the keep alive flag on the CAPV manager. The flag is by enabled default so there are no breaking changes after upgrades.
Fixes #1896 
This leads to the `--enable-keep-alive` flag being exposed on the CAPV manifest.
```release-note
Re-introduce the keep alive flag on the CAPV manager
```

⚠️ Re-introduce the keep alive flag on the CAPV manager

---

apis/v1beta1/types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
pkg/services/govmomi/ipam/parse.go
pkg/services/govmomi/ipam/status.go
pkg/services/govmomi/ipam/status_test.go

This PR allows ipv6 gateway to be optional. In the case of using IPAM for nodes the IPAddress can have an ipv6 address without a gateway and it will configure the machine's metadata appropriately. The comment on gateway6 says it is required when DHCPv6 is disabled. This comment was removed, but there was no logic enforcing it except in the case of Node IPAM were it would always try to parse the gateway from the `IPAddress` resource.
Fixes #1861
```release-note
Allow IPv6 Gateways to be optional when DHCPv6 is disabled.
```

:bug: Allow ipv6 gateway to be optional when DHCPv6 is disabled.

---

Makefile
apis/v1alpha3/conversion_test.go
apis/v1alpha3/zz_generated.conversion.go
apis/v1alpha4/zz_generated.conversion.go
apis/v1beta1/vspherecluster_types.go
apis/v1beta1/zz_generated.deepcopy.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
controllers/vspherecluster_reconciler.go
controllers/vspherecluster_reconciler_test.go

This patch introduces a new parameter for selecting zones for control plane nodes.
In the past, all zones having the same vCenter URL in the spec.server would be associated to a vSphereCluster object with the same vCenter URL set in the spec.server.
Now the vSphereCluster spec exposes a label based selection which can be used to choose the zones for control plane node placement. The label selector follows the same rules as described on the label selector types in https://pkg.go.dev/k8s.io/apimachinery@v0.26.1/pkg/apis/meta/v1#LabelSelector
Fixes #
n/a
```release-note
Introduces parameter for control plane zone selection
```

✨ Introduces parameter for control plane zone selection

---

config/rbac/role.yaml
controllers/vspherevm_ipaddress_reconciler.go

This PR adds back update to the ipaddressclaim rbac. Looks like https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1893 assumed we were not using update and only using patch. Turns out update is still used during delete: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/controllers/vspherevm_ipaddress_reconciler.go#L222.
Fixes #
```release-note
Add update to ipaddressclaim rbac
```

:bug: Add update to ipaddressclaim rbac

---

hack/ensure-kubectl.sh

*What this PR does / why we need it**:
The `storage.googleapis.com/kubernetes-release` URL is a hard coded path to a GCS bucket location. To allow redirecting and spreading the load across multiple hosting locations, the `dl.k8s.io` URL has been introduced.
Related PRs:
- https://github.com/kubernetes-sigs/image-builder/pull/656
- https://github.com/kubernetes-sigs/cluster-api/pull/4958
None
```release-note
NONE
```

🌱 Use dl.k8s.io instead of hardcoded GCS URIs

---

apis/v1beta1/vspherevm_webhook.go
apis/v1beta1/vspherevm_webhook_test.go

Updating thumbprint of VSphereCluster will cause reconcilererror for VSphereVM, to fix it
- Relax the VSphereVM webhook to allow the thumbprint update.
- Keep VSphereVM thumbprint consistent with VSphereCluster
Fixes #1718
```release-note
Allow thumbprint update on VSphereVM
```

🐛 Allow thumbprint update on VSphereVM

---

apis/v1alpha3/conversion_test.go
apis/v1alpha3/types.go
apis/v1alpha3/zz_generated.conversion.go
apis/v1alpha4/types.go
apis/v1alpha4/zz_generated.conversion.go
apis/v1beta1/types.go
apis/v1beta1/vspherevm_types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
controllers/vspherevm_controller.go
controllers/vspherevm_controller_test.go
pkg/services/govmomi/service.go

Adds a new status field to vspherevms resources, representing the fetched moid/vmref from reconciliation process.
This information is desired on situations where you create a cluster, and later may want to query on vCenter directly information about the nodes (for observability reasons, metrics collection, datastore usage, etc).
vmRef/Moid is an immutable information, so as soon as a virtual machine is created it is allocated and will persist during VM lifecycle, while biosUUID can change on specific situations (see https://kb.vmware.com/s/article/2002506).
Having biosUUID should be enough to query a virtual machine VMRef, but this needs a bunch of machinery (https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/5a027e203ceae96c9721a69 …

✨ Add VMRef moID to Object status

---

controllers/serviceaccount_controller.go
controllers/serviceaccount_controller_intg_test.go
pkg/util/supervisor.go
pkg/util/supervisor_test.go
test/helpers/vmware/intg_test_context.go

Fixes #1927
As part of this, had to implement pause support for the integration tests.
```release-note
CAPV forces setting controller ownership of resources reconciled by the Service Account controller, which may have stale references when upgrading from vSphere 7.
```

🐛 ServiceAccount Controller: Forcefully set controller ownership on resources being reconciled

---

Makefile
hack/tools/Makefile

Today golang-ci lint is called twice on PRs, one via Github Actions and the other on `make test`.
We can remove it from Makefile (as Core ClusterAPI)
Also, the current call is not considering the root of repository to access GH action version, and not considering that there may be other directives (like go-version) so this is fixing the current call for the linter version
```release-note
NONE
```

:seedling: Fix golang-lint call and pinning

---

controllers/vspherevm_controller.go

Right now the CreateFunc and UpdateFunc use different way of checking whether a cluster is paused.
Now change it to annotations.IsPaused as a general way
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1890
```release-note
Use same func to check whether cluster is pasued inside vspherevm_controller handler
```

🐛 Use same check when checking cluster is pasued or not in the handler

---

.github/workflows/scan.yaml

Add the `release-1.7` branch to the trivy scan for CVEs in images.
```release-note
NONE
```

:seedling: Add release-1.7 to Trivy scan

---

apis/v1alpha3/vspherevm_types.go
apis/v1alpha4/vspherevm_types.go

Adds the missing `categories=cluster-api` marker to:
* `apis/v1alpha3/vspherevm_types.go`
* `apis/v1alpha4/vspherevm_types.go`
The missing markers result into inconsistent results for the generated CRD's.
Related to #1928
```release-note
```

🐛 apis: fix missing categories marker for VShpereVM in v1alpha3 and v1alpha4

---

README.md

This section is out of date, so update it in case others may refer to it.
Fixes #1947 
```release-note
Update CAPV compatibility specification
```

📖 Update CAPV compatibility specification

---

test/e2e/anti_affinity_test.go

Adds a check to the currently broken anti-affinity test to ensure enough hosts are available for the given anti-affinity test input.
Fixes #1975
```release-note
```
/test help

🌱 test/e2e: add check at anti-affinity test to ensure enough hosts exist

---

pkg/services/govmomi/vcenter/clone.go

When storage policy is specified, CAPV will fetch compatible datastores and randomly selects one, however the return set also contains datastore cluster. This will leads to long-time retries and even clone failures. Fix it by adding a filter when to get compatible datastores.
Fixes #
#1914
#1853 
```release-note
Fix datastore selection based on StoragePolicy
```

🐛 Fix datastore selection based on StoragePolicy

---

Makefile
hack/go-install.sh
hack/tools/Makefile
hack/tools/go.mod
hack/tools/go.sum
hack/tools/tools.go

release-1.6 had dependency issues building the `govc` binary.
This change adopts the way of building dependant binaries from core CAPI for `govc`. This method does not have a such issue.
For more information see #1983
Fixes #
```release-note
```

🌱 Makefile: refactor how govc is built to workaround dependency issues building govc

---

go.mod
go.sum

This PR bumps docker/distribution to fix the CVE found in: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/5507817195/jobs/10066944200
Fixes #
```release-note
```

[release-1.6] 🌱 Bump docker/distribution to v2.8.2

---

Makefile
hack/go-install.sh
hack/tools/Makefile
hack/tools/go.mod
hack/tools/go.sum
hack/tools/tools.go

Manual cherry-pick of #1986 to release-1.7
Fixes #
```release-note
```

[release-1.7] 🌱 Makefile: refactor how govc is built to workaround dependency issues building govc

---

go.mod
go.sum
test/helpers/envtest.go

Accounts for when GOPATH does not contain source files due to other system or user configurations for the Go compiler.
Fixes #1930
```release-note
NONE
```

🐛 envtest: Dynamically load CRDs using golang resolvers

---

config/default/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_contentlibraryproviders.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_contentsourcebindings.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_contentsources.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclassbindings.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclasses.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineimages.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachines.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineservices.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_webconsolerequests.yaml
config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_providerserviceaccounts.yaml
config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
hack/tools/go.mod
hack/tools/go.sum

Bumps controller-gen to fix the non-deterministic YAML generation.
Thx very much to @ntoofu for fixing the issue in controller-tools (https://github.com/kubernetes-sigs/controller-tools/pull/792)
Fixes #1757
Fixes #1928
```release-note
```

🌱 Bump controller-tools to v0.12.1

---

Makefile
config/default/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_contentlibraryproviders.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_contentsourcebindings.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_contentsources.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclassbindings.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineclasses.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineimages.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachines.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachineservices.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
config/deployments/integration-tests/crds/vmoperator.vmware.com_webconsolerequests.yaml
config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_providerserviceaccounts.yaml
config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/supervisor/crd/vmware.infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
hack/tools/Makefile
hack/tools/go.mod
hack/tools/tools.go

This is a manual cherry-pick of #2005
As follow-up of #2004
Adjusts the targets for `controller-gen` to use `hack/go-install.sh` instead so we are able to cherry-pick the new version to the release branches of 1.5, 1.6 and 1.7. We do this to make `verify-crds` deterministic on this branches again.
Note: this would not be possible on the release branches by just bumping in `hack/tools/go.mod` because other binaries won't compile then anymore.

[release-1.7] 🌱 hack/tools: use go-install.sh for installing controller-gen for 1.7

---

pkg/session/session.go

This PR makes it possible to set `VsphereCluster.Spec.Server` as an unbracketed IPv6 address. This makes `Server` consistent with `VsphereCluster.Spec.ControlPlaneEndpoint`'s handling of IPv6 addresses.
Fixes #1997
```release-note
Support unbracketed IPv6 addresses for `VsphereCluster.Spec.Server`
```

✨ Support bare IPv6 vCenter server addresses

---

go.mod
go.sum

Replaces #2019 .
`github.com/vmware/govmomi` v0.30.6 includes https://github.com/vmware/govmomi/pull/3175 which is required for bumping to go 1.20.
Fixes #
```release-note
```

🌱 bump github.com/vmware/govmomi to v0.30.6

---

test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml

Updates CI template to k8s 1.27.3
To confirm whether CAPV works with `1.27.0`
```release-note
NONE
```

🌱 [CI]: Updates CI template to k8s 1.27.3

---

Dockerfile
Makefile
go.mod
hack/ensure-go.sh
hack/tools/go.mod

Bumps Go to the latest supported 1.20.6 to be on the same version as CAPI and k8s v1.27 / v1.28
Fixes #
```release-note
Bump Go to 1.20.6
```

🌱 Bump Go to 1.20.6

---

pkg/session/session.go

This is an manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1949
```release-note
NONE
```

[release-1.5] 🐛 Don't call session logout for keepAliveHandler

---

pkg/session/session.go

Fixes the used RoundTripper inside the KeepAliveHander function to use the one provided by the function arguments.
Got introduced in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1897
Fixes #
Cherry-picking this to release-1.7, because the change got cherry-picked by accident in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2027.
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/commit/a32439152edaea5a9e4b145c86d6d5c0b4068b47#diff-59fbb0bb5dfeeb4f123f1e9e0a3d12c38a60b839e113b29868cb905755639e13R202-R2 …

🐛 pkg/session fix used RoundTripper inside anonymous func for KeepAliveHandler

---

pkg/services/vimmachine.go

Just want to rename the func to make it clear this works independent of the vCenter version.
The only restriction we have is that it is for the non-supervisor mode but that is clear because the func is a method on VimMachineService
Fixes #
```release-note
```

🌱 Rename findVMPre7 to findVSphereVM

---

docs/proposal/node-affinity-and-anti-affinity.md
feature/feature.go
main.go

The feature gate was already deprecated / disabled with v1.7. This PR now removes the feature gate. The difference for users should only be that we don't emit the log anymore.
Fixes #
```release-note
```

🌱 Remove NodeLabeling feature gate

---

pkg/services/vmoperator/vmopmachine.go
pkg/services/vmoperator/vmopmachine_test.go

Since we bumped to CR v0.15 deleteFunc is always just a regular delete. So let's cleanup accordingly
Fixes #
```release-note
```

🌱 Cleanup deleteFunc in VmopMachineService

---

controllers/vspheremachine_controller.go

In general it is recommended to consistently use the same receiver type. I think in this case (as usually in all reconcilers) we should use a pointer receiver.
Otherwise the machineReconciler struct is getting copied on method calls.
Fixes #
```release-note
```

🌱 Use pointer receiver consistently in vspheremachine controller

---

go.mod
go.sum

Bump docker/docker to version v24.0.5
Release Notes: https://github.com/moby/moby/releases/tag/v24.0.5
This fixes issues similar to https://github.com/kubernetes-sigs/cluster-api/issues/9037 related to using go 1.20.6.
This also should fix our Conformance tests in CI which are currently red, e.g.:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-vsphere-conformance-release-1-7/1683468651639869440
Fixes # …

🌱 Bump docker to v24.0.5

---

.github/workflows/golangci-lint.yaml
.golangci.yml
Makefile
hack/tools/Makefile

Manual cherry-pick of #2028 .
Older golangci-lint versions are way slower (especially the version which is/was used on release-1.5, `v1.47.3`. Resulting in false-positive failures of the linter.
This bumps to the latest version also used on main which does not have this issue.
Part of #2087
```release-note
NONE
```

[release-1.7] 🌱 Bump golangci-lint to v1.53.3

---

go.mod
go.sum

Manual cherry-pick of #2081.
Release Notes: https://github.com/moby/moby/releases/tag/v24.0.5
This fixes issues similar to https://github.com/kubernetes-sigs/cluster-api/issues/9037 related to using go 1.20.6.
This also should fix our Conformance tests in CI which are currently red, e.g.:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-vsphere-conformance-release-1-7/1683468651639869440
Fixes # …

[release-1.5] 🌱 Bump docker to v24.0.5

---

go.mod
go.sum

Manual cherry-pick of #2081.
Release Notes: https://github.com/moby/moby/releases/tag/v24.0.5
This fixes issues similar to https://github.com/kubernetes-sigs/cluster-api/issues/9037 related to using go 1.20.6.
This also should fix our Conformance tests in CI which are currently red, e.g.:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-vsphere-conformance-release-1-7/1683468651639869440
Fixes # …

[release-1.6] 🌱 Bump docker to v24.0.5

---

Makefile

Bumps the version of setup-envtest to the same as the controller-runtime dependency in go.mod.
setup-envtest was even downgraded in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/commit/4f91fcc6166750f8491e1b5d2752e9e55e716f08#diff-f389ca9ba468c8313b9d514e887e4b8899886bb2d6790352386aaf01da3aa588R11 .
Fixes #
```release-note
NONE
```

🌱 [CI] Bump setup-envtest

---

.golangci.yml
apis/v1beta1/vspherefailuredomain_types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml

Fixes #
```release-note
```
Part of #1899

🌱 Deprecate AutoConfigure functionality

---

.github/PULL_REQUEST_TEMPLATE.md

Follow-up to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2103#issuecomment-1655505707
```release-note
```

📖 Remove unused parts from the PR template

---

controllers/vmware/test/controllers_test.go
controllers/vmware/vspherecluster_reconciler.go
controllers/vspherecluster_reconciler.go
controllers/vspheredeploymentzone_controller.go
controllers/vspheremachine_controller.go
controllers/vspherevm_controller.go

- Add finalizer if not existed
- Requeue immediately after adding finalizer to avoid the race condition between init and delete
Please find more details in #2039 description.
Fixes #2039 
```release-note
Refine finalizer handling
```

🐛 Refine finalizer handling

---

Makefile

Did a bit of testing and we need some fixups.
Test release can be seen here: https://github.com/sbueringer/cluster-api-provider-vsphere/releases/tag/v1.8.0
Part of #2051

🌱 Fixups after Makefile refactoring

---

OWNERS
OWNERS_ALIASES

Refresh of OWNERS to reflect current folk as per the meeting of 2023/06/22
Related PRs:
* https://github.com/kubernetes/test-infra/pull/30190
* https://github.com/kubernetes/org/pull/4345
* https://github.com/kubernetes/k8s.io/pull/5621
Fixes #
```release-note
NONE
```

:seedling: OWNERS: Refresh of owners as per meeting of 2023/06/22

---

controllers/controllers_suite_test.go
controllers/serviceaccount_controller.go
controllers/servicediscovery_controller.go
controllers/vmware/test/controllers_test.go
controllers/vspherecluster_controller.go
controllers/vsphereclusteridentity_controller.go
controllers/vspheredeploymentzone_controller.go
controllers/vspheremachine_controller.go
controllers/vspherevm_controller.go
main.go
pkg/context/controller_manager_context.go
pkg/manager/manager.go
pkg/manager/options.go

removes `--max-concurrency` and replaces by concurrency flag per controller:
- adds `--vspherecluster-concurrency`
- adds `--vspheremachine-concurrency`
- adds `--providerserviceaccount-concurrency`
- adds `--servicediscovery-concurrency`
- adds `--vspherevm-concurrency`
- adds `--vsphereclusteridentity-concurrency`
- adds `--vspheredeploymentzone-concurrency`
```diff
16d21
<       --max-concurrent-reconciles int            The maximum number of allowed, concurrent reconciles. (default 10)
22c27,29
>       --providerserviceaccount-concurrency int   Number of provider service accounts to process simultaneously (default 10)
>       --servicediscovery-concurrency int         Number of vSphere clusters for service discovery to process simultaneously …
```

⚠️ Introduce concurrency flags per controller

---

controllers/serviceaccount_controller.go
controllers/servicediscovery_controller.go
controllers/vspherecluster_controller.go
controllers/vsphereclusteridentity_controller.go
controllers/vspheredeploymentzone_controller.go
controllers/vspheremachine_controller.go
controllers/vspherevm_controller.go
main.go
pkg/context/controller_manager_context.go
pkg/manager/manager.go
pkg/manager/options.go

Adds the flag `--watch-filter` and uses the predicate filter `predicates.ResourceNotPausedAndHasFilterLabel` from CAPI on every controller.
```
--watch-filter string                    Label value that the controller watches to reconcile cluster-api objects. Label key is always cluster.x-k8s.io/watch-filter. If unspecified, the controller watches for all cluster-api objects.
```
Fixes #2038 
Requires #2104 to merge first
```release-note …
```

🌱 Introduce watch-filter flag as predicate filter + filter out paused objects

---

Makefile

Just saw that we're using an old version while debugging why kpromo failed on some k8s.io/k8s.io PR
Fixes #

🌱 Bump kpromo to v4.0.4

---

Makefile

* Adjusts makefile target `test-integration` to also produce a junit file
* Adds `test-junit` target which does the same as `test` but uses gosumtest to create a junit file. This is to be used in CI to get an better overview which tests failed.
Part of #2122

🌱 test: generate junit result for test-integration and add test-junit target

---

Makefile
test/integration/integration_suite_test.go

This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2140.
Replaces

[release-1.5] 🌱 test: generate junit result for test-integration and add test-junit

---

packaging/flavorgen/flavors/generators.go
templates/cluster-template-external-loadbalancer.yaml
templates/cluster-template-ignition.yaml
templates/cluster-template-node-ipam.yaml
templates/cluster-template.yaml
templates/clusterclass-template.yaml

Adds `powerOffMode` to the current templates to serve as documentation to control the VM power off behavior.
Fixes #

:seedling: Add powerOffMode to templates

---

apis/v1beta1/condition_consts.go
pkg/services/govmomi/service.go

We used to treate WasNotFoundByUUID as terminal error, and set `failureMessage` and `failureReason`, so VSphereVM won't be reconciled anymore. However, in some situation, this error is recoverable, for instance, if the storage was temporarily disconnected but later recovered, this error will be transient.
Fixes #2102

:warning: Treating VSphereVM wasNotFoundByBIOSUUID as transient error

---

apis/v1beta1/vspherevm_webhook.go
apis/v1beta1/vspherevm_webhook_test.go

This PR improves the validation for VSphereVM objects by adjusting the webhook to:
* only allow changes to `VSphereVM.spec.biosUUID` if it is not already set
* prevent updates which try to change the biosUUID.
Identified during discussions around #2102

⚠️ webhook: prevent changes to an already set VSphereVM.spec.biosUUID

---

go.mod
go.sum

Semi-automated via:
```
function bump() { go mod edit -require golang.org/x/net@v0.13.0 && go mod tidy }
bump; git commit -m "Bump golang.org/x/net to v0.13.0"
```
This bumps golang.org/x/net to v0.13.0 to address vulnerability GO-2023-1988.
We're not affected (according `govulncheck`) but after some time trivy may report the vulnerability so we bump better now and prior to get to that point.
More info: https://pkg.go.dev/vuln/GO-2023-1988
Fixes #

🐛 Bump golang.org/x/net to v0.13.0

---

apis/v1alpha3/types.go
apis/v1alpha4/types.go
apis/v1beta1/types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml

When reading the API specs, it was not obvious to me what the syntax of the field was. This PR updates the description of the ipAddrs field to prevent ambiguity when specifying the IP address.
Resolves a minor issue I found in the [troubleshooting guide](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/troubleshooting.md?rgh-link-date=2023-03-17T18%3A28%3A49Z#a-static-ip-address-must-include-the-segment-length).
This is a manual minor fixup of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1828 - thanks @rvanderp3!

:book: Improve godoc of the ipAddrs field

---

go.mod
go.sum

Bump controller-runtime to v0.15.1
Release notes: [kubernetes-sigs/controller-runtime@v0.15.1 (release)](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.1)

:seedling: Bump controller-runtime to v0.15.1

---

.github/workflows/golangci-lint.yaml

Right now the error doesn't show exact line that has issue.
With this fix, then the error log will be more descriptive.
Example: here https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/5791075333/job/15695267905?pr=2171
```
run golangci-lint
Running [/home/runner/golangci-lint-1.53.3-linux-amd64/golangci-lint run --out-format=line-number,github-actions] in [] ...
Error: pkg/session/session.go:335:67: unnecessary conversion (unconvert)
logger.V(4).Info("Session.LoginByToken with certificate", string(userCert))
^
pkg/session/session.go:347: unnecessary trailing newline (whitespace)
}
Error: unnecessary conversion (unconvert)
Error: unnecessary trailing newline (whitespace)
Error: issues found
Ran golangci-lint in 2717ms
``` …

🌱 Add args to golangci-lint to show lines number

---

.golangci.yml
apis/v1alpha3/doc.go
apis/v1alpha3/haproxyloadbalancer_types.go
apis/v1alpha3/vspherecluster_types.go
apis/v1alpha3/vsphereclusteridentity_types.go
apis/v1alpha3/vspheredeploymentzone_types.go
apis/v1alpha3/vspherefailuredomain_types.go
apis/v1alpha3/vspheremachine_types.go
apis/v1alpha3/vspheremachinetemplate_types.go
apis/v1alpha3/vspherevm_types.go
apis/v1alpha4/doc.go
apis/v1alpha4/vspherecluster_types.go
apis/v1alpha4/vsphereclusteridentity_types.go
apis/v1alpha4/vsphereclustertemplate_types.go
apis/v1alpha4/vspheredeploymentzone_types.go
apis/v1alpha4/vspherefailuredomain_types.go
apis/v1alpha4/vspheremachine_types.go
apis/v1alpha4/vspheremachinetemplate_types.go
apis/v1alpha4/vspherevm_types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
pkg/constants/constants.go

Deprecate v1alpha3 and v1alpha4 apiVersions by:
1) Adding a Go deprecrated marker to each package and each root API type in packages `v1alpha3` and `v1alpha4`
2) Add a kubebuilder marker to set `deprecated: true` on the openAPI definition.
Part of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2165

:seedling: Deprecate v1alpha3 and v1alpha4 apiVersions

---

controllers/controllers_suite_test.go
controllers/serviceaccount_controller.go
controllers/servicediscovery_controller.go
controllers/vspherevm_controller.go
controllers/vspherevm_controller_test.go
main.go

Using ClusterCacheTracker instead of remote.NewClusterClient
Fixes #2053

:seedling: Using ClusterCacheTracker instead of remote.NewClusterClient

---

pkg/session/session.go

Improve session handling with a secure session key to avoid hijack.
Fixes #

✨ Improve session handling with a secure session key

---

pkg/session/session.go

Manually cherry-pick #2154 to resovle conflicts
Fixes #

✨ [release-1.5] Improve session handling with a secure session key

---

Makefile
packaging/flavorgen/cmd/root.go
packaging/flavorgen/flavors/crs/util.go
packaging/flavorgen/flavors/util/helpers.go

🌱  flavorgen generates all flavors by default

---

config/manager/manager.yaml
controllers/vspherecluster_reconciler.go
controllers/vspheredeploymentzone_controller.go
controllers/vspherevm_controller.go
main.go
pkg/clustermodule/session.go
pkg/constants/constants.go
pkg/session/session.go

Manual cherry-pick to resolve conflicts
Fixes #2193

[release-1.6] ✨ Re-introduce the keep alive flag

---

.github/dependabot.yml
.github/workflows/pr-golangci-lint.yaml
.github/workflows/pr-md-link-check.yaml
.github/workflows/pr-verify.yaml
.github/workflows/weekly-image-scan.yaml
.github/workflows/weekly-md-link-check.yaml
.github/workflows/weekly-test-release.yaml
.markdownlinkcheck.json
Makefile
docs/release/release-tasks.md

Aligns the github actions used in this repo with those used in upstream Cluster API c/f https://github.com/kubernetes-sigs/cluster-api/tree/main/.github/workflows
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2059

:seedling: Align github actions with upstream CAPI

---

controllers/clustermodule_reconciler.go
controllers/clustermodule_reconciler_test.go

Ensures to preserve existing cluster modules if `DoesExist` returns an error. Instead bubble up the error in the `ClusterModulesAvailableCondition`.
Also adds unit tests for the cases when:
* Error returned from `DoesExist` (above case)
* Cluster modules do not exist anymore (`DoesExists` returns `false, nil`) and need to be recreated.
Fixes #2184

🐛  clustermodules: prevent creation of new modules if DoesExist returns an error

---

README.md
docs/release/release-tasks.md

🌱  Update compatibility in README.md

---

Makefile
hack/e2e.sh
hack/ipclaim-template.yaml

Adds the prowjob name and id as annotation to ipclaims to help identifying where leaks of IPs come from.
Fixes #

🌱 CI: add annotation with prowjob name and id to ipclaims

---

.golangci.yml
controllers/clustermodule_reconciler_test.go
controllers/serviceaccount_controller_suite_test.go
controllers/svcdiscovery_controller_suite_test.go
controllers/vsphereclusteridentity_controller_test.go
pkg/services/govmomi/cluster/vmgroup.go
test/e2e/common.go
test/helpers/framework.go
test/helpers/mod_test.go
test/integration/integration_suite_test.go

This PR syncs the `.golangci.yml` configuration file with the one of [core CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/main/.golangci.yml).
There are parts still commented out on purpose, to not introduce too many different changes at a single PR but to uncomment them in future PRs.
Part of #2058
**Additional info**
Exclude-rules omitted, which are part of core CAPI:
```yaml
- linters:
- staticcheck
text: "SA1019: (bootstrapv1.ClusterStatus|scope.Config.Spec.UseExperimentalRetryJoin|DockerMachine.Spec.Bootstrapped|machineStatus.Bootstrapped) is deprecated"
...
- linters:
- …
```

🌱 Sync golangci-lint configuration to core CAPI

---

.github/workflows/pr-golangci-lint.yaml

Bump golangci-lint to v1.54.1.
The main feature here is go v1.21 support. Notes:
v1.54.0: [golangci/golangci-lint@v1.54.0 (release)](https://github.com/golangci/golangci-lint/releases/tag/v1.54.0)
v1.54.1: [golangci/golangci-lint@v1.54.1 (release)](https://github.com/golangci/golangci-lint/releases/tag/v1.54.1)

:seedling: Bump golangci-lint to v1.54.1

---

docs/proposal/20201103-failure-domain.md

Fix a broken link caught by the weekly markdown run.

:book: Fix broken links in markdown

---

CONTRIBUTING.md
docs/proposal/20201103-failure-domain.md

Fix broken links caught by the weekly markdown run.

[release-1.8]  :book:  Fix broken links in markdown

---

docs/release/release-tasks.md

Replaces the multiple k8s-triage links to have a single one instead which handles all jobs at the same time.
Fixes #

:book: docs: update k8s-triage link to one which catches all jobs

---

Makefile
packaging/flavorgen/flavors/generators.go
templates/cluster-template-external-loadbalancer.yaml
templates/cluster-template-ignition.yaml
templates/cluster-template-node-ipam.yaml
templates/cluster-template.yaml
templates/clusterclass-template.yaml

We introduced powerOffMode in CAPV v1.8. We ensured that the default behavior doesn't change by using "hard" as default on the CRDs. 
I think it's reasonable now to start using trySoft in our cluster-templates and in CI. It's the ideal value and just changing the value in the cluster-templates doesn't break our API behavior in any way.
Also the VM's now have a chance to "return" their DHCP leases during shutdown, which is helpful for CI stability.
P.S. I don't want to cherry-pick this change as I don't want to change the field in cluster-templates in a CAPV v1.8 patch release
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close …

🌱 Enable powerOffMode trySoft in cluster-templates and CI

---

.golangci.yml
apis/v1alpha3/types.go
apis/v1alpha3/vspherevm_types.go
apis/v1alpha4/types.go
apis/v1alpha4/vspherevm_types.go
apis/v1beta1/condition_consts.go
apis/v1beta1/types.go
apis/v1beta1/vspherevm_types.go
apis/vmware/v1beta1/conditions_consts.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
docs/getting_started.md
main.go
test/e2e/e2e_suite_test.go
test/integration/integration_suite_test.go

Check the duplicate words in the code via linter configuration, and fix it. 
Enable `dupword` check in `.golangci.yml` configuration file.
Part of [#2058 ](url)

🌱 lint: fix duplicated words via dupword linter

---

.github/workflows/pr-gh-workflow-approve.yaml

Manual cross-repo cherry-pick of 
- https://github.com/kubernetes-sigs/cluster-api/pull/9244
Fixes #

🌱 github: add workflow to auto-approve golangci-lint if ok-to-test label is set

---

.github/workflows/pr-gh-workflow-approve.yaml

Adds the types `edited` and `reopened` to the triggers for the `PR approve GH Workflows` action.
Before this PR the golangci-lint action could have been triggered by the `edited` or `reopened` actions.
The approval workflow would not get triggered in that case and did not approve the linter.
Cross-repo cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9259
Fixes #

🌱 github: add edited and reopened as triggers for the GH workflow approval

---

.github/dependabot.yml

Add a grouping for all dependencies under `k8s.io/` to the dependabot configuration. This should reduce manual approvals for those dependencies.
Fixes #2202

:seedling: Add dependabot grouping for Kubernetes modules

---

.golangci.yml
packaging/flavorgen/flavors/flavors.go
packaging/flavorgen/flavors/generators.go

1. Fix the checked error by errchkjson linter. (remove the safe returns of errors from `json.Marshal`)
2. Enable `errchkjson` check in `.golangci.yml` configuration file.
3. Enable `linters-settings.errchkjson.check-error-free-encoding`. With it set to true, errchkjson does not report about the errors from json encoding functions that are safe to be ignored, because they are not possible to happen.
Part of #2058

🌱 lint: fix the JSON encoding check error via errchkjson linter

---

pkg/services/govmomi/vcenter/clone.go

This PR fixes some workflows on CAPV + Storage policy:
* When using a storage policy, we need to make sure that the only selected datastores are the DS connected to the cluster/host. Today we don't validate it, which means that we may end up with an invalid datastore on a multi-cluster environment with a storage policy that selects datastores on different clusters, we can select a datastore not connected to our cluster - The new workflow will first get all the datastores connected to the cluster, and then pass this list of datastores to Storage Policy validation
*  When passing both storage policy and datastore, this datastore should be validated on the storage policy and fail if it cannot be used
* Finally, on cloning we MUST pass …

:bug: StoragePolicy should select datastore based on connected hosts and set on VM spec

---

pkg/services/govmomi/vcenter/clone.go

Cherry pick of #2134 for Release v1.5
/assign @sbueringer

[release-1.5] 🐛 StoragePolicy should select datastore based on connected hosts and set on VM spec

---

.golangci.yml
controllers/clustermodule_reconciler_test.go
controllers/serviceaccount_controller_suite_test.go
controllers/vmware/vspherecluster_reconciler_test.go
controllers/vspheredeploymentzone_controller_test.go
pkg/manager/manager_test.go
pkg/record/recorder_test.go
pkg/services/govmomi/cluster/service_test.go
pkg/services/govmomi/extra/extra_suite_test.go
pkg/services/govmomi/util_test.go
pkg/services/network/network_test.go
pkg/services/vmoperator/control_plane_endpoint_test.go
pkg/services/vmoperator/vmopmachine_test.go
pkg/util/supervisor_test.go
test/e2e/anti_affinity_test.go
test/e2e/multivc_test.go
test/e2e/storage_policy_test.go

The PR enables [ginkgolinter](https://github.com/nunnatsa/ginkgolinter). This linter enforce several standards of using ginkgo and gomega, and can find some bugs in tests (e.g. test with no assertion). The PR also fixes all ginkgolinter findings.
Part of #2058

:seedling: lint: enable ginkgolinter and fix findings

---

.golangci.yml
pkg/context/controller_manager_context.go
pkg/services/govmomi/cluster/cluster_suite_test.go
pkg/util/fetch_object.go
test/helpers/vmware/intg_test_context.go

Enable containedctx lint for future code checking, but exclude current failures as we have a separate issue to track the whole refactoring of capv controller context #2295
Part of #2058

🌱 lint: enable containedctx lint

---

go.mod
go.sum

🌱 Bump ClusterAPI to v1.5.1

---

CONTRIBUTING.md
Makefile
hack/ensure-trivy.sh
hack/verify-container-images.sh
hack/verify-licenses.sh

Adds a licence scan inline with what is currently being added in the core Cluster API repo with https://github.com/kubernetes-sigs/cluster-api/pull/9184
Part of https://github.com/kubernetes-sigs/cluster-api/pull/9184

:seedling: Add license scan for pull requests

---

controllers/vspherevm_controller.go
controllers/vspherevm_controller_test.go

Fix a nilpointer error that can occur in the vSphereVM reconciler if the controller's infrastructureRef is nil.
Fixes #2302

:bug: Fix nil pointer error in retrieveVcenterSession

---

Makefile

Release notes here: https://github.com/aquasecurity/trivy/releases/tag/v0.45.0

:seedling: Bump Trivy to v0.45.0

---

controllers/vmware/test/controllers_test.go

1. Fix the YML unmarshal error caused by an incorrect credential format string. (Remove the credential-related code as discussed.)
Fixes #2320

🌱 fix YML unmarshal error at test code

---

.golangci.yml
apis/v1alpha3/cloudprovider_encoding_test.go
apis/v1alpha3/cloudprovider_types.go
apis/v1alpha3/haproxyloadbalancer_types.go
apis/v1alpha3/vspherecluster_types.go
apis/v1alpha4/vspheremachinetemplate_conversion.go
controllers/controllers_suite_test.go
controllers/servicediscovery_controller.go
controllers/vspherecluster_reconciler.go
controllers/vspheredeploymentzone_controller.go
controllers/vspheredeploymentzone_controller_domain_test.go
controllers/vspherevm_controller_test.go
pkg/manager/manager_test.go
pkg/manager/options_test.go
pkg/services/govmomi/util.go
pkg/services/govmomi/vcenter/clone_test.go
pkg/util/label_test.go
test/e2e/gpu_pci_passthrough_test.go
test/e2e/log_collector.go
test/helpers/vmware/intg_test_context.go
test/helpers/webhook.go
test/integration/integration_suite_test.go

1. Enable `gocritic` configuration in the `.golangci.yml` file's `linters-settings` section to check for potential bugs, performance improvements, and style issues.
2. Fix findings related to it.
Part of #2058

🌱 lint: enable `gocritic` configuration and fix findings

---

.github/codecov.yml
.github/workflows/cover.yaml
Makefile
hack/codecov-ignore.sh

Add codecov to keep an overview over our test coverage
(mostly copied from CAPZ)
Part of #2308

🌱 Add codecov

---

CONTRIBUTING.md
README.md

📖 Document backport policy

---

Dockerfile
Makefile
hack/ensure-go.sh

🌱 Bump to Go 1.20.8

---

apis/v1beta1/vsphereclusteridentity_types.go
controllers/vsphereclusteridentity_controller.go

Add a finalizer to ensure the cleanup for this type completes.

🌱 Add finalizer for VSphereClusterIdentity

---

hack/ensure-go.sh

Test coverage jobs are broken (https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#periodic-test-coverage-main) as kubekins image still contains 1.20.7. I think it's not super important to enforce the patch version.
Fixes #

🌱 Only ensure Go minor version

---

config/metrics/crd-clusterrole.yaml
config/metrics/crd-metrics-config.yaml
config/metrics/kustomization.yaml

This PR adds a custom resource config for kube-state-metrics to scrape metrics via kube-state-metrics from the CAPV resources.
This could be used together with https://github.com/kubernetes-sigs/cluster-api/pull/9390 and the following configuration in `tilt-settings.yaml`:
```yaml
deploy_kustomizations:
kube-state-metrics-custom-resource-capv: ../cluster-api-provider-vsphere/config/metrics
```
**Note:** depends on the path to be correct here.
Fixes #

🌱 config: add metrics configuration for kube-state-metrics

---

test/e2e/capv_quick_start_test.go

I think there is no reason why we would need it as PR blocking as we are running the CC quickstart already as PR blocking
Fixes #

🌱 Remove regular quickstart from PR blocking job

---

Makefile
hack/e2e.sh
test/e2e/README.md

This PR intends to define `LDFLAGS` only once for Makefile, which makes `e2e-image` use Docker cache instead of building a new image from scratch.
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1354

🌱 LDFLAGS defined once for Makefile

---

Makefile
apis/.import-restrictions
apis/v1beta1/.import-restrictions
apis/vmware/v1beta1/.import-restrictions
hack/verify-import-restrictions.sh

This PR introduces a new make target `verify-import-restrictions` to verify imports in source codes
to prevent regression mentioned in #2159.
Fixes #2159

🌱 Add verify-import-restrictions to enforce import restrictions

---

Makefile

:seedling: Including all packages in coverage

---

controllers/controllers_suite_test.go
controllers/vmware/test/controllers_test.go
controllers/vspherecluster_controller.go
controllers/vspherecluster_reconciler.go
controllers/vspherecluster_reconciler_test.go
main.go
pkg/manager/manager.go
pkg/manager/network.go
pkg/manager/options.go
test/helpers/envtest.go

Set up golang context when initiating controller manager and also pass it down to VSphereCluster controller.
For other controllers, will update in separate PR.
This is part of #2295.
Part of #2295

✨ Set up golang context when initiating controller manager

---

controllers/vspherecluster_reconciler.go
controllers/vsphereclusteridentity_controller.go
controllers/vspheredeploymentzone_controller.go
controllers/vspheredeploymentzone_controller_domain.go
pkg/identity/identity.go

Signed-off-by: killianmuldoon <kmuldoon@vmware.com>
(cherry picked from commit d63e2bcdebe6498f185ee11939c01a4aebd93c00)
Cherry-pick of the production code from https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2209
Test code was not easily cherry-picked as upstream Cluster API does not export the correct functions.

[release-1.7] :seedling: Add ownerReference resilience test

---

Dockerfile
Makefile
go.mod
go.sum
hack/ensure-go.sh

What this PR does / why we need it:
Bumps Go version to 1.20.8
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

🌱  [release-1.7] Bump to Go 1.20.8

---

Makefile

Release notes: https://github.com/aquasecurity/trivy/releases/tag/v0.45.1

:seedling: Bump Trivy to v0.45.1

---

pkg/services/vimmachine.go
pkg/services/vimmachine_test.go

I'm assuming this is an intermediate state when to support supervisor mode, so it uses unstructured type in VSphereVM reconciler to support two modes. As we now have [vmoperator](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/tree/main/pkg/services/vmoperator) to reconcile VM in supervisor mode, I think we are good to get rid of unstructured type in VSphereVM reconciler, but better to have a review from folks who're more familiar with supervisor mode.
Fixes #2056

🌱 Get rid of unstructured type in VSphereVM reconciler

---

controllers/controllers_suite_test.go
controllers/vspheredeploymentzone_controller.go
controllers/vspheredeploymentzone_controller_domain.go
controllers/vspheredeploymentzone_controller_domain_test.go
controllers/vspheredeploymentzone_controller_test.go
main.go
pkg/services/govmomi/cluster/rule.go
pkg/services/govmomi/cluster/rule_test.go
pkg/services/govmomi/cluster/service.go
pkg/services/govmomi/cluster/vmgroup.go
pkg/services/govmomi/metadata/metadata.go
pkg/services/govmomi/metadata/metadata_suite_test.go
pkg/services/interfaces.go
pkg/taggable/get.go

Refactor context for vspheredeploymentzone_controller.go and vspheredeploymentzone_controller_domain.go, as they are related, also refactor some underlying functions. Please find more background in #2295 
Part of #2295

✨ refactor context for vspheredeploymentzone controller

---

Makefile

Signed-off-by: killianmuldoon [kmuldoon@vmware.com](mailto:kmuldoon@vmware.com)
Bump apidiff to v0.7.0
Release notes: [joelanford/go-apidiff@v0.7.0 (release)](https://github.com/joelanford/go-apidiff/releases/tag/v0.7.0)

:seedling: Bump apidiff to v0.7.0

---

controllers/controllers_suite_test.go
controllers/vsphereclusteridentity_controller.go
controllers/vsphereclusteridentity_controller_test.go
main.go

Refactor the context in `vsphereclusteridentity_controller.go` and correct any corresponding function calls. You can discover additional information in reference to #2295.
Part of #2295

✨ refactor context for vsphereclusteridentity controller

---

controllers/controllers_suite_test.go
controllers/vmware/test/controllers_test.go
controllers/vspheremachine_controller.go
main.go

Refactor context for vspheremachine_controller.go. Please find more background in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2295
**Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged)**:
Part of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2295

✨ Refactor context for vspheremachine controller

---

test/e2e/anti_affinity_test.go

This PR removes the requirement to have at least 4 esxi hosts for the anti-affinity test. Instead it uses the number of available esxi hosts with a maximum of 10.
Fixes #2368

🌱 Use number of esxi hosts as worker node count for anti-affinity e2e test

---

.golangci.yml
controllers/vspheredeploymentzone_controller_domain.go
test/e2e/e2e_suite_test.go
test/e2e/log_collector.go
test/helpers/mod.go
test/helpers/vcsim/builder.go
test/helpers/webhook.go
test/integration/integration_suite_test.go

Removes some exclusions from `.golangci.yaml`
Part of #2058

🌱 lint: remove linter ignores from .golangci-lint for gosec

---

controllers/vspherecluster_reconciler.go
pkg/services/network/constants.go
pkg/services/vmoperator/control_plane_endpoint.go

Cleanup to fix deprecated markers across the codebase so that they meet the go api deprecation standard.

:seedling: Fix deprecated markers across codebase

---

go.mod
go.sum

Bump Cluster API to its latest patch release.
Release notes here: https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.5.2

:seedling: Bump Cluster API to v1.5.2

---

go.mod
go.sum
test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/integration/integration-dev.yaml

Release notes here: [kubernetes-sigs/cluster-api@v1.5.2 (release)](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.5.2)

[release-1.8] :seedling: Bump Cluster API to v1.5.2

---

test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/integration/integration-dev.yaml

Follow-up to #https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2401
Bump components in the e2e and integration test configurations.

:seedling: Bump CAPI test components to v1.5.2

---

controllers/vspheredeploymentzone_controller.go
controllers/vspheredeploymentzone_controller_domain.go
controllers/vspheredeploymentzone_controller_domain_test.go
controllers/vspheredeploymentzone_controller_test.go
pkg/context/vspheredeploymentzone_context.go
pkg/taggable/get.go

Reorder the reconcile function of the VSphereDeploymentZone in order to ensure deletion can proceed even if the failureDomain does not exist.

🐛 Handle missing VSphereFailureDomain on VSphereDeploymentZone deletion

---

packaging/flavorgen/flavors/generators.go
templates/cluster-template-ignition.yaml
test/e2e/data/infrastructure-vsphere/main/ignition/ignition.yaml

Ensure kubeadm runs after containerd to avoid a race condition between the two.
We intentionally add an `After=` directive and not a `Requires=` directive to avoid breaking things for distros which use Ignition and don't use containerd.
See https://github.com/kubernetes-sigs/image-builder/issues/939.
None

:bug: flatcar: Run kubeadm after containerd

---

apis/v1alpha3/conversion_test.go
pkg/services/govmomi/util.go
pkg/services/govmomi/vcenter/clone.go
test/helpers/envtest.go

Remove  usage of following:
`//nolint:gocyclo`
`//nolint:gocognit`
`//nolint:paralleltest`
`//nolint:wrapcheck`
Part of #2384

🌱 Remove nolint usages for gocyclo, paralleltest, wrapcheck and gocognit

---

controllers/vmware/vspherecluster_reconciler.go
pkg/identity/identity_test.go
pkg/services/network/dummy_provider.go

Remove usage of following:
`//nolint:revive`
`//nolint:prealloc`
`//nolint:goconst`
Didn't find any occurrence of `//nolint:errcheck` in codebase.
The comment for `//nolint:ineffassign` is alrady present in the occurrence.
Part of #2384

🌱 Remove nolint usages for errcheck, revive, prealloc, goconst, ineffassign

---

controllers/vspherecluster_reconciler.go
pkg/services/govmomi/service.go
pkg/services/govmomi/vcenter/clone.go
pkg/services/vimmachine.go

This PR removes all unused `//nolint:nestif `directives. 
Note: This specific lint check was not enabled.
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2384

🌱 remove //nolint:nestif directives

---

controllers/vspheremachine_controller.go
pkg/context/fake/fake_machine_context.go
pkg/context/interfaces.go
pkg/context/machine_context.go
pkg/context/vmware/machine_context.go
pkg/services/interfaces.go
pkg/services/services_suite_test.go
pkg/services/vimmachine.go
pkg/services/vimmachine_test.go
pkg/services/vmoperator/vmoperator_suite_test.go
pkg/services/vmoperator/vmopmachine.go
pkg/services/vmoperator/vmopmachine_test.go
pkg/util/testutil.go

Improve logging for VSphereMachine controller and underlying packages.
Part of #2076

🌱 Improve logging for VSphereMachine

---

pkg/services/govmomi/ipam/parse.go
pkg/services/govmomi/ipam/status_test.go

Signed-off-by: ekarlso <endre.karlson@xait.com>
Fixes #

:bug: Remove the conditional on ipv6

---

OWNERS_ALIASES

Update the owners file to clarify which members of the `  cluster-api-maintainers` list are active maintainers of CAPV.
This adds a bit of duplication to the file, but it's clearer.

:seedling: Clarify OWNER_ALIASES file

---

controllers/controllers_suite_test.go
controllers/vspheremachine_controller.go
pkg/services/govmomi/service.go

Remove `//nolint:gocritic` linter and fix findings.
1. Remove `nolint:gocritic` for `/controllers/controllers_suite_test.go`
1. To properly execute the `teardown`, I remove the `defer` keyword and place it before the `os.Exit(code)` statement.
2. Remove `nolint:gocritic` for `/controllers/vspheremachine_controller.go`
1. To simplify the code, I merge the conditions `r.supervisorBased` and `machineCtx.GetCluster().Status.InfrastructureReady` using an `else if` statement as recommended by `gocritic`.
3. Remove `nolint:gocritic` for `pkg/services/govmomi/service.go`
1. Reconstruct the `switch` logic, and use an if to replace it.
2. I noticed a TODO comment from @akutz  that suggests using a switch instead of an if statement to check metadata encoding. …

🌱 Remove lint ignore for `gocritic`

---

.golangci.yml
controllers/vspheredeploymentzone_controller_domain.go
internal/webhooks/vspherefailuredomain.go
internal/webhooks/vspherefailuredomain_test.go

- Remove usage of `//nolint:staticcheck`.
- Add a new rule to exclude static check for some fields will be deprecated in a future release.
- The only remaining `nolint:staticcheck` [here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/controllers/vmware/vspherecluster_reconciler.go#L312) is needed because the `ctx` is not used, but we need it.
Part of fixes #2384

🌱 Remove lint ignore for staticcheck

---

controllers/controllers_suite_test.go
controllers/vspherevm_controller.go
controllers/vspherevm_controller_test.go
controllers/vspherevm_ipaddress_reconciler.go
controllers/vspherevm_ipaddress_reconciler_test.go
main.go
pkg/services/fake/vmservice.go
pkg/services/govmomi/cluster/vmgroup.go
pkg/services/govmomi/cluster/vmgroup_test.go
pkg/services/govmomi/create.go
pkg/services/govmomi/create_test.go
pkg/services/govmomi/ipam/status.go
pkg/services/govmomi/ipam/status_test.go
pkg/services/govmomi/power.go
pkg/services/govmomi/power_test.go
pkg/services/govmomi/service.go
pkg/services/govmomi/service_test.go
pkg/services/govmomi/template/template.go
pkg/services/govmomi/util.go
pkg/services/govmomi/util_test.go
pkg/services/govmomi/vcenter/clone.go
pkg/services/interfaces.go
pkg/util/fetch_object.go
pkg/util/fetch_object_test.go

Refactor context for vSphereVM controller and underlying functions that vSphereVM controller are consuming, this is a part of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2295.
Fixes part of #2295

✨ Refactor context for vspherevm controller

---

controllers/vsphereclusteridentity_controller.go

Improve logging for VsphereClusterIdentity controller
Part of #2076

🌱 Improve logging for cluster identity controller

---

Dockerfile
Makefile

Bump the go version used to build CAPI to v1.20.10

:seedling: Bump Go to v1.20.10

---

go.mod
go.sum

Bump golang.org/x/net to v0.17.0
Release notes: https://github.com/golang/net/releases/tag/v0.17.0

:seedling: Bump golang.org/x/net to v0.17.0

---

Makefile

Bump trivy to v0.46.0.
Release notes: https://github.com/aquasecurity/trivy/releases/tag/v0.46.0

:seedling: Bump trivy to v0.46.0

---

Makefile

Bump dependencies for:
- envtest
- gotestsum
- conversion-gen
- yq
- govulncheck

:seedling: Bump Makefile dependency versions

---

clusterctl-settings.json
metadata.yaml

This PR addresses following to prepare main branch for release-1.9:
[Prepare main branch for development of the new release](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md#prepare-main-branch-for-development-of-the-new-release)
Part of #2207

✨ Prepare main branch for release-1.9 development

---

pkg/clustermodule/service_test.go
test/helpers/vcsim/builder.go

1. Add unit test cases for `pkg/clustermodule/service.go`
Part of #2308

🌱 Add unit test cases for clustermodule

---

pkg/services/vimmachine.go

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2395 removed a return from reconciliation.
When an error occurs, the caller cannot be able to verify there was an error, and moves forward, calling the pointer of object "vm", which is null
This PR re-adds https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/commit/a3f651f1606429b718a1d4583bfa827665167e0e#diff-2f616e5f5f40526609f3723e82cbcf01b16b9f240ea00fcdf3fc06b6aa6d164cL132

:bug: Re-add return on vimmachine error

---

test/e2e/data/kubetest/upstream-conformance.yaml
test/e2e/data/kubetest/upstream-e2e-alpha-features.yaml
test/e2e/data/kubetest/upstream-e2e-serial.yaml
test/e2e/data/kubetest/upstream-e2e-slow.yaml
test/e2e/data/kubetest/upstream-e2e.yaml

Adds kubetest yaml files for #2452

🌱 Add kubetest files for upstream e2e tests

---

go.mod
go.sum
pkg/services/govmomi/service.go
pkg/services/govmomi/service_test.go
pkg/services/govmomi/storageprofile_util.go

During the debug of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2453#issuecomment-1773244913 we have figured out this call is too expensive for environments with a lot of resources, like more than 10k resources.
This may turn into a huge slow query that can take up to 20 minutes.
Instead, we should be using the "QueryAssociatedProfiles" call that, given an object (like a disk), check if it has associated storage policies
Fixes #
**Note** https://github.com/vmware/govmomi/pull/3268 implements the call directly on pbmClient, but as this is not released yet I have added …

:bug: Use a cheaper method for storage policy

---

test/e2e/data/kubetest/upstream-e2e-alpha-features.yaml
test/e2e/data/kubetest/upstream-e2e-serial.yaml
test/e2e/data/kubetest/upstream-e2e-slow.yaml
test/e2e/data/kubetest/upstream-e2e.yaml

Fixes the kubetest configuration for the upstream tests to match the upstream configuration.
Adds `ginkgo.flake-attempts: 1`.
part of #2452

🌱 kubetest: add flake attempts configuration to match upstream tests

---

Makefile

Bump Trivy to v0.47.0
Release notes: https://github.com/aquasecurity/trivy/releases/tag/v0.47.0

:seedling: Bump Trivy to v0.47.0

---

controllers/vspherecluster_reconciler.go
controllers/vspherecluster_reconciler_test.go
controllers/vspheremachine_controller.go
controllers/vspheremachine_controller_test.go
test/e2e/ownerreference_test.go

Remove special handling for orphaned VSphereMachines. VSphereMachines should no longer be orphaned by CAPI MachineSets on creation so this safeguard is no longer needed.
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2054

:seedling: Remove handling for orphaned VSphereMachines

---

Dockerfile
Makefile

To fix the CVE in our test code: https://github.com/sbueringer/cluster-api-provider-vsphere/actions/runs/6849967877/job/18623212588
Fixes #

🌱 Bump to Go 1.20.11

---

controllers/vspherevm_controller.go
controllers/vspherevm_controller_test.go
controllers/vspherevm_ipaddress_reconciler.go
controllers/vspherevm_ipaddress_reconciler_test.go
pkg/context/fake/fake_vm_context.go
pkg/context/vm_context.go
pkg/services/govmomi/create_test.go
pkg/services/govmomi/ipam/status_test.go
pkg/services/govmomi/metadata/metadata_suite_test.go
pkg/services/govmomi/service_test.go
pkg/services/govmomi/vcenter/clone.go

**What this PR does / why we need it**: 
This improves logging in `vspherevm_controller `& `vspherevm_ipaddress_reconciler` by using the logger from passed context and removing `ControllerContext` types.
Fixes # https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2076

🌱 Improve logging for `vspherevm_controller` & `vspherevm_ipaddress_reconciler`

---

packaging/flavorgen/flavors/generators.go
templates/cluster-template-ignition.yaml
templates/cluster-template-node-ipam.yaml
templates/cluster-template-topology.yaml
templates/cluster-template.yaml

Bump the kube-vip to 0.6.3 in the flavor templates.
Also enable kube-vip to watch service for LB.
Fixes #2507

:seedling: Bump kube-vip to 0.6.3 and enable service mode

---

Makefile
README.md
config/manager/manager.yaml
config/rbac/role.yaml
main.go
test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/e2e/data/shared/main/v1beta1/metadata.yaml
test/integration/integration-dev.yaml

🌱 Finalize CAPI v1.6.0-beta.1 bump & diagnostics implementation

---

config/default/crd/kustomization.yaml

When building the manifests kustomizations with kustomize v5 I'm getting the following error.
```
error: invalid Kustomization: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch
```
This is because kustomize v5.0 has dropped support for legacy patches.
https://github.com/kubernetes-sigs/kustomize/pull/4911
https://github.com/kubernetes-sigs/kustomize/issues/1373
As such the suggestion is to add the newly supported patches' `- path:` syntax, which should be [compatible as back as kustomize 3.0.1](https://github.com/kubernetes-sigs/kustomize/issues/1373#issuecomment-618439078)

✨ Update kustomization.yaml to support kustomize v5

---

controllers/serviceaccount_controller.go
controllers/servicediscovery_controller.go
controllers/vspherevm_controller.go

Similar to https://github.com/kubernetes-sigs/cluster-api/pull/9810
Sets RequeueAfter: time.Minute instead of Requeue: true on ErrClusterLocked.
This way the requeue does not end up in the Rate Limited Queue with exponential time
/assign sbueringer 
Fixes #

🐛 ClusterCacheTracker: Use RequeueAfter 1 minute instead of immediate requeue when ErrClusterLocked gets returned to not fall into exponential requeue

---

pkg/session/session.go

While doing some scalability tests, we have realized that vAPI (Rest) was getting into user limits and erroring new logins.
This didn't stopped soap client to keep logging in and not logging out, consuming all the available userSessions on vCenter
Fixes #

:bug: Force logout of sessions in case of errors

---

controllers/vspherecluster_reconciler.go
pkg/services/govmomi/util.go

See https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2465#issuecomment-1853768810
Kudos to @chrischdi for the nice research!!
Fixes #2465

🌱 Remove reconcile when APIserver is online in VSphereCluster controller

---

test/e2e/data/infrastructure-vsphere/main/clusterclass/kustomization.yaml
test/e2e/data/infrastructure-vsphere/main/clusterclass/patch-namingstrategy.yaml

🌱 Add e2e test coverage for namingStrategy

---

test/e2e/ownerreference_test.go

Properly uses `defer GinkgoRecover` in go routine.
Error occured in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/2550/pull-cluster-api-provider-vsphere-e2e-full-main/1734914800363769856
Fixes #

🐛 test: use GinkgoRecover in go subroutine of ownerreference test

---

controllers/serviceaccount_controller.go
controllers/servicediscovery_controller.go
controllers/vmware/vspherecluster_reconciler.go
controllers/vsphereclusteridentity_controller.go
controllers/vspheredeploymentzone_controller.go
controllers/vspheremachine_controller.go
controllers/vspherevm_controller.go

The goal of this PR is to implement consistent pause behavior, which is:
* if cluster.spec.paused is true => do nothing (if the cluster object is available)
* if reconciled object has paused annotation => do nothing
I mostly tried to keep the previous behavior regarding what should happen if we can't retrieve the cluster object. This is handled very differently across various providers. Maybe the reconciles still have to work even if the Cluster object is already gone, I have no idea.
Fixes #2510

🌱 Implement consistent pause behavior

---

Makefile

Since introducing the clusterctl upgrade tests in #2517, our e2e-full suite could take longer than 2h.
This for now increases the timeout so we at least have a signal.
Fixes #

🌱 ginkgo: increase timeout to 3h

---

test/e2e/e2e_suite_test.go

Discovered the following during test:
```
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
>  goroutine 59 [running]:
>  runtime/debug.Stack()
>  	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
>  	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/log.go:60 +0xcd
>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc0006756c0, {0x2dac73c, 0x14})
>  	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/deleg.go:147 +0x4c
>  github.com/go-logr/logr.Logger.WithName({{0x31f08f8, 0xc0006756c0}, 0x0}, {0x2dac73c?, 0x0?})
> …
```

🌱 test: set logger in e2e suite

---

.github/dependabot.yml
.github/workflows/pr-dependabot.yaml

Follow up to #2532
Adapts configuration from github.com/kubernetes-sigs/cluster-api
/assign @fabriziopandini 
Fixes #

🌱 Dependabot: add github action to fix modules on PRs and add test to configuration

---

pkg/services/vmoperator/vmopmachine.go
pkg/services/vmoperator/vmopmachine_test.go
pkg/util/testutil.go

VMOp mutation webhook updates the VMOp Spec.ImageName to a user-friendly name prefixed `vmi-` or `cvmi-`. This causes the reconciliation of the VSphereMachine to fail since the controllers copy the all spec fields to the VMOp `VirtualMachine` on every reconcile. Since imageName is an immutable field we see the below error:
```yaml
Name:         guestcluster1-control-plane-bz7k9-c9whq
Namespace:    gctest
Labels:       cluster.x-k8s.io/cluster-name=guestcluster1
cluster.x-k8s.io/control-plane=
cluster.x-k8s.io/control-plane-name=guestcluster1-control-plane
topology.cluster.x-k8s.io/owned=
Annotations:  cluster.x-k8s.io/cloned-from-groupkind: VSphereMachineTemplate.vmware.infrastructure.cluster.x-k8s.io
cluster.x-k8s.io/cloned-from-name: …
```

🐛 Skip updating VMOp immutable fields

---

go.mod
go.sum

Bumping crypto to get the security scan back to green (xref: https://github.com/sbueringer/cluster-api-provider-vsphere/actions/runs/7377303614/job/20089976745)
Fixes #

🌱 Bump golang.org/x/crypto to v0.17.0

---

controllers/vspherecluster_controller.go
controllers/vspherecluster_reconciler.go
controllers/vspheremachine_controller.go
pkg/services/interfaces.go
pkg/services/vimmachine.go
pkg/services/vmoperator/vmopmachine.go
pkg/services/vmoperator/vmopmachine_test.go
pkg/util/machines.go

This patch refactors the VSphereMachine Service interface to expose a new method to get the VSphereVM objects associated with a Cluster object.
The idea is to reuse the VSphereMachine service without the need to repeat similar code blocks in two places.
n/a
/hold
Waiting for #2566 to be merged

🌱 Refactor: Get VSphereMachine functions

---

pkg/services/vmoperator/vmopmachine.go
pkg/services/vmoperator/vmopmachine_test.go

This is to ensure CAPV created resources should have the CAPI cluster-name label. VSphereVM already has it like [here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/pkg/services/vimmachine.go#L316), so just add it for vm-operator VM in this PR.
Fixes #2218

🌱 Ensure vm-operator VM has CAPI cluster-name label

---

controllers/serviceaccount_controller_intg_test.go
controllers/vmware/test/controllers_test.go
controllers/vspherecluster_reconciler.go
controllers/vsphereclusteridentity_controller.go
controllers/vspheredeploymentzone_controller.go
controllers/vspheredeploymentzone_controller_domain.go
controllers/vspheredeploymentzone_controller_test.go
controllers/vspherevm_controller_test.go
controllers/vspherevm_ipaddress_reconciler.go
internal/test/helpers/vmware/intg_test_context.go
pkg/context/fake/fake_cluster_context.go
pkg/context/fake/fake_machine_context.go
pkg/context/fake/fake_util.go
pkg/services/govmomi/util.go
pkg/services/vimmachine.go

Same as: https://github.com/kubernetes-sigs/cluster-api/pull/9956
Fixes #

🌱 Stop relying on GVK being set on regular typed objects

---

config/base/manager_image_patch.yaml
config/manager/manager.yaml
test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/integration/integration-dev.yaml
tilt-provider.json

When the CAPV image hasn't been build locally we should default to using the latest image from main. Not some old image from the old registry.
Fixes #

🌱 Use correct image from main per default when running e2e tests locally

---

test/e2e/e2e_suite_test.go

🌱 Sync e2e_suite_test.go with core CAPI

---

main.go

Just noticed that %v doesn't make sense when bumping CR in core CAPI (in core CAPI it will be addressed when bumping CR)
Fixes #

🌱 Fix error log when default level cannot be set

---

hack/e2e.sh

Everything that we store in ARTIFACTS will be uploaded to GCS. Storing the CAPV image there means that every single e2e job that we run requires an additional ~ 90 MB of storage. So let's not do that.
Fixes #

🌱 e2e: Stop storing the CAPV image in artifacts

---

Makefile

Note: Previous version had some problems related to generics (we found this in controller-runtime)
Fixes #

🌱 Bump go-apidiff to v0.8.2

---

README.md

🌱 Clarify our goals for CAPV releases related to CAPI, CPI and Kubernetes releases

---

docs/troubleshooting.md

Just saw these old images referenced here while grepping for usage of these images.
Fixes #

🌱 Fix images in troubleshooting doc

---

main.go

Makes CAPV fail on startup if no CRD's exist and mode detection won't add any manager.
/assign @sbueringer 
Fixes #

🌱 Fail startup if no CRDs are detected

---

hack/ensure-kubectl.sh

🌱 Fix ensure-kubectl script

---

README.md

🌱 Update docs to link to the OVAs in the community-owned GCS bucket

---

Makefile
docs/release/release-tasks.md

Depends on:
- https://github.com/kubernetes-sigs/cluster-api/pull/9937
Related to:
- https://github.com/kubernetes/test-infra/pull/31654
Fixes #

🌱 Add generate-test-infra-prowjobs makefile target and update docs

---

packaging/flavorgen/cloudprovider/cloud-controller-manager.go
packaging/flavorgen/cloudprovider/cpi/cpi.yaml
packaging/flavorgen/cloudprovider/embed.go
packaging/flavorgen/flavors/crs/cpi.go
templates/cluster-template-external-loadbalancer.yaml
templates/cluster-template-ignition.yaml
templates/cluster-template-node-ipam.yaml
templates/cluster-template-topology.yaml
templates/cluster-template.yaml

Use `helm template --namespace=kube-system` to generate the CPI manifests used in flavor-gen.
This allows to streamline the update progress of CPI.
Fixes #

🌱 flavor-gen: bump CPI manifests and use embed instead of hardcoding

---

OWNERS_ALIASES

This PR adds myself (@laozc) to the CAPV reviewer list.
I've been contributing to CAPV project since July 2023.
I made a few changes with some feature and bug fixes.
I would like to continue with that in future with a new role as a reviewer to help the project.
PRs: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pulls?q=is%3Apr+is%3Aclosed+author%3Alaozc
Issues: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues?q=is%3Aissue+is%3Aclosed+author%3Alaozc

:seedling: Add laozc to CAPV reviewer

---

Makefile
hack/e2e.sh
test/e2e/README.md
test/e2e/anti_affinity_test.go
test/e2e/capi_machine_deployment_rollout_test.go
test/e2e/cluster_upgrade_test.go
test/e2e/clusterclass_changes_test.go
test/e2e/clusterctl_upgrade_test.go
test/e2e/common.go
test/e2e/dhcp_overrides_test.go
test/e2e/e2e_suite_test.go
test/e2e/govmomi_test.go
test/e2e/gpu_pci_passthrough_test.go
test/e2e/hardware_upgrade_test.go
test/e2e/helper/helper.go
test/e2e/ipam/ipamhelper.go
test/e2e/ipam/noop.go
test/e2e/k8s_conformance_test.go
test/e2e/md_scale_test.go
test/e2e/multivc_test.go
test/e2e/node_drain_timeout_test.go
test/e2e/node_labeling_test.go
test/e2e/ownerreference_test.go
test/e2e/quick_start_test.go
test/e2e/storage_policy_test.go
test/go.mod

🌱 e2e: Claim ip addresses dynamically so tests can run in parallel

---

hack/e2e.sh

Fixes the failing wait for ipam.
The service account used is not allowed to do `kubectl cluster-info`.
Also at the end it did not fail when reaching the timeout.
Fixes #

🌱 hack/e2e.sh fix waiting for ipam

---

packaging/flavorgen/flavors/kubevip/files.go
packaging/flavorgen/flavors/kubevip/kube-vip.yaml
packaging/flavorgen/flavors/kubevip/kubevip.go
packaging/flavorgen/flavors/kubevip/topology.go
templates/cluster-template-ignition.yaml
templates/cluster-template-node-ipam.yaml
templates/cluster-template-topology.yaml
templates/cluster-template.yaml

* Bumps kube-vip to v0.6.4
* Adjusts flavorgen to import kube-vip.yaml from file and add required changes on top.
Fixes #

🌱 flavorgen: bump kubevip to v0.6.4 and import from file

---

test/e2e/anti_affinity_test.go

Follow-up from release-1.6 flakyness.
Requires manual cherry-pick to release-1.6
Fixes #

🌱 test: change way to get number of hosts to not rely on read hosts permissions

---

packaging/flavorgen/flavors/kubevip/kube-vip-prepare.sh
templates/cluster-template-ignition.yaml
templates/cluster-template-node-ipam.yaml
templates/cluster-template.yaml
templates/clusterclass-template.yaml

Fixes the kubve-vip-prepare.sh for kubernetes versions < v1.29
Fixes #2659

🐛 kube-vip: fix prepare script to work on pre k8s v1.29

---

test/framework/ip/incluster.go

Fixing flakes like: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/2655/pull-cluster-api-provider-vsphere-e2e-full-main/1750560965209886720
Fixes #

🌱 test: ignore VMs on errors retrieving the properties

---

Makefile
hack/e2e.sh
test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/integration/integration-dev.yaml

Just renaming the image we use in e2e tests to be ~ consistent how we do it in CAPI.
Fixes #

🌱 Rename e2e-image

---

controllers/vmware/test/controllers_test.go

Fixes the error `fatal error: concurrent map read and map write` by not re-using `scheme.Scheme` but using our own `runtime.Scheme` instead.
Fixes #2325

🐛 controllers/vmware fix test to not contain data race

---

test/framework/log/collector.go

`cat /var/log/cloud-init-output.log` resulted in:
```
cat: /var/log/cloud-init-output.log: Permission denied
```
This makes use of sudo which fixes that. Also adds stderr to the output.
Fixes #

🌱 test: fix log collector for cloud-init

---

controllers/vspherevm_controller.go

A vSphereVM could reconcile again with using an outdated object from the cache.
In case of a VSphereVM which get's deleted this could lead to triggering a task to destroy the VM twice. While the second one would fail after some timeout.
Did hit this issue at https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/2594/pull-cluster-api-provider-vsphere-e2e-main/1752293260056858624
Fixes #

🐛 vspherevm: ensure that the cache gets updated when patching .status.taskRef

---

test/e2e/e2e_suite_test.go
test/e2e/govmomi_test.go

Cleanup of function which is already implemented in CAPI.
Fixes #

🌱 test: remove getClusterctlConfigVariable function and use capi framework functions instead

---

hack/e2e.sh

Only uploads the docker image to gcs when we don't set `GINKGO_FOCUS`.
We set `GINKGO_FOCUS` at all e2e periodics + presubmits except for the `{periodic,pull}-cluster-api-provider-vsphere-e2e` which are the only ones where we require to upload the images because of running the clusterctl upgrade tests.
Fixes #

🌱 e2e: only upload images to gcs if we run tests which need it

---

test/infrastructure/vcsim/api/v1alpha1/controlplaneendpoint_types.go
test/infrastructure/vcsim/api/v1alpha1/envvar_types.go
test/infrastructure/vcsim/api/v1alpha1/vcsim_types.go
test/infrastructure/vcsim/api/v1alpha1/zz_generated.deepcopy.go
test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_controlplaneendpoints.yaml
test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_envvars.yaml
test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_vcentersimulators.yaml
test/infrastructure/vcsim/controllers/controlplaneendpoint_controller.go
test/infrastructure/vcsim/controllers/envvar_controller.go
test/infrastructure/vcsim/controllers/vcsim.go
test/infrastructure/vcsim/controllers/vcsim_controller.go

According to API conventions we should not use int in API types 😅

🌱 Fix vcsim API replacing int with int32

---

test/e2e/data/infrastructure-vsphere/main/clusterclass/patch-prekubeadmscript.yaml

We have to run the prekubeadmscript as first so other commands which depend on the versions (e.g. kube-vip-prepare.sh) run with the correct version.
Fixes #

🌱 test: run the prekubeadmscript first

---

.dockerignore
Dockerfile
Makefile
hack/e2e.sh
test/e2e/config/vsphere.yaml
test/framework/vmoperator/vmoperator.go
test/infrastructure/vcsim/Dockerfile
test/integration/integration-dev.yaml

Align docker-build (Dockerfiles, .dockerignore, make targets) to what we are doing in CAPI, use the same build targets for E2E

🌱 Align docker build to CAPI

---

test/e2e/cluster_upgrade_test.go

Increases the amount of worker nodes for the k8s upgrade and conformance test to 5 to align with the other conformance tests which are green.
Fixes #

🌱 test: use 5 worker nodes for k8s upgrade + conformance test

---

Makefile
hack/tools/janitor/README.md
hack/tools/janitor/janitor.go
hack/tools/janitor/main.go
hack/tools/janitor/vsphere.go

Adds `hack/tools/janitor`, a small tool which can be run as cronjob in CI to cleanup leftover objects over time.
As of now cleanup was done manually but since running jobs in parallel, we may have more leftover objects so its more often required to cleanup things.
Fixes #

🌱 hack: add capv-janitor for automated ci cleanup

---

hack/clean-ci.sh
hack/tools/janitor/main.go

Properly sets the KUBECONFIG env var and return a proper error.
Fixes #

🌱 hack: fix janitor to properly set kubeconfig and log an error

---

hack/tools/janitor/janitor.go

task.Name() returns empty strings 🤦 using `task.Reference().Value` now, as we do in our controller.
Fixes #

🌱 hack/janitor: fix printing task id

---

hack/e2e.sh

Fixes hack/e2e.sh to look for the right image and by that e2e-main: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-vsphere-e2e-main/1755157866454454272
Issue got introduced in #2691 
Fixes #

🌱 hack: follow up fix from aligning image build process

---

.github/workflows/pr-golangci-lint.yaml
controllers/clustermodule_reconciler.go
controllers/clustermodule_reconciler_test.go
controllers/vspheremachine_controller.go
controllers/vspherevm_controller.go
internal/test/helpers/envtest.go
internal/webhooks/vspheredeploymentzone_test.go
internal/webhooks/vspherefailuredomain_test.go
internal/webhooks/vspheremachine_test.go
internal/webhooks/vspheremachinetemplate_test.go
internal/webhooks/vspherevm_test.go
packaging/flavorgen/cmd/root.go
packaging/flavorgen/flavors/crs/types/cloudprovider_encoding.go
packaging/flavorgen/flavors/crs/types/cloudprovider_encoding_test.go
pkg/identity/identity_suite_test.go
pkg/manager/options.go
pkg/manager/options_test.go
pkg/services/govmomi/util_test.go
pkg/session/session.go
pkg/util/machines_test.go
pkg/util/supervisor_test.go
test/infrastructure/tmp-to-be-deleted/runtime/cache/client_test.go
test/infrastructure/tmp-to-be-deleted/runtime/cache/gc.go
test/infrastructure/tmp-to-be-deleted/runtime/cache/sync.go
test/infrastructure/tmp-to-be-deleted/server/api/handler.go
test/infrastructure/tmp-to-be-deleted/server/api/portforward/httpstreams.go
test/infrastructure/tmp-to-be-deleted/server/etcd/handler_test.go
test/infrastructure/tmp-to-be-deleted/server/mux.go

🌱  bump golangci-lint to v1.56.1

---

go.mod
go.sum
hack/tools/janitor/janitor.go
pkg/services/govmomi/cluster/vmgroup_test.go
pkg/services/govmomi/create_test.go
pkg/services/govmomi/util.go
test/go.mod
test/go.sum
test/infrastructure/vcsim/controllers/vmip_controller.go

Dependabot upgraded Govmomi to version 0.35.0 and some functions have been deprecated. This PR replaces the deprecated functions on top of dependabot's upgrade.

🌱 Bump github.com/vmware/govmomi from 0.34.2 to 0.35.0

---

.github/workflows/pr-golangci-lint.yaml
.golangci.yml
Makefile
hack/ensure-go.sh
main.go
pkg/services/govmomi/util_test.go
pkg/services/network/nsxt_provider.go
pkg/services/vmoperator/vmopmachine_test.go

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2741

[release-1.7] 🌱 Bump to Go 1.21

---

controllers/serviceaccount_controller_suite_test.go
controllers/servicediscovery_controller_intg_test.go
controllers/servicediscovery_controller_suite_test.go
internal/test/helpers/vmware/intg_test_context.go

This should resolve the flaky tests for the service discovery controller we have on main and release-1.9 from https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/controllers/servicediscovery_controller_intg_test.go.
The tests did use a cached client and did assert on cached client data. Using an uncached api reader / client instead makes the test stable.
Also this improves some timeouts in eventually instead of only trying it once.
Heavily tested at #2749
Should solve:
* [service discovery controller tests](https://storage.googleapis.com/k8s-triage/index.html?date=2024-02-19&job=.*-cluster-api-provider-vsphere.*&test=.*Service%20Discovery%20controller%20integration%20tests.*)
/cherry-pick release-1.9
**Which issue(s) this PR …

🐛 controllers/test: use APIReader to not assert on cached information

---

docs/release/release-tasks.md

We added a go module in `test` since v1.9. We also should add tags for the test module.
Fixes #

📖 docs: document tagging the test go module

---

Makefile
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/vsphere.yaml
test/e2e/data/infrastructure-vsphere/main/ipam/ipam-patch.yaml
test/e2e/data/infrastructure-vsphere/main/ipam/ippool.yaml
test/e2e/data/infrastructure-vsphere/main/ipam/kustomization.yaml
test/e2e/data/shared/v1.9/v1beta1_ipam/metadata.yaml
test/e2e/e2e_setup_test.go
test/e2e/ipam_test.go
test/framework/framework.go
test/framework/ip/addressmanager.go
test/framework/ip/incluster.go
test/framework/ip/noop.go

🌱 test/e2e: implement e2e test for IPAM

---

packaging/flavorgen/flavors/clusterclass_generators.go
packaging/flavorgen/flavors/env/envsubts_consts.go
packaging/flavorgen/flavors/generators.go
packaging/flavorgen/flavors/util/helpers.go
templates/cluster-template-external-loadbalancer.yaml
templates/cluster-template-ignition.yaml
templates/cluster-template-node-ipam.yaml
templates/cluster-template-topology.yaml
templates/cluster-template.yaml
templates/clusterclass-template.yaml

Add CONTROL_PLANE_ENDPOINT_PORT env var / cluster class var as required by vcsim

🌱 Make Flavor gen templates vcsim friendly

---

controllers/servicediscovery_controller_suite_test.go

🐛 controllers: add 3 second timeout to assertion in test to deflake

---

controllers/serviceaccount_controller_suite_test.go
controllers/svcdiscovery_controller_intg_test.go
controllers/svcdiscovery_controller_suite_test.go
test/helpers/vmware/intg_test_context.go

Manual cherry-pick of #2752 and #2769

[release-1.8] 🐛 controllers: use apireader to not assert on cached information

---

test/infrastructure/vcsim/config/rbac/kustomization.yaml
test/infrastructure/vcsim/config/rbac/leader_election_role.yaml
test/infrastructure/vcsim/config/rbac/leader_election_role_binding.yaml

Add leader election role & role binding to vcsim component yaml

🌱 Add leader election to vcsim component yaml

---

.gitignore
Makefile
test/infrastructure/vm-operator/kustomization.yaml

Usage:
```sh
make release-vm-operator
```
Or to build and push a specific version:
```sh
VM_OPERATOR_VERSION=v1.8.1 make release-vm-operator
```
Outputs:
Multiarch image (`linux/amd64`, `linux/arm64`) at: `https://gcr.io/k8s-staging-capi-vsphere/extra/vm-operator:v1.8.1`
Manifest at: `https://storage.googleapis.com/artifacts.k8s-staging-capi-vsphere.appspot.com/vm-operator/v1.8.1.yaml`
Fixes #

🌱 add make targets to build and push vm operator image for testing purposes

---

Makefile
hack/e2e.sh
internal/test/helpers/vcsim/model.go
test/e2e/config/vsphere.yaml
test/e2e/e2e_setup_test.go
test/e2e/e2e_suite_test.go
test/e2e/quick_start_test.go
test/framework/framework.go
test/framework/ip/addressmanager.go
test/framework/ip/incluster.go
test/framework/ip/noop.go
test/framework/ip/vcsim.go
test/framework/vcsim/server.go
test/framework/vmoperator/vmoperator.go
test/infrastructure/vcsim/api/v1alpha1/envvar_types.go
test/infrastructure/vcsim/api/v1alpha1/vcsim_types.go
test/infrastructure/vcsim/controllers/controlplaneendpoint_controller.go
test/infrastructure/vcsim/controllers/controlplaneendpoint_controller_test.go
test/infrastructure/vcsim/controllers/envvar_controller.go
test/infrastructure/vcsim/controllers/vcsim_controller.go
test/infrastructure/vcsim/controllers/virtualmachine_controller.go
test/infrastructure/vcsim/controllers/virtualmachine_controller_test.go
test/infrastructure/vcsim/controllers/vmbootstrap_controller.go
test/infrastructure/vcsim/controllers/vspherevm_controller.go
test/infrastructure/vcsim/controllers/vspherevm_controller_test.go
test/infrastructure/vcsim/main.go

Add E2E test for vcsim in govmomi mode + one step closer to test supervisor mode

🌱 Implement E2E test for vcsim in govmomi mode

---

pkg/util/networkutil.go
pkg/util/networkutil_test.go

NSX releases can have more than 3 segments. They frequently have 4. This causes an issue when there's an attempt to parse it with the semver package. 
In this PR, if a version with 4 segments is found, it will trim the last segment before parsing it as a semver. The codepath is only there to check that the version is >= 3.0.1 and < 3.1.0 so precision isn't lost by trimming down to 3 segments.

🐛 Fixes issue with NCP versioning while using the semver package

---

test/framework/ip/incluster.go

Finally bumps capi's ipam dependency in test to v1beta1.
We upgraded the ipam provider in the CI cluster which now allows us to do this.
Fixes #

🌱 test: bump ipam to v1beta1

---

Makefile
test/infrastructure/vm-operator/kustomization.yaml
test/infrastructure/vm-operator/vm-operator-replicas.yaml

Improves the vm-operator kustomization which gets used for testing CAPV in supervisor mode.
* Sets number of replicas to 1
* Removes the web-validator deployment which is not relevant for our use case.
Fixes #

🌱 vm-operator: remove web-validator and set replicas to 1

---

go.mod
go.sum
test/go.mod
test/go.sum

Introduces support for sha256 tls thumbprints for vsphere connections.
Related to:
- #2805

🌱 Bump github.com/vmware/govmomi from 0.35.0 to 0.36.1

---

Makefile
test/infrastructure/vcsim/config/rbac/role.yaml

🌱 Fix vcsim role to include permissions for protected endpoints

---

Makefile

Fixes #
Partially solves failing CVE jobs https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/8232381773/job/22509705921

🌱 bump Go version to 1.21.8

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes #
Partially solves failing CVE jobs https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/8232381773/job/22509705921

[release-1.9] 🌱 bump protobuf to v1.33 to fix CVEs

---

Makefile
docs/release/release-tasks.md

🌱 Fix release instructions and release note generation

---

go.mod
go.sum

Fixes #
Partially solves failing CVE jobs [https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/8232381773/jo](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/8232381773/job/22509705921)

[release-1.8] 🌱 bump protobuf -> v1.33 to fix CVEs

---

go.mod
go.sum

Fixes #
Partially solves failing CVE jobs [https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/8232381773/jo](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/8232381773/job/22509705921)

[release-1.7] 🌱  bump protobuf -> v1.33 to fix CVEs

---

go.mod
go.sum

Fixes #
Partially solves failing CVE jobs [https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/8232381773/jo](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/8232381773/job/22509705921)

[release-1.6] 🌱 bump protobuf -> v1.33 to fix CVEs

---

Makefile

🌱 Bump govulncheck to v1.0.4

---

Makefile

Quote from Slack: https://kubernetes.slack.com/archives/CKFGK3SSD/p1710424265062089
Hey folks,
the weekly scan found a few CVEs across all supported CAPV versions. We've fixed those in main / 1.9 / 1.8 / 1.7 by bumping the Go 1.21.8 and to a newer protobuf version.
It was not possible to fix CAPV 1.6 because it is based on Go 1.20. Go 1.20 is out of support and thus there is no patch release to fix the CVE.
We would ignore these CVEs for now as CAPV v1.10 will be released soon (a bit after the next CAPI minor versions). At this point CAPV v1.6 will be out of support and there will be no further patch releases.
If you're affected by these CVE's please consider upgrading to a newer CAPV version. …

[release-1.6] 🌱 Disable govulncheck

---

test/e2e/e2e_setup_test.go
test/e2e/multivc_test.go

🌱 Use ControlPlaneEndpointIPVariable consistently

---

go.mod
go.sum
test/go.mod
test/go.sum

manual bump due to linter issue on https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2838

🌱 Bump github.com/onsi/gomega from 1.31.1 to 1.32.0

---

go.mod
go.sum
test/go.mod
test/go.sum

Manual bump due to linter issue on https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2837

🌱 Bump github.com/onsi/ginkgo/v2 from 2.16.0 to 2.17.0

---

apis/vmware/v1beta1/vspherecluster_types.go
controllers/serviceaccount_controller.go

Ensure entries for ProviderServiceAccount created in the ConfigMap are cleaned up by adding a finalizer on the vSphereCluster
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2845

🐛 Ensure entries for ProviderServiceAccount created in the ConfigMap are cleaned up

---

apis/vmware/v1beta1/vspherecluster_types.go
controllers/serviceaccount_controller.go

[release-1.8] 🐛 Ensure entries for ProviderServiceAccount created in the ConfigMap are cleaned up

---

test/infrastructure/vcsim/controllers/vmbootstrap_controller.go

Ensure a few vcsim logs line are generated only when something happens instead of every reconcile

🌱 Fix noisy logs in vcsim

---

apis/vmware/v1beta1/vspherecluster_types.go
controllers/serviceaccount_controller.go

[release-1.7] 🐛 Ensure entries for ProviderServiceAccount created in the ConfigMap are cleaned up

---

apis/vmware/v1beta1/vspherecluster_types.go
controllers/serviceaccount_controller.go

[release-1.6] 🐛 Ensure entries for ProviderServiceAccount created in the ConfigMap are cleaned up

---

main.go

Part of #2549
Not necessary anymore since https://github.com/kubernetes-sigs/cluster-api/pull/9813/files
Fixes #

🌱 Drop duplicate ClusterCacheTracker log name

---

hack/tools/janitor/janitor.go
pkg/services/govmomi/cluster/vmgroup_test.go
pkg/services/govmomi/create_test.go
pkg/services/govmomi/util.go
test/infrastructure/vcsim/controllers/vmip_controller.go

As per comments in https://github.com/vmware/govmomi/issues/3394, we are going back to use thread-safe functions `task.Wait` and `task.WaitForResult`.
Deprecation notice is going to be removed in a future version of govmomi

🌱 Revert "Replace deprecated wait functions"

---

config/manager/manager.yaml

If set, CCT uses these variables to figure out if it tries to communicate with the cluster it's running on. If that's the case it will use `kubernetes.default.svc` instead of the regular external control plane endpoint
(jut noticed when reading CAPI release notes of the last few years :))
Fixes #

🌱 Add env variables for ClusterCacheTracker

---

controllers/serviceaccount_controller.go
controllers/servicediscovery_controller.go
controllers/vmware/vspherecluster_reconciler.go
controllers/vspherecluster_reconciler.go
controllers/vsphereclusteridentity_controller.go
controllers/vspheredeploymentzone_controller.go
controllers/vspheremachine_controller.go
controllers/vspherevm_controller.go
pkg/services/govmomi/service.go

Improve patch helper error handling, as the patch package has improved to contain related context [here](https://github.com/kubernetes-sigs/cluster-api/pull/9946).
Part of #2549

🌱 Improve patch helper error handling

---

packaging/flavorgen/flavors/clusterclass_generators.go
packaging/flavorgen/flavors/flavors.go
packaging/flavorgen/flavors/generators.go
templates/cluster-template-topology-supervisor.yaml
templates/cluster-template-topology.yaml
templates/clusterclass-template-supervisor.yaml
templates/clusterclass-template.yaml

Refine `make generate-flavors` to not generate unused variables for supervisor mode.
- infraServer
- credsSecretName
Fixes #2829

🌱 Remove infraServer and credsSecretName from supervisor ClusterClass

---

Makefile

Fixes the arguments for release-notes generator which got bumped by bumping the CAPI dependency in Makefile.
* Removes the `--pre-release-version=$(PRE_RELEASE)` argument
* When RELEASE_TAG is a pre-release (contains `-`), then add the `--previous-release-version` argument:
* the previous-release-version gets calculated using the following pipeline
* list all tags (`git tag -l`)
* grep for `.0` releases and releases which are on the same major/minor version as RELEASE_TAG
* sort by version
* return the tag which is in the list right before `RELEASE_TAG`
Fixes #

🌱 Makefile: fix release-notes generator arguments

---

.github/workflows/release.yaml

Changes the github action which creates a draft release to not fail when generating release-notes failed.
Instead it will create the draft release with a note that the release-notes were not successfully generated.
This allows us to still manually generate the release notes and publish the release.
Fixes #

🌱 github: still create a draft release on release notes generation failures

---

config/rbac/role.yaml
controllers/vmware/vspherecluster_reconciler.go
controllers/vspheremachine_controller.go
go.mod
go.sum
pkg/manager/manager.go
pkg/manager/network.go
pkg/services/interfaces.go
pkg/services/network/constants.go
pkg/services/network/dummy_provider.go
pkg/services/network/netop_provider.go
pkg/services/network/network_test.go
pkg/services/network/nsxt_provider.go
pkg/services/network/nsxt_vpc_provider.go
pkg/services/vmoperator/vmopmachine.go
pkg/services/vmoperator/vmopmachine_test.go
test/go.sum

This commit introduces NSX-T Virtual Private Cloud (nsx-vpc) as a new network provider for the vSphere Supervisor Cluster in anticipation of the upcoming vSphere 9 release. Key Changes:
nsx-vpc implemented as a new NetworkProvider using nsx-operator libs.
Skipped VM Readiness check as nsx-vpc offers private network access.
Added unit tests for nsx-vpc network provider.
The vSphere Supervisor Cluster currently accommodates two network types: vSphere Distributed Switch (VDS) and NSX-T network. With the impending release of vSphere 9, a third network type will be introduced: NSX-T Virtual Private Cloud (nsx-vpc). 
To adapt this change,  CAPV need to add support for nsx-vpc  as a new network provider.
**Which issue(s) this PR fixes** *(optional, in …

:sparkles:Add NSX-VPC Network Provider Support

---

Makefile
hack/tools/janitor/janitor.go
hack/tools/janitor/janitor_test.go
hack/tools/janitor/main.go
hack/tools/janitor/vsphere.go

Adds functionality to hack/tools/janitor:
* Delete created child folders (get created during supervisor tests)
* Delete created child resource pools (get created during supervisor tests)
* Unit test coverage for janitor
Fixes #

🌱 hack/tools/janitor also cleanup child resource pools and folders for capv

---

apis/v1beta1/types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
pkg/services/govmomi/pci/device.go

Allow to set custom label for PCI devices.
Fixes #2470

🌱 Allow to set custom label for PCI device

---

Makefile
test/e2e/cluster_upgrade_test.go
test/e2e/config/vsphere.yaml
test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-prekubeadmscript.yaml
test/e2e/data/infrastructure-vsphere-supervisor/main/conformance/kustomization.yaml
test/e2e/data/infrastructure-vsphere-supervisor/main/conformance/worker-node-size.yaml
test/e2e/data/infrastructure-vsphere-supervisor/main/install-on-bootstrap/inject-install-on-bootstrap.yaml
test/e2e/data/infrastructure-vsphere-supervisor/main/install-on-bootstrap/kustomization.yaml
test/e2e/e2e_setup_test.go
test/e2e/k8s_conformance_test.go
test/e2e/quick_start_test.go

Adding more supervisor tests.
At this stage it is just an experiment to figure out how to proceed

🌱 Add more supervisor tests

---

test/e2e/e2e_suite_test.go
test/framework/ip/incluster.go

We have the capv-janitor periodic which cleans up the test environment.
This PR changes the e2e test code to only do a best-effort Teardown of IPAM resources to not fail on otherwise successful tests, and let the janitor handle the at the moment not deletable objects.
xref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/2879/pull-cluster-api-provider-vsphere-e2e-supervisor-conformance-ci-latest-main/1777669997108137984
Fixes #

🌱 test: teardown ipam only on best-effort base to not fail successful tests

---

packaging/flavorgen/flavors/generators.go
packaging/flavorgen/flavors/kubevip/files.go
packaging/flavorgen/flavors/kubevip/kubevip.go
packaging/flavorgen/flavors/kubevip/topology.go
templates/cluster-template-external-loadbalancer.yaml
templates/cluster-template-ignition.yaml
templates/cluster-template-node-ipam.yaml
templates/cluster-template-supervisor.yaml
templates/cluster-template.yaml
templates/clusterclass-template-supervisor.yaml
templates/clusterclass-template.yaml
test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass/patch-prekubeadmscript.yaml
test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-prekubeadmscript.yaml

The k8s v1.28 to v1.29 upgrade tests are currently failing on main and release-1.10, because the `prekubeadmscript.sh` gets run **after** `kube-vip-prepare.sh`. Because of that kube-vip fails on v1.28 and the kube-apiserver's public IP does not get up so provisioning including kubeadm fails.
This PR refactors the way we add additional pre-kubeadm scripts.
It changes the pattern from
* adding a script
* adding a preKubeadmCommand entry which runs the script
to
* adding scripts to `/etc/pre-kubeadm-commands`
* having a static script which runs the scripts inside that directory in alphabetical order
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …

🌱 templates: add a script to run prekubeadmcommands in order of files defined in /etc/pre-kubeadm-scripts

---

main.go

Retry CRD deletion during start-up, so the controller handle nice race conditions but it goes back to crash loopbacking when the issue is more persistent

🌱 Retry CRD detection during startup

---

Makefile
test/e2e/config/vsphere.yaml
test/infrastructure/vm-operator/vm-operator-v1.8.6-0-gde75746a.yaml

🌱 Generate vm-operator YAML instead of downloading it from GCS

---

.github/workflows/weekly-md-link-check.yaml
.github/workflows/weekly-security-scan.yaml
.github/workflows/weekly-test-release.yaml
README.md

CAPV v1.10 is released so we can drop test coverage for v1.6.
Part of #2644
Fixes #

🌱 Drop test coverage for release-1.6 and update README.md

---

README.md

This provides easy reference to developers to familiarize themselves with the types provided by cluster-api-provider-vsphere and the types provided by cluster-api.
Adds links to CRD documentation on doc.crds.dev
This provides easy reference to developers to familiarize
themselves with the types provided by cluster-api-provider-vsphere
and the types provided by cluster-api.

📖  Adds links to CRD documentation on doc.crds.dev

---

.github/workflows/cover.yaml

This only made it into main (before release-1.10 was created)
Fixes #

[release-1.9] 🌱 Drop codecov from PRs

---

Makefile
hack/e2e.sh
test/e2e/clusterctl_upgrade_test.go
test/e2e/config/vsphere.yaml
test/e2e/data/infrastructure-vsphere-govmomi/main/remote-management/image-injection.yaml
test/e2e/data/infrastructure-vsphere-govmomi/main/remote-management/kustomization.yaml
test/framework/daemonset_helpers.go
test/framework/image_preloading.go
test/go.mod

Removes pushing the images to gcloud and instead uses a daemonset and streams the image tarball via kubectl exec.
Fixes #

🌱 test: use a daemonset and kubectl exec to provide images to remote clusters

---

pkg/session/session.go

PR #2530 introduced additional logouts to avoid session leaks. Unfortunately we realized later that this leads to more deadlocks.
Notes
* v1.11: keep alive handler has been removed
* v1.10 keep alive handler is disabled per default
* v1.9-v1.7: keep alive handler is enabled per default
*  in v1.10 and removed in v1.11
In general, the recomendation is to disable the keep alive handler in v1.10-v1.7. For folks that have it still enabled, this PR tries to remove the deadlock issue.
Fixes #

[release-1.10] 🐛 Remove logouts in keep alive handlers

---

hack/e2e.sh

🌱 hack: remove references to GCR_KEY_FILE

---

controllers/serviceaccount_controller_intg_test.go
controllers/servicediscovery_controller_intg_test.go
internal/test/helpers/vmware/intg_test_context.go

This PR changes the controllers tests for serviceaccount_controller and servicediscovery_controller to only create the objects which are required, instead of creating all and deleting the ones not required.
This solves a race condition for the serviceaccount_controller related test cases for the following cases:
* https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/controllers/serviceaccount_controller_intg_test.go#L130
* https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/controllers/serviceaccount_controller_intg_test.go#L156
In case of this tests, the serviceaccount_controller could already have reconciled once successfully and added a successful `ProviderServiceAccountsReadyCondition` before the tests …

🌱 controllers: fix ProviderServiceAccount tests to create objects on-demand

---

pkg/session/session.go

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2987
Fixes #

[release-1.7] 🐛 Remove logouts in keep alive handlers

---

hack/e2e.sh

Improves our censoring in e2e.sh to:
* not add binary files (e.g. gzipped files) to the output artifacts because we can't control their data
* also censor the base64 version of our secret
Fixes #

🌱 hack/e2e don't add binary files to artifacts and also censor base64 encoded values

---

.github/ISSUE_TEMPLATE/release_tracking.md
docs/release/release-tasks.md

First try to add some docs around this. Let's try to incrementally improve
Fixes #

📖 Document Kubernetes bump

---

pkg/session/session.go

Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2987
Fixes #

[release-1.8] 🐛 Remove logouts in keep alive handlers 

---

Makefile
hack/verify-go-directive.sh

🌱 add `Go` directive check as `Makefile` target

---

Makefile

Manual cherry-pick of #3016
Fixes #

[release-1.7] 🌱 Use setup-envtest from CR main (05/2024) to use envtest binaries from CT releases

---

Makefile

Manual cherry-pick of #3016
Fixes #

[release-1.8] 🌱 Use setup-envtest from CR main (05/2024) to use envtest binaries from CT releases

---

Makefile

Manual cherry-pick of #3016
Fixes #

[release-1.9] 🌱 Use setup-envtest from CR main (05/2024) to use envtest binaries from CT releases

---

Makefile

Manual cherry-pick of #3016
Fixes #

[release-1.10] 🌱 Use setup-envtest from CR main (05/2024) to use envtest binaries from CT releases

---

controllers/vmware/test/controllers_suite_test.go
controllers/vmware/test/controllers_test.go
internal/test/helpers/webhook.go

We are running multiple managers in supervisor tests. If all of them are trying to serve webhook son the same port the tests will fail, e.g.: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-vsphere-test-main/1793553292249272320
This PR ensures that we only run one manager with webhooks.
Fixes #

🐛 Run only one manager with webhooks for supervisor tests

---

Makefile

See https://github.com/kubernetes-sigs/cluster-api/pull/10569 for context
Fixes #

🌱 Use setup-envtest from CR main (05/2024) to use envtest binaries from CT releases

---

Makefile

let's fix some CVE findings: https://github.com/sbueringer/cluster-api-provider-vsphere/actions/runs/9448371935/job/26022229717
Fixes #

🌱 Bump Go to 1.21.9

---

packaging/flavorgen/flavors/crs/cpi.go
packaging/flavorgen/flavors/util/helpers.go
templates/cluster-template-external-loadbalancer.yaml
templates/cluster-template-ignition.yaml
templates/cluster-template-node-ipam.yaml
templates/cluster-template-supervisor.yaml
templates/cluster-template-topology-supervisor.yaml
templates/cluster-template-topology.yaml
templates/cluster-template.yaml
templates/clusterclass-template-supervisor.yaml
templates/clusterclass-template.yaml

… be set as string in templates
Setting a password like `VSPHERE_PASSWORD: "[][xxxxxxx"` toherwise failed due to the following error:
```
Error: failed to parse yaml: failed to unmarshal the 9th yaml document: "apiVersion: v1\nkind: Secret\nmetadata:\n  name: 'test'\n  namespace: 'test'\nstringData:\n  password: [][xxxxxxx\n  username: admin\n": error converting YAML to JSON: yaml: line 6: did not find expected key
```
xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1717005276084809
Fixes #

🌱 flavorgen: enforce VSPHERE_USERNAME and VSPHERE_PASSWORD variables to be set as string in templates

---

cloudbuild-nightly.yaml
cloudbuild.yaml

This should fix https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-cluster-api-provider-vsphere-push-images/1800527833475321856
Fixes #

🌱 cloudbuild: bump images to match capi

---

hack/e2e.sh
test/e2e/config/vsphere-ci.yaml

Manual, minimal cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3034
Fixes #

[release-1.9] ✨ test/e2e: use vSphere projects from Boskos

---

test/e2e/config/vsphere.yaml

Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/3046

🌱 Drop pre-load of cert-manager images in E2E tests

---

Makefile
docs/development.md

Some cleanup to our Makefile to drop:
* Variable `VERSION` (only used for `OVERRIDES_DIR`)
* Variable `OVERRIDES_DIR`
* Make targets which did use `OVERRIDES_DIR`:
* `dev-manifests`: generated manifests and copied them to `$HOME/.cluster-api/overrides/infrastructure-vsphere/...`
* `dev-flavors`: generated flavors and copied them to `$HOME/.cluster-api/overrides/infrastructure-vsphere/...`
Folks should use tilt instead which also allows to add the templates directory to tilt.
Fixes #

🌱 Makefile: drop OVERRIDES_DIR and dependent make targets

---

test/e2e/config/vsphere.yaml
test/e2e/data/infrastructure-vsphere-govmomi/main/install-on-bootstrap/kustomization.yaml
test/e2e/data/infrastructure-vsphere-govmomi/main/install-on-bootstrap/set-md-rollout-strategy.yaml
test/e2e/data/infrastructure-vsphere-supervisor/main/install-on-bootstrap/kustomization.yaml
test/e2e/data/infrastructure-vsphere-supervisor/main/install-on-bootstrap/set-md-rollout-strategy.yaml

This speeds up the K8s-Upgrade tests by changing the rolloutStrategy for MachineDeployments in the used `install-on-bootstrap` flavor.
This test uses 5 replicas for the machine deployment which makes the test currently flaky by reaching the 15mins timeout.
Fixes #

🌱 test: use rolloutStrategy to speed up K8s-Upgrade tests to not hit rollout timeout

---

test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/e2e/data/infrastructure-vsphere/main/install-on-bootstrap/kustomization.yaml
test/e2e/data/infrastructure-vsphere/main/install-on-bootstrap/set-md-rollout-strategy.yaml

🌱 [release-1.9] test: use rolloutStrategy to speed up K8s-Upgrade tests to not hit rollout timeout

---

.github/dependabot.yml

🌱 Sync dependabot config with core CAPI

---

docs/getting_started.md
test/infrastructure/vcsim/controllers/vcsim_controller.go

sha1 support for certificates gets removed in Go 1.24 ([xref](https://github.com/golang/go/issues/62048)).
Due to its insecurity we should also use sha256 for thumbprints to ensure this works.
Note: govmomi directly verifies the thumbprint and does not use the library for it, so its not going to break with v1.24.
Fixes #

🌱 use sha256 thumbprint in tests

---

.golangci.yml
Makefile
hack/ensure-go.sh
hack/utils.sh

Bumps to Go 1.22 to stay on a supported Go version
Fixes #

[release-1.10] ✨ Bump to Go 1.22.4 

---

.golangci.yml
Makefile
hack/ensure-go.sh
hack/utils.sh

Bumps to Go 1.22 to stay on a supported Go version
Fixes #

[release-1.9] ✨ Bump to Go 1.22.4

---

.golangci.yml
Makefile
hack/ensure-go.sh
hack/utils.sh

Bumps to Go 1.22 to stay on a supported Go version
Fixes #

[release-1.8] ✨ Bump to Go 1.22.4

---

Makefile

Pins the go version used to compile controller-gen to 1.21 since we are using controller-gen < 0.14 and go >= 1.22.
controller-gen < 0.13 is incompatible to go >= 1.22 and would panic.
Fixes #

[release-1.10] 🌱 Makefile: pin controller-gen binary to go 1.21

---

go.mod
go.sum

Required for using sha256 thumbprints in CI.
Fixes #

[release-1.7] 🌱 Bump govmomi to 0.37.0 for sha256 support

---

go.mod
go.sum
test/go.mod
test/go.sum

Required for using sha256 thumbprints in CI.
Fixes #

[release-1.9] 🌱 Bump govmomi to 0.37.0 for sha256 support

---

go.mod
go.sum

Required for using sha256 thumbprints in CI.
Fixes #

[release-1.8] 🌱 Bump govmomi to 0.37.0 for sha256 support

---

controllers/vmware/test/controllers_test.go

🌱 controllers: add unit test coverage for esxi host label on supervisor

---

Makefile

🌱 Bump to Go 1.21.12

---

Makefile

1.0.0 is not compatible with Go 1.22, 1.0.1 is
Fixes #

[release-1.8] 🌱 Bump govulncheck to 1.0.1

---

test/e2e/quick_start_test.go

Adds a check to the basic PR-Blocking test to check if all pods (e.g. CSI) are running.
Fixes #

🌱  test: implement check for all pods running

---

test/e2e/e2e_suite_test.go
test/framework/vcsim/server.go

The upper timeout was 30s and the inner retry also 30s leading to not actually doing a retry.
Fixes #

🌱 test: allow retries creating vcsim

---

test/e2e/config/vsphere.yaml
test/e2e/e2e_setup_test.go

🌱 test: fix wording in vsphere.yaml comment, always use bootstrapClusterProxy to get vCenterSimulator

---

apis/v1beta1/types.go
docs/gpu-vgpu.md
internal/webhooks/vspheremachine.go

✨ vGPU implementation - follow-ups

---

pkg/services/vmoperator/vmopmachine.go

This PR surfaces more conditions about VirtualMachine pre-prequisites; this can help triaging VirtualMachine not coming up

🌱 Surface more conditions about VirtualMachine pre-prequisites

---

pkg/services/vmoperator/vmopmachine.go

Fixes nil pointer occured in unit test: 
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/3109/pull-cluster-api-provider-vsphere-test-main/1813959719862145024
Fixes #

🐛 vmoperator: fix nil pointer when reconciling VM

---

test/e2e/config/vsphere.yaml

To get `periodic-e2e-supervisor-main-1-29-1-30` back green ([xref testgrid](https://testgrid.k8s.io/vmware-cluster-api-provider-vsphere#periodic-e2e-supervisor-main-1-29-1-30))
Via having:
- https://github.com/kubernetes-sigs/cluster-api/pull/10903
In the used CAPI controller image.
Also to deflake `periodic-e2e-govmomi-main-1-30-1-31` ([xref testgrid](https://testgrid.k8s.io/vmware-cluster-api-provider-vsphere#periodic-e2e-govmomi-main-1-30-1-31))
Fixes #

🌱 test: bump core-CAPI v1.8.0-beta.0 to nightly image build

---

test/e2e/anti_affinity_test.go
test/e2e/clusterctl_upgrade_test.go
test/e2e/data/infrastructure-vsphere-govmomi/v1.9/clusterclass/clusterclass-quick-start.yaml
test/e2e/data/infrastructure-vsphere-govmomi/v1.9/topology/cluster-template-topology.yaml
test/e2e/data/infrastructure-vsphere-govmomi/v1.9/topology/kustomization.yaml
test/e2e/data/infrastructure-vsphere-govmomi/v1.9/topology/workload-control-plane-port.yaml
test/e2e/dhcp_overrides_test.go
test/e2e/e2e_setup_test.go
test/e2e/e2e_suite_test.go
test/e2e/gpu_pci_passthrough_test.go
test/e2e/hardware_upgrade_test.go
test/e2e/multivc_test.go
test/e2e/node_labeling_test.go
test/e2e/ownerrefs_finalizers_test.go
test/e2e/storage_policy_test.go

🌱 test: enable vcsim to run clusterctl upgrade e2e tests

---

test/e2e/ownerrefs_finalizers_test.go

xref: https://storage.googleapis.com/k8s-triage/index.html?text=Resource%20versions%20didn%27t%20stay%20stable&job=.*-cluster-api-provider-vsphere.*
TLDR:
* resource version is sometimes not stable for machines
* reason for that is that while its expected to be stable, the node gets healthy (because CNI finished to start)
* this leads to an update of the machine's status
Fixes #

🌱 test: wait for nodes being ready before testing resource versions being stable

---

config/deployments/integration-tests/README.md
config/deployments/integration-tests/crds/topology.tanzu.vmware.com_availabilityzones.yaml
controllers/vmware/vspherecluster_reconciler.go
controllers/vmware/vspherecluster_reconciler_test.go

🌱 Drop WCP fault domains feature gate

---

controllers/vspherecluster_reconciler_test.go
internal/test/helpers/envtest.go

Fixes test flake:
https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-provider-vsphere.*&xjob=.*-exp-.*#e61449f7544d59f42549
* Old test deleted the VSphereFailureDomain.
* New test wanted to create VSphereFailureDomain with same name again, but its still in deleting.
Fixes #

🌱 Fix flake where VSphereFailureDomain still exists from previous test

---

test/e2e/clusterctl_upgrade_test.go
test/e2e/config/vsphere-ci.yaml
test/e2e/config/vsphere-dev.yaml
test/integration/integration-dev.yaml

Bumps CAPV to the latest v1.8.10 for upgrade tests, otherwise it fails using the SHA256 thumbprint.
Fixes #

🌱 [release-1.9] Bump CAPV to from v1.8.10 and v1.7.7 for upgrade tests

---

test/e2e/cluster_upgrade_runtimesdk_test.go
test/e2e/ownerrefs_finalizers_test.go

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/3119/pull-cluster-api-provider-vsphere-e2e-supervisor-main/1815834140377878528
Fixes #

🌱 test: dump resources before ValidateResourceVersionStable test

---

controllers/controllers_suite_test.go
controllers/serviceaccount_controller.go
controllers/serviceaccount_controller_intg_test.go
controllers/servicediscovery_controller_intg_test.go
controllers/vspherecluster_reconciler_test.go
internal/test/helpers/envtest.go

This PR should:
* make it easier to debug unit tests by increasing log level to 5, like
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-vsphere-test-main/1817859752558858240
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-vsphere-test-main/1817874852074229760
* fix https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-vsphere-test-main/1817981442076971008
Fixes #

 🐛 Fix unit tests, improve debuggability

---

config/default/crd/patches/webhook_in_vsphereclusters.yaml
config/default/crd/patches/webhook_in_vsphereclustertemplates.yaml
config/default/crd/patches/webhook_in_vspheredeploymentzones.yaml
config/default/crd/patches/webhook_in_vspherefailuredomains.yaml
config/default/crd/patches/webhook_in_vspheremachines.yaml
config/default/crd/patches/webhook_in_vspheremachinetemplates.yaml
config/default/crd/patches/webhook_in_vspherevms.yaml

Context: https://github.com/kubernetes-sigs/cluster-api/pull/10972
Fixes #

🐛 Drop caBundle from CRDs to support Kubernetes 1.31

---

controllers/serviceaccount_controller_intg_test.go
controllers/servicediscovery_controller_intg_test.go

xref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-vsphere-test-main/1818498689912541184
Fixes #

🌱 Improve checking if guest cluster client works in unit tests

---

hack/ci-e2e-lib.sh
hack/e2e.sh
test/e2e/config/vsphere.yaml
test/framework/framework.go

* Introduces e2e variable `KUBERNETES_VERSION_MANAGEMENT` analog to CAPI
* Adds scripts (synced from capi) to build the kindest/node image for `KUBERNETES_VERSION_MANAGEMENT` if needed
TODO:
Fixes #

🌱 e2e: introduce and use KUBERNETES_VERSION_MANAGEMENT variable which builds kindest/node image on demand

---

test/framework/log/collector.go

We may use a naming strategy in e2e tests for creating VirtualMachines. For them we can't just use the machine name to find the vm in vsphere to collect logs.
Fixes #

🌱 test: ensure we can collect machine logs

---

packaging/flavorgen/flavors/generators.go
templates/cluster-template-ignition.yaml
test/framework/log/collector.go

Debatable if we want to have this. It was handy for debugging. Cloud-init does it simiarily.
/hold
Fixes #

🌱 packaging: write kubeadm script log for ignition

---

README.md

📖 README.md: add information about v1.31.0 OVA's

---

.github/workflows/pr-md-link-check.yaml

[release-1.11] 🌱 Set base branch correctly for link checker

---

test/extension/handlers/topologymutation/handler.go

This was missed in #3156
Fixes #

🌱 test: use ubuntu 24.04 in Runtime SDK test

---

.golangci.yml
config/rbac/role.yaml
controllers/vmware/vspherecluster_reconciler.go
go.mod
go.sum
pkg/manager/manager.go
pkg/services/network/constants.go
pkg/services/network/network_test.go
pkg/services/network/nsxt_vpc_provider.go
test/go.sum

In the VPC network, the vm-operator Pod and Kubernetes Clusters are in different VPCs. TCP readiness probe does not work across VPC so use LB 's healthcheck instead. This annotation is agnostic to LB providers. NSX LB supports it to enable healthcheck while AVI LB has healthcheck enabled by default. vm-operator will propagate this annotation to Service annotation.
Fixes #

✨ Enable NSX LB healthcheck on kube-apiserver

---

controllers/vspherecluster_reconciler_test.go

Two small fixes:
- The secret was created with an OwnerReference. Later on (line ~141) it is checked if the controller sets the OwnerReference by counting the number of OwnerReferences. However, this is always > 0 since the OwnerReference was explicitly set before, so this check always passes. Removed the initial OwnerReference and counting the ones set by the controller.
- Line ~237 it is stated: "should remove vspherecluster finalizer if the secret does not exist". However, it was not checked whether the Finalizers are actually empty. Added this check.

🐛 Small test fix. Remove OwnerReference & Check for Finalizers being empty

---

controllers/vmware/controllers_suite_test.go
controllers/vmware/serviceaccount_controller.go
controllers/vmware/serviceaccount_controller_intg_test.go
controllers/vmware/serviceaccount_controller_suite_test.go
controllers/vmware/serviceaccount_controller_unit_test.go
controllers/vmware/servicediscovery_controller.go
controllers/vmware/servicediscovery_controller_intg_test.go
controllers/vmware/servicediscovery_controller_suite_test.go
controllers/vmware/servicediscovery_controller_unit_test.go
controllers/vmware/test/controllers_suite_test.go
controllers/vmware/vspherecluster_reconciler_test.go
controllers/vspherecluster_controller.go
main.go

🌱 Move ProviderServiceAccount & ServiceDiscovery controller to supervisor package

---

test/e2e/data/infrastructure-vsphere-govmomi/main/ownerrefs-finalizers/kustomization.yaml
test/e2e/data/infrastructure-vsphere-govmomi/main/ownerrefs-finalizers/vspherecluster-failuredomainselector.yaml
test/e2e/ownerrefs_finalizers_test.go
test/infrastructure/vcsim/controllers/envvar_controller.go
test/infrastructure/vcsim/controllers/vcsim_controller.go

🌱 test: check failureDomains on VSphereCluster in e2e test

---

go.mod
go.sum
test/go.mod
test/go.sum

CI automatically uses CAPI v1.8.2 which lead to failures and requires e2e fixes from:
https://github.com/kubernetes-sigs/cluster-api/pull/11136/files#diff-ddb199a962dbc0b01aef54bdb65e0375a2ed58262d0b5999d50c7e70596496b5
Fixes #

🌱 Bump sigs.k8s.io/cluster-api to v1.8.2

---

packaging/flavorgen/cloudprovider/csi/vsphere-csi-driver.yaml
templates/cluster-template-external-loadbalancer.yaml
templates/cluster-template-ignition.yaml
templates/cluster-template-node-ipam.yaml
templates/cluster-template-supervisor.yaml
templates/cluster-template-topology-supervisor.yaml
templates/cluster-template-topology.yaml
templates/cluster-template.yaml
test/e2e/data/infrastructure-vsphere-govmomi/v1.10/topology/cluster-template-topology.yaml
test/e2e/data/infrastructure-vsphere-govmomi/v1.11/topology/cluster-template-topology.yaml
test/e2e/data/infrastructure-vsphere-govmomi/v1.9/topology/cluster-template-topology.yaml
test/e2e/data/infrastructure-vsphere-supervisor/v1.10/topology/cluster-template-topology-supervisor.yaml
test/e2e/data/infrastructure-vsphere-supervisor/v1.11/topology/cluster-template-topology-supervisor.yaml
test/e2e/data/infrastructure-vsphere-supervisor/v1.9/topology/cluster-template-topology-supervisor.yaml

🌱 csi: use images from new location

---

hack/create-mirror-repository-pr.sh

Until the e2e CI is migrated to community infra, this script will be useful for all PR authors to create a PR in the mirror repo and run the CI there.
please suggest a better script name if needed.
NONE

🌱 hack: add script for creating mirror repo PRs

---

Makefile

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-cluster-api-provider-vsphere-push-images 
is broken since merging:
- #3233 
log says:
```
mkdir -p out/
cd packaging/flavorgen; go build -o flavorgen ./
go: ../go.mod requires go >= 1.22.7 (running go 1.22.0; GOTOOLCHAIN=local)
make[2]: *** [Makefile:793: generate-flavors] Error 1
```
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-cluster-api-provider-vsphere-push-images/1849761049792745472
This sets GOTOOLCHAIN=auto for buiilding flavorgen which should make go auto-download a good version.
Alternative: bumping [gcr.io/k8s-staging-test-infra/gcb-docker-gcloud](http://gcr.io/k8s-staging-test-infra/gcb-docker-gcloud) in cloudbuild-nightly.yaml and cloudbuild.yaml does not work because …

🌱 Makefile: set GOTOOLCHAIN=auto for generate-flavors to make it work in cloudbuild

---

pkg/services/govmomi/power.go
pkg/services/govmomi/service.go
pkg/services/govmomi/util.go
pkg/services/govmomi/vcenter/clone.go

During the "context" usage refactoring, we have missed the error return messages/fields.
This way the return of an error message was containing the "context" field, and not the real "Virtual Machine context" (which is a stringer).

:seedling: Fix return messages to contain proper VM information

---

hack/verify-container-images.sh

This was done a while ago in CAPI to keep this working. Let's do the same now in CAPV
xref: https://github.com/sbueringer/cluster-api-provider-vsphere/actions/runs/11554091887
Fixes #

🌱 Switch to using ECR mirror for trivy DB repo

---

pkg/util/constants.go
pkg/util/machines_test.go

**What this PR does / why we need it**: 
On some networks IPv6 is announced via RA. Networkd (and maybe netplan) separates DHCPv6 and RA enablement, meaning that even when users set to ignore/disable DHCPv6, IPv6 is still configured on the Host VM if there is some Route Advertisement for IPv6. 
Turns out on some setups this may break the desired behavior, as DNSv6 and others may also end up being configured on the node using IPv6.
This PR intends to do the following changes:
* Organize cloud-init template to separate DHCPv, DHCPv6 and override flags as they are independent
* Configure cloud-init to pass accept-ra. This enforcement needs cloud-init on at least version 24.2 (see https://github.com/canonical/cloud-init/pull/4928 and https://github.com/canonical/cloud-init/pull/5060)

:bug: Proper ignore IPv6 announcements when IPv6 is not requested

---

apis/v1alpha3/conversion_test.go
apis/v1alpha3/zz_generated.conversion.go
apis/v1alpha4/conversion_test.go
apis/v1alpha4/zz_generated.conversion.go
apis/v1beta1/vspherecluster_types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
controllers/vspherecluster_reconciler.go
controllers/vspherevm_controller.go

What this PR does:
The cluster module is currently enabled for all vSphere clusters based on the anti-affinity feature flag, with no option to disable its creation if the user doesn't want this feature. This PR introduces a DisableClusterModule field to the vSphereCluster API, allowing users to control the creation of a cluster module. However, this field is only applicable when the NodeAntiAffinity feature flag is enabled; otherwise, it is ignored.

✨ enables explicit disabling of cluster module

---

.golangci.yml
controllers/controllers_suite_test.go
controllers/vmware/controllers_suite_test.go
controllers/vmware/serviceaccount_controller.go
controllers/vmware/serviceaccount_controller_intg_test.go
controllers/vmware/servicediscovery_controller.go
controllers/vmware/servicediscovery_controller_intg_test.go
controllers/vspherevm_controller.go
controllers/vspherevm_controller_test.go
internal/test/helpers/vmware/intg_test_context.go
main.go
pkg/context/fake/fake_controller_manager_context.go

Removes usage of the deprecated remote.ClusterCacheTracker and related functions.
Fixes #

🌱 Replace CAPI's clustercache tracker by the new clustercache

---

apis/v1beta1/types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
pkg/context/fake/fake_vm_context.go
pkg/services/govmomi/create_test.go
test/e2e/e2e_setup_test.go
test/e2e/quick_start_test.go
test/infrastructure/vcsim/api/v1alpha1/envvar_types.go
test/infrastructure/vcsim/config/crd/bases/vcsim.infrastructure.cluster.x-k8s.io_envvars.yaml
test/infrastructure/vcsim/controllers/envvar_controller.go
test/infrastructure/vcsim/controllers/vspherevm_controller.go

**What this PR does / why we need it**: Allow users passing MOID as part of the spec
In some cases, passing the name of an object may not be enough. There may be disambiguation problems on name usage, or special characters that are accepted by vSphere but not properly encoded to be used during VM provisioning.
This change allows users that can rely on passing MOID  (eg.: automation, terraform, vSphere UI) to pass the MOID of an object instead of passing the canonical name
Note: This change doesn't cover yet Network Name and the Failure Domain fields, that can be either covered by this same change, or on a follow up PR.

:sparkles: Allow using moid

---

.github/workflows/pr-md-link-check.yaml

Part of 1.12-rc.0 release tasks

[release-1.12] 🌱 Set base branch correctly for link checker

---

Makefile
go.mod
go.sum
packaging/go.mod
packaging/go.sum
test/e2e/config/vsphere.yaml
test/e2e/node_drain_test.go
test/go.mod
test/go.sum

* Adds the node drain e2e test from CAPI
* Adds functions to also cover waiting for volumes blocked by csi
Fixes #

🌱 e2e: add NodeDrain e2e test

---

test/e2e/node_drain_test.go

Missed this commit when cherry-picking #3278 
Fixes #

🌱 [release-1.12] test: drop PR-Blocking from node drain test

---

test/e2e/config/vsphere.yaml

Bumps kubernetes to v1.32.0-rc.1
Fixes #

🌱 Bump kubernetes release to v1.32.0-rc.1

---

controllers/vspherevm_controller.go

Makes the best-effort node-deletion to not cause infinite requeue when there is no connection to the workload cluster.
Bug was introduced in:
- #3236
Note: this only affected pre-releases of v1.12 prior to this commit.
If kubeadm init failed, this would have lead to CAPV always requeue and never remove the finalizer. So deletion would have been stuck.
Fixes #

🐛 vspherevm: don't requeue on deletenode when there is no ClusterCache connection

---

README.md

📖 README: add links to Kubernetes v1.32 OVA's and document version support for CAPI v1.9

---

go.mod
go.sum
packaging/go.mod
packaging/go.sum
test/go.mod
test/go.sum

To fix: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/12546218303/job/34981686966
Fixes #

🌱 Bump golang.org/x/net to v0.33.0

---

Makefile

We use go 1.23, that needs a newer govulncheck version to work.
Fixes #

🌱 Bump govulncheck to v1.1.4

---

apis/v1beta1/types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
docs/proposal/20241003-data-disk-support.md
pkg/services/govmomi/vcenter/clone.go
pkg/services/govmomi/vcenter/clone_test.go
test/e2e/data/infrastructure-vsphere-govmomi/main/multi-disk/data-disks-patch.yaml
test/e2e/multi_disk_test.go

The current implementation of the data disk feature for creating additional disks on a VirtualMachine dynamically is currently coded to create each disk as a thin provisioned disk.  This may not be suitable for all scenarios.  Administators may require the full disk be allocated (and possibly zeroed out).  This PR is adding a new field to allow the administrators to create data disk that is either: 
- Thin Provisioned
- Thick Provisioned
- EagerlyZeroed
- Left unset to follow the rest of the cloning process
Fixes #

:sparkles: Add ability to configure data disk provision type during clone

---

controllers/controllers_suite_test.go
controllers/vmware/controllers_suite_test.go
controllers/vmware/serviceaccount_controller_intg_test.go
controllers/vmware/serviceaccount_controller_unit_test.go
controllers/vmware/servicediscovery_controller_intg_test.go
controllers/vmware/servicediscovery_controller_unit_test.go
internal/test/helpers/envtest.go
internal/test/helpers/webhook.go

Follow-up from bumping due to clustercache changes in https://github.com/kubernetes-sigs/cluster-api/pull/11757
This should get the unit tests back to green.
/assign @sbueringer
/assign @fabriziopandini 
The tests in:
* `controllers/vmware/serviceaccount_controller_intg_test.go`
* `controllers/vmware/servicediscovery_controller_intg_test.go`
Have a special requirement: They require an additional kube-apiserver instance to simulate the workload cluster.
To be able to properly shutoff this kube-apiserver instance (including etcd) we need to stop the clustercache.
This was only possible at the very end of the whole test suite to not break other tests.
Instead now these two test suites get their own management cluster including clustercache controller …

🌱 test: shutdown clustercache when ctx is done

---

go.mod
go.sum
packaging/go.mod
packaging/go.sum
test/e2e/cluster_upgrade_runtimesdk_test.go
test/e2e/cluster_upgrade_test.go
test/e2e/clusterctl_upgrade_test.go
test/e2e/common.go
test/e2e/config/vsphere.yaml
test/e2e/dhcp_overrides_test.go
test/e2e/e2e_setup_test.go
test/e2e/e2e_suite_test.go
test/e2e/gpu_pci_passthrough_test.go
test/e2e/hardware_upgrade_test.go
test/e2e/k8s_conformance_test.go
test/e2e/multivc_test.go
test/e2e/scale_test.go
test/e2e/storage_policy_test.go
test/framework/framework.go
test/go.mod
test/go.sum

Bump is required to have https://github.com/kubernetes-sigs/cluster-api/pull/11798
Variable renaming was due to CAPI PR https://github.com/kubernetes-sigs/cluster-api/pull/11743
Fixes #

🌱 test: enable upgrades for scale-test and bump CAPI to d5158c2503c84bcf2fc35cf463fca486892b5fae

---

docs/proposal/20241003-data-disk-support.md
test/e2e/data/infrastructure-vsphere-govmomi/main/multi-disk/data-disks-patch.yaml

Noticed that e2e tests are red.
We did not rename all fields when finishing https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3332 .
That resulted in the applied files to have `provisioningType` which is a not existing field and got dropped.
Fixes #

🌱 e2e: fix provisioningMode in tests

---

go.sum
hack/tools/boskosctl/main.go
hack/tools/janitor/main.go
hack/tools/pkg/janitor/janitor.go
hack/tools/pkg/janitor/janitor_test.go
hack/tools/pkg/janitor/vsphere.go
test/e2e/node_drain_test.go

Adds cleanup of CNS volumes which are currently only created during node-drain tests.
Fixes #

🌱 e2e: properly label and cleanup created PVCs during e2e tests in prow

---

packaging/flavorgen/flavors/generators.go
templates/cluster-template-external-loadbalancer.yaml
templates/cluster-template-ignition.yaml
templates/cluster-template-node-ipam.yaml
templates/cluster-template-supervisor.yaml
templates/cluster-template.yaml
templates/clusterclass-template-supervisor.yaml
templates/clusterclass-template.yaml

xref: https://github.com/kubernetes/kubernetes/pull/130162
Without this, the templates used (also in CI) set the flag `--cloud-provider=external`, leading to apiserver not starting due to unknown flag.
Fixes #

🌱 templates: remove cloud-provider flag for kube-apiserver due to removal in v1.33

---

Makefile

Deletes the file `test/framework/log/collector.go` while running govulncheck.
We on purpose ignore this vulnerability because bumping to `golang.org/x/crypto@v0.35.0` would require us to also bump transitively to Go 1.23 in our go.mod file which would be a breaking change.
The vulnerability only affects test code.
Fixes #

[release-1.12] 🌱 Makefile: drop test file to ignore ssh vulnerability in test code

---

controllers/vmware/vspheremachinetemplate_controller.go

```
E0307 10:18:06.090143       1 controller.go:316] "Reconciler error" err="failed to get VirtualMachineClass \"\" for VSphereMachineTemplate: VirtualMachineClass.vmoperator.vmware.com \"\" not found" controller="vspheremachinetemplate" controllerGroup="vmware.infrastructure.cluster.x-k8s.io" controllerKind="VSphereMachineTemplate" VSphereMachineTemplate="vksns303/tkc-md-v3.2.0" namespace="vksns303" name="tkc-md-v3.2.0" reconcileID="18bc210a-a59f-47d3-bfe9-4ef76cac3349"
```
Prevents the above error which could e.g. happen for VSphereMachineTemplates which are referenced by a ClusterClass.
Fixes …

🌱 vspheremachinetemplate: don't reconcile if className is not set

---

main.go

🌱 Align CRD migration flag to core CAPI

---

main.go
test/extension/main.go
test/infrastructure/net-operator/main.go
test/infrastructure/vcsim/main.go

🌱 Log version directly on controller startup

---

test/e2e/config/vsphere.yaml

Part of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/3307

🌱 Bump Kubernetes version used for testing to v1.33.0-beta.0

---

apis/v1beta1/vsphereclusteridentity_types.go
apis/v1beta1/vspheredeploymentzone_types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusteridentities.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheredeploymentzones.yaml
controllers/vsphereclusteridentity_controller.go
controllers/vspheredeploymentzone_controller.go
controllers/vspheredeploymentzone_controller_domain.go
pkg/context/vspheredeploymentzone_context.go

Part of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/3221
Fixes #

🌱 vspheredeploymentzone/vsphereclusteridentity: implement v1beta2 conditions, govmomi

---

Makefile
go.mod
go.sum
main.go
packaging/go.mod
packaging/go.sum
test/e2e/config/vsphere.yaml
test/go.mod
test/go.sum

Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/11991
Fixes #3407

✨ Improve CRD migration & bump to CAPI release-1.10 (19th March)

---

controllers/vmware/servicediscovery_controller.go
controllers/vmware/servicediscovery_controller_suite_test.go
test/framework/vmoperator/vmoperator.go
test/infrastructure/vcsim/config/rbac/role.yaml
test/infrastructure/vcsim/controllers/vmip_controller.go
test/infrastructure/vcsim/controllers/vmoperatordependencies_controller.go
test/infrastructure/vcsim/main.go

Fixes red e2e tests (especially around upgrades).
Error is/was:
```
* ServiceDiscoveryReady: failed to create or patch service Endpoints: Endpoints "supervisor" is   
invalid: [subsets[0].addresses[0].ip: Invalid value: "": must be a valid IP address, (e.g.      
10.9.8.7 or 2001:db8::ffff), subsets[0].addresses[0].ip: Invalid value: "": must be a valid IP  
address]                                                                                        
```
Fixes #

🌱 e2e: servicediscovery controller to have an ip to discover in tests

---

pkg/services/vmoperator/control_plane_endpoint.go
pkg/services/vmoperator/control_plane_endpoint_test.go

This allows creating clusters on supervisor having a name > 41 characters. Before this change the VirtualMachineService was exceeding the name length limit of 63 and thus never got created.
The code falls back to the legacy name if there is no VirtualMachineService found.
Supersedes #3413 
Fixes #

🌱 supervisor: create the VirtualMachineService for the control plane without a name suffix

---

test/e2e/config/vsphere.yaml

Keep up with K8s releases
/cherry-pick release-1.13
/hold for CI

🌱 Bump to Kubernetes v1.33.0-rc.1

---

main.go
webhooks/alias.go
webhooks/doc.go
webhooks/vmware/alias.go
webhooks/vmware/doc.go

This fix allows to export web-hook code for use in external projects as well as controllers code.
This  is the same approach as Cluster API web-hooks exporting, when you need to compile code that will include all controllers and their logic, such as web-hooks, in a single binary file.
Fixes #

:seedling: Able to export webhooks for external utilization

---

.github/workflows/pr-golangci-lint.yaml
.golangci.yml
.trivyignore
Makefile
controllers/vspherecluster_reconciler.go
controllers/vsphereclusteridentity_controller.go
controllers/vspherevm_ipaddress_reconciler.go
hack/ensure-go.sh
test/framework/log/collector.go

[release-1.11] 🌱 Bump to Go 1.23.8 to fix CVEs + ignore CVE CVE-2025-22872 via trivy

---

controllers/vmware/test/controllers_test.go
internal/test/helpers/envtest.go
internal/webhooks/vmware/vspheremachine.go
internal/webhooks/vmware/vspheremachine_test.go
internal/webhooks/vmware/vspheremachinetemplate.go
internal/webhooks/vmware/vspheremachinetemplate_test.go
internal/webhooks/vsphereclustertemplate.go
internal/webhooks/vspheredeploymentzone.go
internal/webhooks/vspheredeploymentzone_test.go
internal/webhooks/vspherefailuredomain.go
internal/webhooks/vspherefailuredomain_test.go
internal/webhooks/vspheremachine.go
internal/webhooks/vspheremachine_test.go
internal/webhooks/vspheremachinetemplate.go
internal/webhooks/vspheremachinetemplate_test.go
internal/webhooks/vspherevm.go
internal/webhooks/vspherevm_test.go
main.go
webhooks/alias.go
webhooks/vmware/alias.go

This PR removes "Webhook" suffix from the all web-hook related structures and aligns comments with web-hook implementations (defaulting and/or validating) according to following comments:
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3434#discussion_r2084753659
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3434#discussion_r2084756517 
Fixes #

:seedling: Fix web-hook structure names and descriptions

---

.github/workflows/pr-golangci-lint.yaml
.golangci.yml
.trivyignore
Makefile
controllers/vspherecluster_reconciler.go
controllers/vsphereclusteridentity_controller.go
controllers/vspherevm_ipaddress_reconciler.go
hack/ensure-go.sh
test/framework/log/collector.go

[release-1.12] 🌱 Bump to Go 1.23.8 to fix CVEs + ignore CVE CVE-2025-22872 via trivy

---

Makefile

[release-1.12] 🌱 Bump govulncheck to v1.1.4

---

main.go
webhooks/alias.go
webhooks/vmware/alias.go

This is manual backport of the #3462 to release-1.11
Fixes #

[release-1.11] :seedling: Fix web-hook structure names and descriptions

---

main.go
webhooks/alias.go
webhooks/vmware/alias.go

This is manual backport of the #3462 to release-1.12
Fixes #

[release-1.12] :seedling: Fix web-hook structure names and descriptions

---

apis/v1alpha3/vspherecluster_types.go
apis/v1alpha4/vspherecluster_types.go
apis/v1beta1/vspherecluster_types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml

The old printercolumn did never work because it never was a list, it was always an object.
Fixes #3362
New output uses `.spec.controlPlaneEndpoint.host` as other providers also do (e.g. CAPZ, CAPO).
CAPA diverges: it has some instances using `.spec.controlPlaneEndpoint.host` (ManagedAWSCluster, RosaAWSCluster), others `.spec.controlPlaneEndpoint`.
This PR renders out as e.g.:
```
❯ kubectl get vspherecluster -o wide
NAME   READY   SERVER   CONTROLPLANEENDPOINT   AGE
foo                     1.2.3.4                18m
```
An alternative would be to use `.spec.controlPlaneEndpoint` which would result in json output:
```
❯ kubectl get vspherecluster -o wide
NAME   READY   SERVER   CONTROLPLANEENDPOINT             AGE
foo …
```

🐛 govmomi: fix additional printer columns for ControlPlaneEndpoint

---

hack/e2e.sh
test/framework/log/collector.go

Also collect logs from the running pods, but as tarball to save some space.
Fixes #

🌱 e2e: also collect pod logs

---

Makefile
test/go.mod
test/go.sum

... to fix govulncheck failures on main

🌱 Bump to Go v1.24.4, github.com/cloudflare/circl v1.6.1

---

Makefile
test/go.mod
test/go.sum

... to fix govulncheck failures on this branch

[release-1.13] 🌱 Bump to Go v1.23.10, github.com/cloudflare/circl v1.6.1

---

Makefile
test/go.mod
test/go.sum

... to fix govulncheck failures on this branch

[release-1.12] 🌱 Bump to Go v1.23.10, github.com/cloudflare/circl v1.6.1

---

Makefile
test/go.mod
test/go.sum

... to fix govulncheck failures on this branch

[release-1.11] 🌱 Bump to Go v1.23.10, github.com/cloudflare/circl v1.6.1

---

pkg/services/vmoperator/resource_policy.go
pkg/services/vmoperator/resource_policy_test.go

This patch ensures that the vSphereCluster owner reference is always set at every reconcile. This ensures that even after a manual removal, the vSphereCluster owner ref link will be reset at the next reconcile.
Fixes n/a

🌱 Enhances VirtualMachineSetResourcePolicy reconcile

---

apis/v1beta1/types.go
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml

fix comment of the `NumCoresPerSocket` property of `VirtualMachineCloneSpec`

🌱 fix comment of the NumCoresPerSocket property of VirtualMachineCloneSpec

---

test/go.mod
test/go.sum

🌱 Bump go-viper/mapstructure to v2.3.0 to fix CVE

---

controllers/vmware/test/controllers_test.go

I hope that fixes:
* https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-provider-vsphere-test-main/1954381688561733632
* https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-provider-vsphere-test-main/1954017284213182464
I assume the problem is that the cache is sometimes not up-to-date
Fixes #

🐛 Fix flake in reconciliation tests

---

test/go.mod
test/go.sum

I broke CAPV e2e tests yesterday by adding a log collector (#3594) without bumping the upgrade test. So let's bump the upgrade test for now (we'll bump everything to v1.11.1 next week anyway)
Fixes #

🐛 Bump test module to get latest version of upgrade test

---

test/go.mod
test/go.sum

Bump to github.com/docker/docker v28.0.2+incompatible to fix CVE
Fixes #

[release-1.12] 🌱 Bump to github.com/docker/docker v28.0.2+incompatible to fix CVE

---

test/e2e/cluster_upgrade_runtimesdk_test.go
test/e2e/ownerrefs_finalizers_test.go

Temporarily ignore resource version changes in VSphereMachine while we found a fix for https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/3592
Note: we consider this temporary fix ok given that we are validating ResourceVersionStable also in other tests where this flake does not happen (so we don't lose coverage entirely) + from a first investigation this seems more an issue of the test setup than a production code issue.

🌱 Temporary fix for ResourceVersion flake

---

.github/ISSUE_TEMPLATE/release_tracking.md

📖 Update release tracking issue template

---

test/e2e/data/autoscaler/autoscaler-to-management-workload.yaml

Noticed that we forgot to configure this
Fixes #

🌱 Set startup taint for autoscaler in e2e tests
