- README.md
**What this PR does / why we need it:**
Starting a bi-weekly meeting.  Updated the links and message.
```
None
```
> Update the readme with meeting and notes link

- Gopkg.lock
- cloud/vsphere/clusteractuator.go
- cloud/vsphere/constants/constants.go
- cloud/vsphere/deployer.go
- cloud/vsphere/machineactuator.go
- cloud/vsphere/provisioner/commands.go
- cloud/vsphere/provisioner/govmomi/create.go
- cloud/vsphere/provisioner/govmomi/delete.go
- cloud/vsphere/provisioner/terraform/templates.go
- cloud/vsphere/provisioner/terraform/terraform.go
- cloud/vsphere/utils/utils.go
This PR further updates and builds on https://github.com/sflxn/cluster-api-provider-vsphere/commit/278f3123b927e0f6dfd989bd697d943585c03b05
> Updated refactor actuator

- README.md
- docs/quickstart.md
Added a quick intro guide to using the clusterctl CLI as well as instructions on getting
all the necessary components ready.
Resolves #56
> Add how to instructions for clusterctl

- Makefile
- cloud/vsphere/provisioner/terraform/terraform.go
- cloud/vsphere/utils/utils.go
go get dep will install HEAD version which is not
what we want.
/assign @frapposelli
> Use release version dep tool

- Makefile
Change-Id: Iab915300c12f1fe38820d3897f48ce05b97b4fe8
> Update the Makefile to reflect the new folder structure

- pkg/cloud/vsphere/provisioner/common/templates.go
- pkg/cloud/vsphere/provisioner/govmomi/create.go
Start using the new `MachineSpec` definition for creating the instance on vsphere
The code now acts accordingly based on the availability of the new cloud-init datasource
`VMwareGuestInfo` inside the template used. This availability can be set by the users in
the spec using the flag `vsphereCloudInit` set to `true`. For usual upstream version of
ubuntu cloud image that has been used so far, this flag need not be set at all and the
controller will utilize the OVF properties available on the ubuntu cloud image to inject
the cloud-init data.
**Note**: The new static IP support is only available with the templates that have the vsphere
cloud-init datasource. DHCP based IPs will continue to work as they have in the past.
Going forward we prefer users creating a custom ubuntu cloud image that …
> Use enhanced MachineSpec to provision

- .travis.yml
- Makefile
- cmd/vsphere-machine-controller/Makefile
this will enable us to run e2e test as presumit job,
in order to make it happen, we need to integrate the repo
with travis-ci, we will work on integrate with Prow later.
> add e2e CI into repo

- cmd/vsphere-machine-controller/main.go
This adds the options related to glog on the command line like `--v=4`
Resolves #91
Change-Id: I0b4756b63d4581e1560e15568b03f380eea1d9bb
> Add goflag parsing to pflags

- OWNERS_ALIASES
Add sflxn to maintainer list to allow approving PRs.
> Add sflxn as maintainer.

- Makefile
The CI build target did not have some dependencies that the production
target have.  Added them to the CI build target to catch more issues.
> Add a few more dependencies to the CI build target

- pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types.go
- pkg/cloud/vsphere/provisioner/govmomi/create.go
- pkg/cloud/vsphere/provisioner/govmomi/create_test.go
- pkg/cloud/vsphere/provisioner/govmomi/utils.go
First pass (towards #35) for testing Create() - adds about 38% coverage to the govmomi actuator package.
> Add test for govmomi actuator Create method

- pkg/controller/add_machine.go
the original error message does not fit the context.
> fix the error message

- scripts/e2e/README.md
- scripts/e2e/bootstrap_job.yml
- scripts/e2e/bootstrap_job/Dockerfile
- scripts/e2e/bootstrap_job/Makefile
- scripts/e2e/bootstrap_job/clusterctl.sh
- scripts/e2e/bootstrap_job/spec/cluster.template
- scripts/e2e/bootstrap_job/spec/machines.template
- scripts/e2e/bootstrap_job/spec/machineset.template
- scripts/e2e/bootstrap_job/spec/provider-components-v1.0.template
- scripts/e2e/bootstrap_job/spec/provider-components-v2.0.template
- scripts/e2e/bootstrap_secret.template
- scripts/e2e/e2e.sh
- scripts/e2e/hack/Dockerfile
- scripts/e2e/hack/Makefile
- scripts/e2e/hack/job.yml
- scripts/e2e/hack/secret.yml
- scripts/e2e/wait_for_job.sh
this is foundation of e2e test: it has two stages
stage 1:  deploy a bootstrap cluster on VMC. (a general k8s cluster, no CRD)
stage 2:  apply secret to bootstrap cluster and apply a k8s job to bootstrap cluster.
the k8s job going to apply clusterapi CRD, and call clusterctl to apply a machineSpec.
and verify the result.
clearly this k8s job can be expanded with regards to:
1. target cluster topology.
2. target cluster verification.
resolve #132
/cc @sflxn @dougm @frapposelli @akutz @sidharthsurana
> clusterapi vsphere e2e test

- installer/.gitignore
- installer/build/bootable/root/opt/ova/bin/kubeadm-provisioning.sh
- installer/build/bootable/root/opt/ova/bin/kubernetes-watchdog.sh
This PR fixes `.gitignore` under `/installer` and add missing scripts to the OVA build
/cc: @sflxn
> Fix .gitignore for OVA

- docs/ova/README.md
> Add Build and Deploy docs for OVA

- cmd/clusterctl/examples/vsphere/generate-yaml.sh
Convenience argument to generate.sh to update the generated provider-components.yaml
file with the containers used during kubecon 2018.
> Added option to generate.sh to use custom kubecon 2018 containers

- README.md
Hello there,
I just tried to use this repo and notice this link is broken. I guess this is right one.
Best,
> Fix quickstart link

- cmd/clusterctl/examples/vsphere/machines.yaml.template
- config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderconfig.yaml
- docs/design/trustedCerts.md
- docs/self-service/README.md
- pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types.go
- pkg/apis/vsphereproviderconfig/v1alpha1/zz_generated.deepcopy.go
- pkg/cloud/vsphere/provisioner/common/templates.go
- pkg/cloud/vsphere/provisioner/govmomi/create.go
Resolves #165
Change-Id: I2f399143419553b120e28b46719e7514990fdab0
> Add support to inject custom trusted certs into the machines

- docs/self-service/README.md
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/184
> Fix Syntax Errors in self service quickstart

- cmd/clusterctl/examples/vsphere/machines.yaml.template
- scripts/e2e/bootstrap_job/clusterctl.sh
- scripts/e2e/bootstrap_job/spec/machines.template
the current yaml example does not work with kubectl
add MachineList make it a valid spec for kubectl
> use MachineList in machine yaml

- docs/self-service/README.md
A recent update of the vendor code updated the clusterctl bootstrap support to include
kind.  This update includes information on using kind as a bootstrapper.
In addition, the minikube project has merged the Fusion support PR.  There is no
longer a need to jump through hoops to build a version of minikube that supports
Vmware Fusion.  This update simplifies the minikube installation section.
Resolves #189
> Update the self-service quickstart docs for minikube and kind

- pkg/cloud/vsphere/provisioner/govmomi/create.go
See https://code.vmware.com/doc/preview?id=4206#/doc/vim.vm.RelocateSpec.DiskMoveOptions.html
for more details
Resolves #212
Change-Id: Ic62701aabc134a3e5038d440eccf902e52bd3351
> Fix cloning from template with snapshot and simultaneous disk expansion

- cmd/manager/main.go
After move to CRD the sync period changed to 10 hrs from few sec
Change-Id: Ia845a01df59afa737d26fdd96ded09ea9bd8c9c5
Resolves #179
> Set the cache resync period to 2 min

- pkg/cloud/vsphere/provisioner/govmomi/create.go
Resolves #232
Change-Id: I073a836da844c19913d8697a51068c51b5f71efb
> Add nil check for the cluster ProviderStatus

- cmd/clusterctl/examples/vsphere/machines.yaml.template
- cmd/clusterctl/examples/vsphere/machineset.yaml.template
- config/crds/vsphereproviderconfig_v1alpha1_vsphereclusterproviderconfig.yaml
- config/crds/vsphereproviderconfig_v1alpha1_vspheremachineproviderconfig.yaml
- docs/design/ntpServers.md
- pkg/apis/vsphereproviderconfig/v1alpha1/vsphereclusterproviderconfig_types.go
- pkg/apis/vsphereproviderconfig/v1alpha1/vspheremachineproviderconfig_types.go
- pkg/apis/vsphereproviderconfig/v1alpha1/zz_generated.deepcopy.go
- pkg/cloud/vsphere/provisioner/common/templates.go
- pkg/cloud/vsphere/provisioner/govmomi/create.go
Resolves #244
Change-Id: I0cb436d3e778686ab70ad01e119c94eb4407e28d
> Add support for specifying ntp servers in the MachineSpec

- cmd/manager/main.go
Add optional --namespace flag so the controllers only watch for cluster
and machine objects in a single namespace.
Signed-off-by: Andy Goldstein <goldsteina@vmware.com>
> Add namespace flag to limit to a single namespace

- OWNERS_ALIASES
Change-Id: Ib990efeca1a59c7ab98b77801d969a302b1531e9
> Add ssurana to list of maintainers for CAPV

- OWNERS_ALIASES
/assign @frapposelli @sidharthsurana
> Add figo to list of maintainers for CAPV

- docs/ova/README.md
> fix a small typo in deployment instructions

- docs/self-service/README.md
Previously the quickstart guide lacked troubleshooting details to be used in case of errors.  Users needed to search through the github issues to find out how to work through problems.  This provides a series of options for working through provisioning problems.
Issue #277
> Add troubleshooting Information to Self-Service Docs

- scripts/e2e/e2e.sh
> restore e2e test cleanup

- pkg/cloud/vsphere/clusteractuator.go
- pkg/cloud/vsphere/provisioner/govmomi/utils.go
- pkg/cloud/vsphere/utils/utils.go
Follow-up PR to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/291
/assign @sidharthsurana
> fix master -> control plane

- scripts/e2e/bootstrap_job/Makefile
- scripts/e2e/bootstrap_job/clusterctl.sh
since we moved the CNI from cloud-init spec to addons
Signed-off-by: Hui Luo <luoh@vmware.com>
cc @andrewsykim @akutz
> Add addons.yaml into ci deployment

- cmd/clusterctl/examples/vsphere/machineset.yaml.template
> clusterctl: remove tabs in machinset yaml template

- cmd/clusterctl/examples/vsphere/generate-yaml.sh
- cmd/clusterctl/examples/vsphere/machines.yaml.template
- cmd/clusterctl/examples/vsphere/machineset.yaml.template
Merge only after https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/307
> clusterctl: templatize kubernetes version

- build/images/README.md
> fix CAPV image URLs in build/images/README.md

- pkg/cloud/vsphere/actuators/actuators.go
This patch updates the actuator error handling so that requeue errors are no longer logged as failures.
> Do not log requeue errors as failures

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
This patch adds the standard k/k issue/pr templates to this project.
/assign @frapposelli 
/assign @figo
/assign @andrewsykim
> Add k/k issue/pr templates

- cmd/clusterctl/examples/vsphere/generate-yaml.sh
> clusterctl: VM folder should be optional

- pkg/cloud/vsphere/context/cluster_context.go
- pkg/cloud/vsphere/context/machine_context.go
This patch fixes an issue with the way patching an object with a JSON patch would fail when the status was modified first.
Since cluster and machine objects have their status values changed during any given call stack, the current patch model sometimes fails because JSONPatching either object type fails when status is included. This is also why the status is patched separately later.
This PR fixes things by ensuring the status of either object is the same as it was when the call was enqueued ahead of generating the JSON patch. After the patch the status is put back ahead of the status patch.
Please see [this Slack thread](https://kubernetes.slack.com/archives/C8TSNPY4T/p1561400433201000) for more information.
**Which issue(s) this PR fixes**: NA …
> Fixes failed JSON patches

- OWNERS_ALIASES
Correct my github Id in the Maintainers file
I accidentally used my email user instead of my github id while adding that.
Fixes #
```release-note
```
> Correct ssurana github id to sidharthsurana

- pkg/cloud/vsphere/actuators/cluster/actuator.go
Syncs the kubeconfig for clusters as Secrets. The naming format is Secrets is `<cluster-name>-kubeconfig`. 
Fixes #
```release-note
Sync the kubeconfig for a cluster as a Kubernetes Secret. 
```
/assign @akutz
> cluster actuator: sync kubeconfig secret

- Makefile
This patch updates the production image to 0.3.0-alpha.0.
**Which issue(s) this PR fixes**: NA
**Release note**: 
```release-note
* Update the production image to 0.3.0-alpha.0.
```
> Update the production image to 0.3.0-alpha.0

- hack/generate-yaml.sh
This patch fixes the ability to set a custom out directory when using the yaml generation script. This patch also adds the flag "-d" to disable environment variable requirements.
**Which issue(s) this PR fixes**: Fixes #348
```release-note
NONE
```
> Fix the -o OUT_DIR opt for generating yaml

- docs/getting_started.md
Fixes some typos in docs/getting_started.md, thanks for catching @fstrudel! 
Fixes #
```release-note
```
> fix typos in docs/getting_started.md

- Makefile
This patch updates the prod image to 0.3.0-alpha.1
**Which issue(s) this PR fixes**: NA
```release-note
NONE
```
> Update image to 0.3.0-alpha.1

- hack/generate-yaml.sh
This patch adds new flags to the generate-yaml script.
* -c can be used to specify the name of the cluster
* -m is used to specify the name of the CAPV manager image
If -c is specified then the output directory becomes "./out/CLUSTER_NAME". If -o OUT_DIR is specified then the output directory is "OUT_DIR". Use -o to specify explicit output directories, otherwise the directories are unique based on the name of the cluster.
Fixes #359  …
> Add new flags to generate-yaml

- scripts/e2e/bootstrap_job/spec/machines.template
- scripts/e2e/bootstrap_job/spec/machineset.template
Change network from sddc-cgw-network-3 to sddc-cgw-network-5, a new
network solely dedicated to CAPV testing.
Fixes #
```release-note
```
> Change network name for CAPV e2e tests

- Makefile
Update release image tag to v0.3.0-alpha.2 
Fixes #
```release-note
```
/assign @akutz
> Update to image tag to v0.3.0-beta.0

- docs/getting_started.md
In https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/367 we changed the default output dir from `out/` to `out/<cluster-name>`. This updates the getting started docs to reflect this change. 
Fixes #
```release-note
```
> docs/getting_started.md: use new out directory for generate-yaml.sh

- Makefile
This patch updates clusterctl targets to build statically linked binaries.
Fixes #
I was building `clusterctl` for releases manually, and this way we can rely on the Docker build for those too.
```release-note
NONE
```
> Updates to build static clusterctl 

- README.md
- docs/getting_started.md
* clarifies assumptions and expectations around clusterctl and kubectl
* clean up project README
Fixes #
```release-note
```
> docs: clarify workflow using clusterctl and kubectl 

- Makefile
Update CAPV provider image to 0.3.0
Fixes #
```release-note
```
> update CAPV image tag to 0.3.0

- docs/getting_started.md
Fix typo of the default value of VSPHERE_MEM_MIB.
Fixes #
```release-note
```
> Fix typo in default MB value of VSPHERE_MEM_MIB

- build/images/packer/linux/centos/http/7/ks.cfg
- build/images/packer/linux/ubuntu/http/base/preseed.cfg
- hack/image-build-ova.py
This PR includes the following updates for machine images:
* The image names are consistent with #347
* Nginx is included as a disabled service in order to serve as non-TLS endpoint for AWS LB health checks for CAPV on VMC
Fixes #347
```release-note
* Machine images will import into vSphere as unique names
* Nginx is now installed as a disabled service in the machine images
```
> Machine image updates

- pkg/cloud/vsphere/services/govmomi/update.go
This patch fixes a bug where a VM is not recreated if it is deleted by the infrastructure, but still exists as a machine in CAPV.
Fixes #409
```release-note
* Fixes a bug where a deleted VM is not recreated
```
> Recreate VM if it is deleted by infrastructure

- cmd/manager/main.go
This patch introduces support for customizing the CAPV manager's sync period via the environment variable `SYNC_PERIOD` and/or the CLI flag `--sync-period`. If set, the environment variable modifies the default value for the flag, otherwise the default sync period is 10 minutes.
Please see #417 for more information.
Hi @moshloop,
In conjunction with #417, this PR is intended to replace #392. Please see #417 for more information.
```release-note
* The sync period may be set with SYNC_PERIOD or --sync-period as a string parseable by …
```
> Customizable sync period

- Makefile
This patch removes vestigial Makefile targets: install, run, and deploy.
This prevents confusion with people new to the project.
```release-note
* Remove vestigial Makefile targets: deploy, install, and run
```
> Removes Makefile targets: install, run, deploy

- scripts/e2e/e2e.sh
Fix shellcheck issues for scripts/e2e/e2e.sh
Fixes #
```release-note
```
> Fix shellcheck issues for scripts/e2e/e2e.sh

- scripts/e2e/e2e.sh
I've seen a few cases where the E2E test reports successful, even though it failed pretty early on. An example is this [log](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-vsphere-e2e/1144662693072867328). In that example, the KIND cluster creation failed, but the test reported success.
This patch adds a wrapper that checks the return code when remote operations are
done, such that we can exit when there is a failure. Track when the bootstrap
VM is created so that we clean up properly if there is a failure.
Fixes # …
> Exit early if command fails on bootstrap

- hack/tools/mdlint/Dockerfile
This patch updates the markdown linter image.
Fixes #
```release-note
NONE
```
> Update the mdlint tool image

- docs/getting_started.md
- scripts/e2e/create_kind_cluster.sh
- scripts/e2e/kind_config.template
Use KIND v0.4.0 in e2e tests, and update docs to have users download the
latest version.
Fixes #
```release-note
```
> Update KIND references to v0.4.0

- hack/generate-yaml.sh
Simple fix for `export VSPHERE_USER=viadmin@vmware.local `     changed to  `export VSPHERE_USERNAME=viadmin@vmware.local `
Fixes #
Isssue #433 
Document Change to https://github.com/tkrausjr/cluster-api-provider-vsphere/blob/master/docs/getting_started.md
```release-note
```
> Fixed export VCENTER_USERNAME in GSG & generate-yaml.sh script

- hack/check-shell.sh
- hack/generate-yaml.sh
- hack/tools/shellcheck/Dockerfile
- hack/tools/shellcheck/Makefile
- hack/tools/shellcheck/shellcheck.sh
- scripts/ci-test.sh
- scripts/e2e/bootstrap_job/clusterctl.sh
- scripts/e2e/create_kind_cluster.sh
- scripts/e2e/wait_for_job.sh
- scripts/fetch_ext_bins.sh
This PR introduces a shellcheck linter `hack/check-shell.sh` that will also be implemented as a Prow pre-submit.
This PR also includes a new image, `gcr.io/cluster-api-provider-vsphere/extra/shellcheck`, that may be used to lint a k/k project with the following command:
```shell
docker run -t --rm -v "$(pwd)":/-:ro -w /- gcr.io/cluster-api-provider-vsphere/extra/shellcheck
```
```release-note
* Project scripts are linted with shellcheck. …
```
> Shellcheck

- hack/generate-yaml.sh
- hack/tools/generate-yaml/Dockerfile
> Update generate-yaml tools for new image location

- hack/tools/bootstrap-base/Dockerfile
- hack/tools/bootstrap-base/Makefile
- hack/tools/manifests-base/Dockerfile
- hack/tools/manifests-base/Makefile
Both the bootstrap and manifests container image install OS packages, and since
these images are built every time during E2E tests, that is time
consuming. We can speed this up by creating base images to build from,
only pulling in what is needed and not doing OS updates.
Fixes #
```release-note
```
> Create base images for bootstrap and manifests

- hack/tools/generate-yaml/Dockerfile
- scripts/e2e/bootstrap_job/Dockerfile
Opening this PR as an example of how we would use the base images in #462 
Fixes #
```release-note
```
/hold
> Use base images for bootstrap and manifests images

- docs/getting_started.md
Don't set CLUSTER_NAME in envvars.txt because it can overrwrite what is set with -c in generate-yaml.sh. 
Fixes #
```release-note
NONE
```
> docs: don't set CLUSTER_NAME in envvars.txt because it's set with -c

- README.md
- docs/troubleshooting.md
This patch adds a troubleshooting guide.
Fixes #
```release-note
* Added a troubleshooting guide
```
> Troubleshooting guide

- docs/troubleshooting.md
The instructions on increasing the log level created to containers in the pod spec, but incomplete entries. Small fix to the remove the hyphen from `- command:`.
Saved with a markdown linter, so the TOC got regenerated.
```release-note
```
> Fix indentation for increasing log level

- docs/getting_started.md
- pkg/cloud/vsphere/services/govmomi/template/template.go
fix a few typos found when reading around
Fixes #473 
```release-note
```
> fix a few typos found when reading around

- api/v1alpha2/cloud/doc.go
This patch fixes a misspelled word on line 22 of "pkg/apis/vsphere/v1alpha1/cloud/doc.go".
Fixes #
```release-note
NONE
```
> Fixing a misspelled word

- examples/provider-components/manager_tolerations_patch.yaml
This PR fixes the `examples/provider-components/manager_tolerations_patch.yaml` to use the correct CAPI namespace and name
Fixes #
```release-note
```
> fix to manifests generation

- api/v1alpha2/vspherecluster_types.go
- api/v1alpha2/vspheremachine_types.go
- api/v1alpha2/vspheremachinetemplate_types.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
- config/rbac/role.yaml
- controllers/vspherecluster_controller.go
- controllers/vspheremachine_controller.go
This PR adds the needed RBACs to CAPV resources.
Fixes #
```release-note
```
> rbac fixes

- docs/getting_started.md
This patch updates the getting started docs with the release image URIs.
Fixes #
```release-note
```
> Update getting started doc with release images

- hack/release.sh
We need a way to have our automation build and push multiple minor versions of releases (e.g. 0.4.x, 0.5.x), but be able to specify which of these versions should also get tagged as `latest`. We are already managing this with branches. Thus...
The -b option allows one to specify a branch for use with the -l option.
This means that if -l is used (tag images as latest) the "latest" tag
will *only* be applied if the current commit is in/on the given branch.
Otherwise "latest" will not be applied.
This allows for CI to do a job like `hack/release.sh -l -p -b release-0.4` that runs on every commit, and only have the `latest` tag applied to images built on tags on the `release-0.4` branch.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
> Add -b option to hack/release.sh

- pkg/cloud/vsphere/services/govmomi/service.go
This PR adds the logic to remove the `MachineRef` if a vm does not exist.
Fixes #551 
```release-note
```
> remove MachineRef when vm is deleted

- .gitignore
git ignores envars.txt file we use in manifest generation examples.
Fixes #
```release-note
NONE
```
> git ignore envars.txt

- docs/getting_started.md
Did a pull request https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/559 got merged... 
But did update the workload cluster sample manifest. This will fix it.
Fixes #
```release-note
```
> add service domain to the sample work-cluster manifest

- api/v1alpha2/cloudprovider/encoding.go
- api/v1alpha2/cloudprovider/encoding_test.go
1) Adds new line after each section of the cloud config INI marshallar
2) fixes equal comparison in TestMarshalINI
Fixes #
```release-note
NONE
```
> Fix cloudprovider encoding tests

- README.md
> fix: cleaning up readme.md

- docs/getting_started.md
- examples/default/cluster/cluster.yaml
- pkg/cloud/vsphere/services/cloudprovider/csi.go
Update the default CSI images used to the most recent release from GitHub repo, published on gcr.io.
Fixes #
```release-note
```
/assign @andrewsykim 
/assign @akutz
> Update CSI default images to v1.0.1 on gcr.io

- docs/getting_started.md
> update default Kubernetes version in docs to v1.16.2

- README.md
The published CAPV images are really for testing and POCs only.
Fixes #644 
```release-note
```
> Add CAPV image disclaimer

- examples/generate.sh
- go.mod
- go.sum
- scripts/e2e/e2e.sh
- scripts/e2e/generate-e2e-spec.sh
/kind feature
This patch updates the CAPI dependency to 0.2.7.
Fixes #
```release-note
* Cluster API v0.2.7
```
> Cluster API 0.2.7

- docs/troubleshooting.md
Adds some troubleshooting guidance to avoid further issues regarding CA and NTP related issues.
Fixes #621 
Just adding text to the troubleshooting documentation.
```release-note
NONE
```
> Adds some troubleshooting for CA related issues

- controllers/vspheremachine_controller.go
fixes copy/paste error that prevented machines from being deleted
> restore machine deletion

- api/v1alpha2/types.go
- controllers/vspherecluster_controller.go
/kind feature
This patch supports a control plane endpoint annotation for v1alpha2.
cc @rsmitty
Fixes #697
```release-note
```
> Support a control plane endpoint annotation for v1a2

- docs/getting_started.md
- examples/default/cluster/cluster.yaml
- pkg/services/cloudprovider/cloud-controller-manager.go
/kind feature
This patch updates the vSphere cloud provider dependency to 1.1.0.
Fixes #
```release-note
* vSphere cloud provider v1.1.0
```
> vSphere cloud provider 1.1.0

- examples/generate.sh
- go.mod
- go.sum
- scripts/e2e/e2e.sh
/kind feature
This patch updates the Cluster API dependency to 0.2.8.
Fixes #
```release-note
* Cluster API 0.2.8
```
> Cluster API 0.2.8

- docs/getting_started.md
/kind documentation
This patch updates the getting started docs in the release-0.5 branch to use the latest release from said branch.
Fixes #
```release-note
```
/assign @yastij
> Update getting started doc to use release-0.5

- test/e2e/framework/management_cluster.go
This patch fixes the e2e tests by allowing a custom CAPI image. To run e2e with a working version of upstream CAPI please do the following:
```shell
$ export CAPI_IMAGE=gcr.io/k8s-staging-cluster-api/cluster-api-controller:v20200103-v0.2.5-497-gdbe789259
$ export CAPI_GIT_REF=09949bd397eecbfeac4e011b0d2c29fdbf2ac1ef
$ make e2e
```
The above should work until upstream CAPI fixes things.
cc @yastij 
Fixes #
```release-note
```
> Fix e2e tests by allowing custom CAPI image

- test/e2e/framework/multi_node_control_plane.go
- test/e2e/framework/single_node_control_plane.go
/kind feature
This PR includes some e2e cleanup and is based on #709. This PR will be rebased once #709 is merged.
Fixes #
```release-note
```
> e2e cleanup

- OWNERS_ALIASES
Nominating @yastij for promotion to the maintainers list as a significant contributor.
/hold
For lazy consensus for 7 days
> OWNERS_ALIASES: Add yastij (Yassine Tijani) to maintainers list

- OWNERS_ALIASES
Co-authored-by: Naadir Jeewa <jeewan@vmware.com>
**What this PR does / why we need it**:  adding myself as an approver for release-0.5 branch
Fixes #
/assign @randomvariable @ncdc 
```release-note
```
> Add yastij (Yassine Tijani) to the cluster-api-vsphere-maintainers group

- controllers/vspherecluster_controller.go
Co-Authored-By: Andy Goldstein <goldsteina@vmware.com>
**What this PR does / why we need it**: cherry-pick of #763
Fixes #
/assign @randomvariable @ncdc 
```release-note
Before deleting a VSphereCluster check if all the corresponding VSphereMachines are gone
```
> cherry-pick of #763: check that vspheremachines are deleted before deleting the vspherecluster

- go.mod
- go.sum
- pkg/util/kubeclient.go
**What this PR does / why we need it**: This PR updates CAPV to the new CAPI RC
```release-note
update CAPV to CAPI v0.3.0-rc.1
```
> update CAPV to CAPI rc-1

- Makefile
- controllers/haproxyloadbalancer_controller.go
- controllers/vspherecluster_controller.go
- controllers/vspheremachine_controller.go
- controllers/vspherevm_controller.go
**Which issue(s) this PR fixes** : Fixes #783
/assign @detiber 
```release-note
do not reconcile resources if cluster.spec.Paused is true
```
> respect the paused field and annotations

- docs/getting_started.md
**What this PR does / why we need it**: This adds a link to the RC OVA
Fixes #
/assign @randomvariable @detiber 
```release-note
NONE
```
> link to rc haproxy OVA

- packaging/flavorgen/flavors/generators.go
- packaging/flavorgen/flavors/helpers.go
Fixes #792 
```release-note
* fixes string quoting in clusterctl templates
```
> packaging: String-quote string variables during substitution

- docs/getting_started.md
Bump versions of core bootstrap and control-plane components to rc.3 to fix a bug in move.
Updating component versions from rc.2 to rc.3 fixes problems that I experienced in using the move command.
Fixes #
```release-note
NONE
```
> Update component versions in getting started

- docs/getting_started.md
**What this PR does / why we need it**: This PR adds docs to specify operations on vm templates to leverage `linkedClone` mode, how to apply CNI and updates the HA proxy OVA link
Fixes #
```release-note
NONE
```
> update docs and links to prep for rc-2

- docs/getting_started.md
/kind documentation
This patch updates the Getting Started guide to add clarity around how to import an OVA as a VM template.
Fixes #
```release-note
NONE
```
> Update GettingStarted with clearer instructions for VM template

- docs/troubleshooting.md
This PR adds troubleshooting steps and scenarios for instances when a machine object is stuck in a provisioning state.
No issue against this PR
There are no changes to any image versions
```release-note
NONE
```
> Add troubleshooting scenarios for machine object stuck in provisioning state

- pkg/services/cloudprovider/csi.go
**What this PR does / why we need it**: This PR aligns with the latest changes for the vsphere csi driver
```release-note
```
> update env variable to pass csi-vsphere.conf

- docs/getting_started.md
**What this PR does / why we need it**: This PR updates the docs to point to the latest haproxy ova
Fixes #
```release-note
```
> update docs to point to the haproxy ova v0.6.0

- controllers/haproxyloadbalancer_controller.go
- pkg/haproxy/secrets.go
Clock skew on VI infrastrucuture can lead to certificate validity issues in HAProxyLoadBalancer.
This changes the cert gen to start validity 10 minutes prior to current time.
In addition, HAProxy reconfiguration is requeued after 20s in case of errors.
Fixes #
```release-note
* Account for clock skew when generating certificates for HAProxy
```
> :bug: Allow for time skew in certificate generation for HAProxy

- api/v1alpha3/types.go
Fix typo FullClone mode is NOT the fastest.
Fixes #
```release-note
```
> Fix typo FullClone mode is NOT the fastest.

- controllers/vspherevm_controller.go
**What this PR does / why we need it**: This PR adds watches for paused field in the vspherevm controller, otherwise this potentially leads to lost status after `clusterctl move`
Fixes #
```release-note
```
> watch for paused field in the vspherevm controller

- controllers/vspheremachine_controller.go
> fix deletion of vms by waiting for not found

- controllers/haproxyloadbalancer_controller.go
- controllers/vspherecluster_controller.go
> wait for vspherevm to be deleted before deleting haproxyloadbalancer

- controllers/haproxyloadbalancer_controller.go
- pkg/haproxy/config.go
Fixes #844 
Fixes #850
```release-note
* HAProxy does not constantly restart on reconciliation
* HAProxy stats enabled on port 8404
* HAProxyLoadBalancer controller log values are made consistent
```
> HAProxyLoadBalancer: Stop constant restarting of HAProxy

- OWNERS_ALIASES
- SECURITY_CONTACTS
* Promote @randomvariable to maintainer
* Create emeritus maintainers group
* Update Cluster API and SIG Cluster Lifecycle admin lists.
/hold
> Update Cluster API maintainers, promote jeewan

- hack/tools/haproxy/hack/image-build-ova.py
When building in enterprise environments, the ISO URL can expose
internal build details.
Fixes #
These details were removed in the `image-builder` in https://github.com/kubernetes-sigs/image-builder/pull/182
```release-note
```
> remove ISO info from HAProxy OVF metadata

- api/v1alpha3/cloudprovider_encoding.go
- controllers/vspherecluster_controller.go
Fixes #866 
```release-note
* Correct setting of extraArgs on cloud provider configuration
```
> cloudprovider: Correctly merge arguments

- hack/tools/haproxy/packer.json
Use a tagged version of the guestinfo datasource
Fixes #
```release-note
```
/assign @akutz @yastij
> Use a tagged version of the guestinfo datasource

- main.go
Seed the random number generator, as (at least) controller-runtime uses
it to add jitter to shared informer resync periods.
Fixes #
```release-note
NONE
```
> Seed the random number generator

- docs/getting_started.md
> point to the new HAProxy OVA on the getting started docs

- packaging/flavorgen/flavors/generators.go
- packaging/flavorgen/flavors/helpers.go
> generate an empty selector to pass admission

- README.md
Update links to latest node and haproxy OVAs. Since the HAProxy OVAs are
now built with image-builder, we now point to them in their own
dedicated section. We also remove K8s 1.15 and add 1.18.
Fixes #
```release-note
```
/assign @yastij
> Update README with latest OVAs

- controllers/haproxyloadbalancer_controller.go
Ensure we commit transactions, and additionally delete any open transactions on re-entrancy.
Fixes #891 
```release-note
* Ensure HAProxy transactions are always closed.
```
> haproxyloadbalancer: Ensure we don't have transactions open

- controllers/haproxyloadbalancer_controller.go
Cherry pick of #907 on release-0.6.
#907: haproxyloadbalancer: Ensure we don't have transactions open
> Automated cherry pick of #907: haproxyloadbalancer: Ensure we don't have transactions open

- controllers/vspherecluster_controller.go
- pkg/services/cloudprovider/csi.go
**What this PR does / why we need it**: This PR bumps the vsphere CSI driver to v2.0.0 for existing clusters
changes are based on https://github.com/kubernetes-sigs/vsphere-csi-driver/tree/master/manifests/v2.0.0/vsphere-67u3/vanilla
```release-note
upgrade vsphere CSI driver to v2.0.0
```
> upgrade csi to v2.0.0 for newly created clusters

- controllers/vspherecluster_controller.go
- pkg/services/cloudprovider/csi.go
Cherry pick of #915 on release-0.6.
#915: upgrade csi to v2.0.0 for newly created clusters
> Automated cherry pick of #915: upgrade csi to v2.0.0 for newly created clusters

- pkg/services/cloudprovider/csi.go
Cherry pick of #929 on release-0.6.
#929: update the latest changes to the csi drivers
> Automated cherry pick of #929: update the latest changes to the csi drivers

- pkg/services/cloudprovider/csi.go
**What this PR does / why we need it**: This PR adds the latest updates for CSI
**Which issue(s) this PR fixes**: Fixes #927 
```release-note
```
> update the latest changes to the csi drivers

- go.mod
- go.sum
> cherry pick of #932: update go.mod

- hack/e2e.sh
- test/e2e/e2e.conf
**What this PR does / why we need it**: This PR bumps the kubernetes version and updates the OVAs
```release-note
NONE
```
> bump the kubernetes version we test against

- controllers/haproxyloadbalancer_controller.go
- controllers/vspherecluster_controller.go
HAProxyLoadBalancer is being deprecated in favour of virtual IPs.
Restrict HAProxyLoadBalancer to reconciling for vSphereClusters to
prevent repeated log entries when the controller does not have
permission to read infrastructure objects from different providers.
Example log spam:
```
[manager] E0706 13:08:57.047937       8 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list infrastructure.cluster.x-k8s.io/v1alpha3, Kind=AWSCluster: awsclusters.infrastructure.cluster.x-k8s.io is forbidden: User "system:serviceaccount:capv-system:default" cannot list resource "awsclusters" in API group "infrastructure.cluster.x-k8s.io" at the cluster scope
```
**Which issue(s) …
> haproxyloadbalancer controller: Only reconcile VSphereClusters

- hack/e2e.sh
- test/e2e/e2e.conf
**What this PR does / why we need it**: This PR fixes the CI by replacing the featureflag with explicit values, this is just a short-term fix until #922 merges
Fixes #
/assign @ncdc 
```release-note
```
> replace featuregate flags to fix the e2e

- examples/default/cluster/cluster.yaml
- packaging/flavorgen/flavors/generators.go
- pkg/services/cloudprovider/cloud-controller-manager.go
- test/e2e/capv_resource_generators.go
Signed-off-by: jan.jansen <jan.jansen@gdata.de>
Fixes #
```release-note
```
> Bump gcr.io/cloud-provider-vsphere/cpi/release/manager from v1.0.0 to v1.1.0.

- api/v1alpha3/vspheremachine_webhook_test.go
- api/v1alpha3/vspheremachinetemplate_webhooks_test.go
- api/v1alpha3/vspherevm_webhook_test.go
- api/v1alpha3/webhooks.go
**What this PR does / why we need it**: This PR fixes boilerplate formatting on webhook tests
Fixes #
/assign @ncdc 
```release-note
```
> fix boilerplate on webhook tests

- Dockerfile
- Makefile
- hack/version.sh
- main.go
- pkg/version/version.go
Adds version to start of controller logs
Fixes #877 
```release-note
NONE
```
> Adds git version to start of controller logs

- docs/releasing.md
> docs: Add notes on how to do a new release.

- controllers/vspherecluster_controller.go
- go.mod
- go.sum
- packaging/flavorgen/flavors/flavors.go
- packaging/flavorgen/flavors/generators.go
- pkg/services/cloudprovider/csi.go
- test/e2e/data/infrastructure-vsphere/cluster-template-haproxy.yaml
- test/e2e/junit.e2e_suite.1.xml
This PR is to install csi as an add-on instead of having it reconciled as part of capv when deploying workload clusters.
Fixes #718 
This PR changes any image versions, and that's the sole change this PR makes.
```release-note
```
> [WIP] Install csi as an add-on

- docs/getting_started.md
**What this PR does / why we need it**: This PR updates the docs to focus more our default flavour and some wording around custom templates
/assign @randomvariable @fabriziopandini 
```release-note
```
> add docs for v0.7.0

- docs/getting_started.md
Small fixes to the getting started page
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/990
```release-note
NONE
```
> Small fixes to getting started page

- packaging/flavorgen/flavors/generators.go
- pkg/services/cloudprovider/cloud-controller-manager.go
- test/e2e/data/infrastructure-vsphere/cluster-template.yaml
Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>
Bump vSphere cloud provider to v1.2.1 which contains some bug fixes. 
Fixes #
```release-note
```
> :seedling: Bump CPI version to v1.2.1

- docs/getting_started.md
Signed-off-by: Shivesh Abhishek <shankeyshivesh@gmail.com>
There is a minor typo in the `Getting Started` page in between a command. This PR fixes it.
Fixes #
```release-note
```
> fix typo in getting_started

- controllers/vspherecluster_controller.go
1) Remove unwanted copying of controlplane endpoint from Cluster back to VSphereCluster.
2) Cleanup legacy code
Fixes #1020 
```release-note
NONE
```
> Fix reconcile of controlplane endpoint in VSphereCluster

- .gitignore
- controllers/vspherecluster_controller.go
- controllers/vspheremachine_controller.go
- controllers/vspherevm_controller.go
- pkg/context/cluster_context.go
Adding conditions for the reconcile delete workflow
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/991
```release-note
VSphereCluster, VSphereMachine, VSPhereVM now update conditions during the delete workflow
```
> Add conditions for the reconcile delete workflow

- controllers/vspherecluster_controller.go
**What this PR does / why we need it**: This PR re-order the deletion process to delete the `HAProxyLoadBalancer` after the `vsphereMachines` are deleted
**Which issue(s) this PR fixes**: Fixes #1033
/assign @fabriziopandini 
```release-note
re-order the deletion process to delete the haproxylb after the machines
```
> re-order the deletion process to delete the haproxylb after the machines

- docs/roadmap/v1alpha4.md
**What this PR does / why we need it**: This PR adds the initial API changes that are going to be needed for v1alpha4, the PR isn't exhaustive, and we can update it as we start to add/remove fields/features
/assign @fabriziopandini @vincepri 
```release-note
```
> add the v1alpha4 API changes for CAPV

- docs/proposal/20201103-failure-domain.md
Proposal for failure domain design based on community discussions.
Fixes #
```release-note
```
> [CAEP] proposal for failure domain

- OWNERS
- OWNERS_ALIASES
Move ncdc to emeritus status
Fixes #
```release-note
NONE
```
> Move ncdc to emeritus status

- api/v1alpha3/condition_consts.go
- controllers/vspherecluster_controller.go
**Which issue(s) this PR fixes**:  Fixes #1065 
```release-note
```
> probe vcenter as part of the vspherecluster reconciliation

- controllers/vspherecluster_controller.go
**What this PR does / why we need it**: This PR skips cloud provider reconciliation when no config is provided
**Which issue(s) this PR fixes**: Fixes #1083 
```release-note
```
> skip cloud provider/CSI install when no cloudprovider config is provided

- docs/getting_started.md
**What this PR does / why we need it**: This PR updates the doc and adds the `VSPHERE_TLS_THUMBPRINT` as the sha1 fingerprint of the vcenter cert
**Which issue(s) this PR fixes**: Fixes #1085
```release-note
```
> add tls thumbprint env var in the getting_started.md

- docs/getting_started.md
**What this PR does / why we need it**: adds more clarification on how to extract the sha1 fingerprint
Fixes #
```release-note
```
> document the openssl command the extract the thumbprint

- pkg/services/govmomi/vcenter/clone.go
Specifies the diskLocator as a part of the VmRelocateSpec
Fixes #1106 
```release-note
NONE
```
> Specifies disks in clone spec

- pkg/services/govmomi/vcenter/clone.go
WIP while we wait for #1108 to merge 
With these changes, we look for compatible datastores to use when a storagepolicy is defined. 
- If storage policy and datastore is defined, it validates the datastore is contained in the compatible list of datastores for the storage policy
- Errors if storage policy returns an empty list of compatible datastore
- Falls back to using the default datastore if neither datastore or storage policy is defined. 
Fixes #1091 
I removed the gocyclo linter for the function as properly refactoring it should be its own issue. …
> Utilize datastores found via storage policy

- README.md
**What this PR does / why we need it**: Updates the bi-weekly meeting times and zoom link.
Fixes # No issue logged.
**Release note**: 
```release-note
Updated the README.md file with the current time for the bi-weekly meeting.
Updated the zoom link to the new zoom link as well as provided the password.
```
> Updated Zoom link and meeting time.

- pkg/services/govmomi/vcenter/clone.go
Cherrypicking #1133 
/assign @yastij
> fix panic and randomize chosen datastore when using storage policiess

- packaging/flavorgen/flavors/generators.go
Signed-off-by: Sagar Muchhal <muchhals@vmware.com>
Updates the kube-vip version in flavorgen
Fixes #1109 
n/a
```release-note
Updates the kube-vip version to 0.3.2
```
> Updates kube-vip version to 0.3.2

- pkg/services/cloudprovider/csi.go
cherry-pick #1159 
```release-note
NONE
```
> Removes topology feature gate 

- packaging/flavorgen/flavors/generators.go
- test/e2e/capv_quick_start_test.go
- test/e2e/config/vsphere-ci.yaml
- test/e2e/config/vsphere-dev.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/govmomi_test.go
Adds storage policy e2e test
```release-note
NONE
```
> Adds storage policy e2e test

- pkg/services/govmomi/service.go
- pkg/services/govmomi/vcenter/clone.go
cherry-pick #1147 
```release-note
NONE
```
> Reconcile storage policy after vm clone

- pkg/util/machines.go
- pkg/util/machines_test.go
Cherry pick of #1156 on release-0.7.
#1156: fix panic when reading from the list of devices
> Automated cherry pick of #1156: fix panic when reading from the list of devices

- go.mod
- go.sum
- pkg/session/session.go
Ports the PR #1158 to the main branch
n/a
```release-note
Adds logger statements to vSphere session cache
```
> Adds log statements to get/create session

- docs/proposal/20201103-failure-domain.md
**What this PR does / why we need it**: This PR adds the implementation details of how Failure domains should look like, it also adds some of the API changes discussed during the PR review
Fixes #
/assign @srm09 @gab-satchi 
```release-note
```
> add implementation details and API changes

- pkg/services/govmomi/vcenter/clone.go
Fixes #1189 
```release-note
Fix bug with fullClone of a VM while expanding the disk size
```
> switches disk move type to the default: moveAllDiskBackingsAndDisallowSharing

- docs/getting_started.md
- docs/identity_management.md
Fixes #1199 
```release-note
NONE
```
> documents identity management

- docs/getting_started.md
- docs/identity_management.md
- reference identity management in getting started docs
```release-note
NONE
```
> v1a4 changes to document identity management

- Makefile
- hack/e2e.sh
- hack/ensure-kubectl.sh
- hack/ipclaim-template.yaml
- test/e2e/config/vsphere-ci.yaml
- test/e2e/config/vsphere-dev.yaml
- adds ip claim and release in the setup script
needs https://github.com/kubernetes/test-infra/pull/23155 merged first to get access to the IPAM 
/hold
```release-note
NONE
```
> Switch to using kube-vip templates in CI

- docs/getting_started.md
As the branch has changed from master to main in the cluster-api repo, we need to update that in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/docs/getting_started.md?plain=1#L219
Fixes #1304 
```release-note
```
> Update branch of cluster-api from master to main

- pkg/services/govmomi/template/template.go
Fixes a minor typo in an error string.
None
None
```release-note
None
```
> Fix typo in template not found error

- api/v1alpha3/types.go
- api/v1alpha3/vspherefailuredomain_types.go
- api/v1alpha3/vspherefailuredomain_webhook_test.go
- api/v1alpha3/vspheremachine_webhook.go
- api/v1alpha3/vspheremachine_webhook_test.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_haproxyloadbalancers.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_vspherefailuredomains.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
- config/webhook/manifests.yaml
- controllers/vspheredeploymentzone_controller_domain_test.go
- pkg/services/govmomi/create_test.go
- pkg/services/govmomi/vcenter/clone_test.go
- pkg/session/session.go
Cherry pick of #1277 on release-0.7.
#1277: move datacenter defaulting to resource defaults
> Backport: move datacenter defaulting to resource defaults

- packaging/flavorgen/flavors/generators.go
- test/e2e/data/infrastructure-vsphere/capi-upgrades/v1alpha3/cluster-template.yaml
- test/e2e/data/infrastructure-vsphere/capi-upgrades/v1alpha4/cluster-template.yaml
Fixes #1314
- Upgraded to 0.4.0
- Added new / changed parameters and documentation
- Added new required capability NET_RAW see documentation at https://kube-vip.io/install_static/
> Updates Kube-vip image to v0.4.0

- controllers/vspherevm_controller.go
Cherry pick of #1272 on release-0.7.
#1272: handle nil vsphere machine for vsphere vm
```release-note
```
> Automated cherry pick of #1272: handle nil vsphere machine for vsphere vm

- Makefile
- test/e2e/capv_quick_start_test.go
- test/e2e/config/vsphere-ci.yaml
- test/e2e/config/vsphere-dev.yaml
- test/e2e/data/infrastructure-vsphere/kustomization/conformance/kustomization.yaml
- test/e2e/data/infrastructure-vsphere/kustomization/conformance/worker-node-md.yaml
- test/e2e/data/infrastructure-vsphere/kustomization/conformance/worker-node-size.yaml
- test/e2e/data/kubetest/conformance-fast.yaml
- test/e2e/data/kubetest/conformance.yaml
- test/e2e/k8s_conformance_test.go
This PR adds conformance tests to CAPV. 
Fixes #
```release-note
NONE
```
> Add conformance tests to CAPV

- hack/e2e.sh
This PR introduces dynamic creation of IP claim name. This is to avoid issues in case multiple prow jobs are running concurrently. 
```release-note
NONE
```
> dynamically create ip-claim name to avoid issues during concurrently running jobs

- docs/development.md
- hack/release.sh
This PR prepares the CAPV repo to use `main` as the default branch
Fixes #949 
```release-note
```
/hold
> 📖 Change references of branch names to main

- config/manager/manager.yaml
**What this PR does / why we need it**: 
Enables keep-alive for connections between CAPV and vCenter. This reduces load on vCenter and can prevent associated errors in CAPV logs and adverse impact on other vCenter clients.
Fixes #1503
```NONE
```
> Enable keep-alive for connections to vCenter.

- apis/v1beta1/types.go
- config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
- config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachinetemplates.yaml
- config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
Improve tagsId field description, vSphere API requires a list of URNs for batch adding of tags. We need to have a note about it on the field description.
Fixes #
```release-note
Improve tagsId field description
```
> Improve tagsId field description

- pkg/identity/identity_test.go
This PR adds unit tests to check if cluster spec identity Ref
is secret or not
Signed-off-by: geetikab@vmware.com <geetikab@vmware.com>
Co-authored-by: Ankita Swamy <swamyan@vmware.com>
Fixes #
```release-note
```
> Add unit tests for identity package

- docs/proposal/20210823-gpu-support.md
**What this PR does / why we need it**: adding @srm09  and myself as reviewers for the GPU prposal
Fixes #
```release-note
```
> add srm09 and yastij as reviewers for the gpu proposal

- Makefile
n/a
n/a
```release-note
NONE
```
> 🐛  Fixes Makefile target

- clusterctl-settings.json
- metadata.yaml
- test/e2e/config/vsphere-ci.yaml
- test/e2e/config/vsphere-dev.yaml
- test/integration/integration-dev.yaml
This PR tracks activity to cut a new release versioned 1.3.0
n/a
n/a
```release-note
NONE
```
/hold
> 🌱 Adds new version to metadata YAML file

- pkg/services/vmoperator/vmopmachine.go
CSI needs this annotation for PVC zone placement
See: https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/1626
https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/1626
Fixes #
```release-note
Set VSphereMachine.Spec.Volumes zone annotation
```
> Set VSphereMachine.Spec.Volumes zone annotation

- Dockerfile
This PR explicitly adds go mod download directive to the Dockerfile to get past build issues on the infrastructure.
Fixes #
n/a
```release-note
NONE
```
> 🌱 Adds `go mod download` directive to Dockerfile

- README.md
Update README with currently supported versions
n/a
n/a
```release-note
NONE
```
> 📖 Updates current CAPV supported versions

- pkg/util/machines.go
- pkg/util/machines_test.go
This patch fixes the logic of enqueuing requests to the `VSphereCluster` controller when `VSphereMachine` objects get changed. This is needed since the name of the `Cluster` object is different than the name of the `VSphereCluster` object in case of topology controller.
It also cleans up the unused `GetMachineInCluster()` function which can be replaced by `GetFilteredMachinesForCluster()` function from the CAPI `util` package.
Fixes #1597
_This patch alters the logic of the controller to not enqueue reconcile requests directly for the name of the provider service account objects and instead enqueue the request for the owner VSphereCluster objects._ …
> 🌱 Updates VSphereCluster reconcile request enqueue mechanism

- packaging/flavorgen/flavors/generators.go
Updates `kube-vip` to 0.5.0
Fixes #1590 
n/a
```release-note
Updates kube-vip to 0.5.0
```
> 🌱 Updates kube-vip to 0.5.0

- hack/e2e.sh
Cherry pick of #1551 on release-1.3.
#1551: Delete node explicitly upon deletion of vm
```release-note
```
> Automated cherry pick of #1551: Adds API group to e2e script

- .gitignore
- controllers/serviceaccount_controller.go
- controllers/servicediscovery_controller.go
- pkg/services/network/nsxt_provider.go
- pkg/services/vimmachine.go
- pkg/services/vmoperator/control_plane_endpoint.go
- pkg/services/vmoperator/resource_policy.go
- pkg/services/vmoperator/vmopmachine.go
Cherry pick of #1583 on release-1.3.
#1583: Switch to CreateOrPatch; ignore manager binary
```release-note
```
> Automated cherry pick of #1583: Switch to CreateOrPatch; ignore manager binary

- clusterctl-settings.json
- metadata.yaml
- test/e2e/config/vsphere-ci.yaml
- test/e2e/config/vsphere-dev.yaml
- test/integration/integration-dev.yaml
This PR tracks activity to cut a new release versioned 1.4.0
Fixes #1567 
n/a
```release-note
NONE
```
> Changes for new 1.4.0 release

- .github/workflows/verify-pr.yml
- Makefile
- RELEASE.md
- go.mod
- hack/tools/Makefile
- hack/tools/go.mod
- hack/tools/go.sum
- hack/tools/tools.go
It adds instrumentation for verifying PR with kubebuilder-release-tools
Fixes #1548 
Brings dependency on kubebuilder-release-tools
No images are affected
> :seedling: Added PR message verification with kubebuilder-release-tools

- .github/workflows/verify-pr.yml
Fixes pull request target key for Verify PR workflow
Fixes n/a
n/a
```release-note
NONE
```
> 🐛 Fixes PR verifier YAML

- main.go
This patch introduces a new flag `--tls-cipher-suites` to set the TLS cipher suites to be used by the webhook server. It uses the flag name that is exposed by the other kubernetes components, namely kube-apisever, kubelet etc.
It also updates the inputs of the minimum TLS version flag, `--tls-min-version`, of the webhook server  to match the values for a similar flag present in the other k8s components.
Fixes #1639
Ref link for kube-controller-manager flags: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
**Release …
> ✨ Updates flags for  webhook server TLS config

- packaging/flavorgen/flavors/generators.go
Updates kube-vip to `0.5.5`
Fixes #https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1662
```release-note
Updates kube-vip to 0.5.5
```
> :seedling: Update kube-vip to 0.5.5

- docs/proposal/20220929-ipam-support.md
This PR adds a proposal for adding IPAM support in CAPV.
Fixes #
```release-note
```
> 📖 Proposal for IPAM support

- controllers/serviceaccount_controller.go
- controllers/serviceaccount_controller_suite_test.go
- controllers/serviceaccount_controller_unit_test.go
Cherry pick of #1653 on release-1.4.
#1653: Creates token secret for service account
```release-note
```
> 🌱 Automated cherry pick of #1653: Creates token secret for service account

- main.go
Cherry pick of #1655 on release-1.4.
#1655: Updates flags for  webhook server TLS config
```release-note
```
> ✨ Automated cherry pick of #1655: Updates flags for webhook server TLS config

- templates/cluster-template-topology.yaml
- templates/cluster-template.yaml
**What this PR does / why we need it**: Some manifests are out of date following a kube-vip update.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: None
**Special notes for your reviewer**: Need to check if we should update the CI to ensure manifests are always up to date.
```release-note
None
```
> :seedling: Run `make generate`

- clusterctl-settings.json
- metadata.yaml
- test/e2e/config/vsphere-ci.yaml
- test/e2e/config/vsphere-dev.yaml
- test/integration/integration-dev.yaml
This PR tracks activity to cut a new release versioned 1.5.0
Fixes #1567 
n/a
```release-note
Changes for new minor release v1.5.0
```
> 🌱 Changes for new minor release v1.5.0

- .github/dependabot.yml
Adds dependabot configuration
Fixes n/a
n/a
```release-note
NONE
```
> ✨ Adds dependabot configuration

- controllers/vspherevm_controller.go
- controllers/vspherevm_controller_test.go
Adds the check for the state of the anti affinity feature flag when reconciling VM. When reconciling the VM, the cluster module info should be looked up only when the NodeAntiAffinity feature flag is turned on. This also solves the issue when the control plane provider is something other than the KubeadmControlPlane, in which case we do not want to allow checks for cluster module info.
Fixes #1702 
n/a
```release-note
Checks for feature flag during VM reconciliation
```
> 🌱 Checks for feature flag during VM reconciliation

- Makefile
- hack/release.sh
Uses docker build targets for release scripts to reduce repeating logic introduced in #1505. This also makes the release script publish arm64 images for users on m1 macs.
Fixes #
```release-note
publishes arm64 images with release
```
> :seedling: chore: publishes arm64 images with release

- pkg/services/govmomi/vcenter/clone.go
This PR fixes the issue that VMs are not cloned in linked clone mode regardless of the `cloneMode` in `VSphereMachineTemplate` manifest.
To clone VMs in linked-clone mode, `DiskMoveType` should be specified to `CreateNewChildDiskBacking`.
`DiskMoveType` appears in both `VirtualMachineRelocateSpec` and `VirtualMachineRelocateSpecDiskLocator` and the former is specified correctly, but as of now the later is specified to `MoveAllDiskBackingsAndDisallowSharing`, which is not compatible with linked clone.
Fixes #1611
_Please confirm that if this PR changes any …
> :bug: Fixes issue that linked clone does not work

- docs/node-ipam-demo.md
This PR adds a doc detailing how to use Node IPAM features.
```release-note
NONE
```
> 📖  Add doc detailing node ipam usage

- apis/v1beta1/vspherevm_types.go
- config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
Adds missing category to the VSphereVM CRD.
Fixes #1799 
n/a
```release-note
Adds missing category to the VSphereVM CRD.
```
> ⚠️ Adds missing category field to VSphereVM CRD

- controllers/vspherecluster_reconciler_test.go
Fixes the flaky test that keeps failing on the `pull-cluster-api-provider-vsphere-test` pre submit prow job for the PRs.
Fixes #1820 
A little context on what the intention of the test was:
On `VSphereCluster` deletion, the secret used by the cluster also ends up getting deleted. This secret had the legacy finalizer added to it as well (which we stopped using after v1alpha3). Any cluster secrets created after `v1alpha3` API version, do not have this finalizer set on it.
Now for the actual failure, the test was testing the deletion workflow of the cluster …
> 🐛 test: Fixes flaky test for finalizer deletion

- metadata.yaml
Adds metadata for the v1.7.0 release
n/a
n/a
```release-note
NONE
```
> 🌱  Adds metadata for v1.7.0 release

- .github/workflows/scan.yaml
- Makefile
- hack/verify-container-images.sh
This PR adds a periodic github job to perform trivy scanning. This should help in surfacing any CVEs in the code base early in the cycle and can act as an early signal.
Fixes #
```release-note
```
> 🌱 add periodic Github job for trivy scanning

- controllers/vspherecluster_reconciler.go
- controllers/vspherecluster_reconciler_test.go
Creating a non-multi-az cluster in a multi-az enabled environment still forces the control plane nodes to be deployed into multiple AZs.
In this PR, will support non-multi-az workload cluster deployment in a multi-az enabled management cluster by nil selector.
Fixes #1950
```release-note
Support non-multi-az cluster deployment in a multi-az enabled env
```
> 🐛 Support non-multi-az cluster deployment in a multi-az enabled env

- config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
This is required to unblock v1.5 PRs now that we fixed the categories flake.
Fixes #
```release-note
```
> [release-1.5] 🌱 Add categories to vspherevm CRD YAML

- pkg/services/govmomi/vcenter/clone.go
Disable the vAppConfig during VM creation to ensure Cloud-Init inside of the guest does not activate and prefer the OVF datasource over the VMware datasource.
Fixes #1746 
```release-note
Disable vAppConfig during VM creation
```
> ✨ Disable vAppConfig during VM creation

- go.mod
- go.sum
- test/e2e/config/vsphere-ci.yaml
- test/e2e/config/vsphere-dev.yaml
- test/integration/integration-dev.yaml
Bumps CAPI dependency to v1.5.0-rc.1 which should be the final RC.
Fixes #
```release-note
```
> 🌱 Bump CAPI to v1.5.0-rc.1

- pkg/session/session.go
This is an manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1949
```release-note
NONE
```
> [release-1.6] 🐛 Don't call session logout for keepAliveHandler

- hack/e2e.sh
Lot's of e2e CI jobs failed fast with the following error:
```
ipclaim.ipam.metal3.io/ip-claim-0e869fd5082c7413eaadc42d54b26bb27569c203 created
Acquired Control Plane IP: 192.168.6.254
ipclaim.ipam.metal3.io/workload-ip-claim-81ba2a87a03045ce899fe07df55d5f17ae6ce671 created
error: resource name may not be empty
```
`error: resource name may not be empty` comes from trying to get a resource without a name, e.g. `kubectl get pod ""`.
In our `hack/e2e.sh` script this could happen at two places while claiming IP addresses:
When `IPADDRESS_NAME` or `WORKLOAD_IPADDRESS_NAME` are an empty string and using them in one of the following occurencies:
* https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/a9ae01e7a505712399957bce3a20b29f59038df1/ …
> 🐛 hack/e2e.sh: retry getting ipaddress object name

- test/e2e/config/vsphere-ci.yaml
- test/e2e/config/vsphere-dev.yaml
Manual cherry-pick of #2016
As discussed in office hours :-)
> 🌱 [CI]: Updates CI template to k8s 1.27.3

- controllers/vspherecluster_reconciler.go
As the cluster.spec.failureDomainSelector is a real K8s label selector, it can be used when listing the deployment zones directly.
This way, instead of having a full list to iterate and check if the label match on every interaction, we can be already sure the returned list contains only the deployment zones we care about 
Fixes #
```release-note
NONE
```
> :seedling: Improve fd selection logic

- Makefile
- go.mod
- go.sum
- test/e2e/config/vsphere-ci.yaml
- test/e2e/config/vsphere-dev.yaml
- test/integration/integration-dev.yaml
Fixes #2074
```release-note
Bump sigs.k8s.io/cluster-api to v1.5.0
```
> 🌱 Bump CAPI to v1.5.0

- metadata.yaml
Updates the metadata.yaml according to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/releasing.md prior to creating the first pre-release for the v1.8 series.
Fixes #
```release-note
NONE
```
> 🌱 Prepare metadata.yaml for v1.8 release series

- main.go
Aligns flags to the ones used in CAPI:
- adds the flag `--leader-elect-lease-duration`
- adds the flag `--leader-elect-renew-deadline`
- adds the flag `--leader-elect-retry-period`
- adds the flag `--contention-profiling`
- adds the flag `--kube-api-qps`
- adds the flag `--kube-api-burst`
- adds the flag `--webhook-cert-dir`
- replaces the profiler webserver by the controller-runtime provided one in `main.go`
Fixes #2072
Detailed diff in help output:
```diff
0a1
>       --contention-profiling                     Enable block profiling, if profiler-address is …
```
> 🌱 align flags with CAPI

- clusterctl-settings.json
This is barely used, but let's keep it up-to-date for now
(only for OVERRIDES_DIR => make dev-manifests / make dev-flavors)
Fixes #
> 🌱 Bump version to v1.8 in clusterctl-settings

- CONTRIBUTING.md
Fixes #
```release-note
NONE
```
> :book: CONTRIBUTING.md: Clarify contribution ladder

- Makefile
> 🌱 Also add release notes to pre releases

- Makefile
> [release-1.7] 🌱 Bump to Go 1.19.12

- Makefile
> [release-1.6] 🌱 Bump to Go 1.19.12

- Makefile
This is a manual cherry-pick of:
- #2139
- #2138
> [release-1.7] 🌱 bump kpromo and fix release-notes target

- Makefile
This is a manual cherry-pick of:
- #2139
- #2138
> [release-1.6] 🌱 bump kpromo and fix release-notes target

- Makefile
This is a manual cherry-pick of:
- #2139
- #2138
> [release-1.5] 🌱 bump kpromo and fix release-notes target

- go.mod
- go.sum
> 🌱 Bump to vm-operator/api v1.8.2

- config/manager/manager.yaml
- controllers/vspherecluster_reconciler.go
- controllers/vspheredeploymentzone_controller.go
- controllers/vspherevm_controller.go
- main.go
- pkg/clustermodule/session.go
- pkg/constants/constants.go
- pkg/session/session.go
Manual cherry-pick to resolve conflicts
Fixes #2193
> [release-1.5] ✨ Re-introduce the keep alive flag

- CONTRIBUTING.md
> 📖 Fix link in CONTRIBUTING.md

- .github/workflows/pr-md-link-check.yaml
Set base branch correctly for link checker
> [release-1.5] 🌱 Set base branch correctly for link checker

- docs/release/release-tasks.md
Add task to update mdlink check config for branches to release.md.
> :seedling: Add task to update mdlink check config for branches

- test/e2e/config/vsphere-ci.yaml
- test/e2e/config/vsphere-dev.yaml
> 🌱 Use Ubuntu 22.04 for e2e tests

- controllers/vmware/vspherecluster_reconciler.go
- controllers/vspherecluster_controller.go
- controllers/vspheremachine_controller.go
- controllers/vspherevm_controller.go
> 🌱 Avoid adding watches after building controllers

- pkg/services/govmomi/vcenter/clone.go
Cherry pick of #2134 for release v1.6
/assign @sbueringer
> [release-1.6] 🐛 StoragePolicy should select datastore based on connected hosts and set on VM spec 

- pkg/services/govmomi/vcenter/clone.go
Cherry-pick of #2134 for CAPV 1.7
Fixes #
> [release-1.7] 🐛 StoragePolicy should select datastore based on connected hosts and set on VM spec 

- test/e2e/config/vsphere-ci.yaml
- test/e2e/config/vsphere-dev.yaml
> 🌱 Bump ccm to 1.28.0

- packaging/flavorgen/flavors/env/envsubts_consts.go
- templates/cluster-template-ignition.yaml
- templates/cluster-template-node-ipam.yaml
- templates/cluster-template-topology.yaml
- templates/cluster-template.yaml
- test/e2e/data/infrastructure-vsphere/main/ignition/ignition.yaml
1. Revise the assignment of the default value for `VIP_NETWORK_INTERFACE`.
Fixes #2279
> 🌱 flavor-gen: fix environment value VIP_NETWORK_INTERFACE default assign

- go.mod
- go.sum
> [release-1.8] 🌱 Bump to CAPI v1.5.1

- docs/release/release-tasks.md
> 📖 docs: fix release-tasks to refer the correct repository

- apis/v1beta1/vspherecluster_types.go
- config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
- config/default/crd/bases/infrastructure.cluster.x-k8s.io_vsphereclustertemplates.yaml
> 🌱 Improve godoc for VSphereCluster.spec.failureDomainSelector

- Dockerfile
- Makefile
- hack/ensure-go.sh
> [release-1.6]🌱 Bump to Go 1.19.13

- Dockerfile
- Makefile
- hack/ensure-go.sh
> [release-1.5]🌱 Bump to Go 1.19.13

- Dockerfile
- Makefile
- hack/ensure-go.sh
> [release-1.7] 🌱 Bump to Go 1.19.13

- Dockerfile
- Makefile
- go.mod
- go.sum
- hack/ensure-go.sh
> 🌱 [release-1.6] Bump to Go 1.20.8

- Dockerfile
- Makefile
- go.mod
- go.sum
- hack/ensure-go.sh
> 🌱 [release-1.5] Bump to Go 1.20.8

- test/e2e/anti_affinity_test.go
Manual cherry-pick of #2377
Fixes #
> [release-1.8] 🌱 Use number of esxi hosts as worker node count for anti-affinity e2e test

- hack/e2e.sh
- hack/ipclaim-template.yaml
Replaces the usage of ipam.metal3.io by in https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster .
/assign @killianmuldoon 
Fixes #
> 🌱 CI: replace metal3 ipam by CAPI in-cluster provider

- pkg/services/vmoperator/vmopmachine.go
Resolving open comments from #2395
Fixes #
> 🌱 Removal of if block usage wrt logging in vsphere machine controller

- go.mod
- go.sum
- pkg/services/govmomi/service.go
- pkg/services/govmomi/service_test.go
- pkg/services/govmomi/storageprofile_util.go
> [release-1.8] :bug: Use a less expensive method for storage policy

- test/e2e/data/infrastructure-vsphere/main/base/kustomization.yaml
> 🌱 Add comment about why we drop the storage policy for some e2e tests

- tilt-provider.json
Aligning with the list of folders where the CAPV manager code is read from
> 🌱 Fix live reload settings for Tilt

- pkg/services/vmoperator/vmopmachine.go
- pkg/services/vmoperator/vmopmachine_test.go
- pkg/util/testutil.go
> 🐛 [release-1.8] Skip updating immutable VMOp fields

- pkg/services/vmoperator/vmopmachine.go
- pkg/services/vmoperator/vmopmachine_test.go
- pkg/util/testutil.go
> 🐛 [release-1.7] Skip updating immutable VMOp fields

- pkg/services/vmoperator/vmopmachine.go
- pkg/services/vmoperator/vmopmachine_test.go
> 🌱 [release-1.7] Prevent updating supervisors VSphereMachine.Spec.ResourcePolicyName

- pkg/services/vmoperator/vmopmachine.go
- pkg/services/vmoperator/vmopmachine_test.go
> 🌱 [release-1.8] Prevent updating supervisors VSphereMachine.Spec.ResourcePolicyName

- .github/workflows/weekly-md-link-check.yaml
- .github/workflows/weekly-security-scan.yaml
- .github/workflows/weekly-test-release.yaml
> 🌱 github: add release-1.9 to weekly actions and remove release-1.5

- .github/workflows/pr-md-link-check.yaml
> 🌱 github: update md-link check action for release-1.9

- main.go
> 🌱 Fail startup if no CRDs are detected

- test/framework/ip/incluster.go
Fixes https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/2594/pull-cluster-api-provider-vsphere-e2e-conformance-ci-latest-main/1750934298652839936
Fixes #
> 🌱 test: change labels used for creating IPAddressClaims to not hit the 63 characters length limit

- test/framework/ip/incluster.go
Fixes the error handling. Using errors.Wrap with a nil error results in not returning an error. In this case we want to create a new error which was why the errors were not bubbled up and the tests continued without any IP.
Fixes #
> 🌱 test: fix error handling in incluster ip provider

- hack/e2e.sh
> [release-1.9] 🌱 e2e: only upload images to gcs if we run tests which need it

- test/e2e/data/infrastructure-vsphere/main/install-on-bootstrap/inject-install-on-bootstrap.yaml
Follow-up fix for #2594
Fixes #
/test help
> 🌱 Use pkgs.k8s.io for apt

- test/e2e/data/infrastructure-vsphere/main/install-on-bootstrap/inject-install-on-bootstrap.yaml
> 🌱 test: fix inject install on bootstrap script

- test/framework/vmoperator/vmoperator.go
- test/framework/vmoperator/vmoperator_test.go
- test/infrastructure/vcsim/controllers/envvar_controller.go
- test/infrastructure/vcsim/controllers/vcsim_controller.go
Make VirtualMachineClass configurable when using vcsim
> 🌱 Make VirtualMachineClass configurable when using vcsim

- test/e2e/cluster_upgrade_test.go
> [release-1.9] 🌱 test: use 5 worker nodes for k8s upgrade + conformance test

- hack/clean-ci.sh
Adds a script for clean-ci to connect via VPN and run `make clean-ci`.
Fixes #
> 🌱 hack: add script to run clean-ci using vpn via prow

- Makefile
> 🌱 Bump kpromo to v4.0.5

- .github/workflows/cover.yaml
- .golangci.yml
- Makefile
- hack/ensure-go.sh
> [release-1.9] 🌱 Bump to Go 1.21

- .github/workflows/pr-golangci-lint.yaml
- .golangci.yml
- Makefile
- hack/ensure-go.sh
- pkg/services/govmomi/util_test.go
- pkg/services/network/nsxt_provider.go
- pkg/services/vmoperator/vmopmachine_test.go
> [release-1.8] 🌱 Bump to Go 1.21

- README.md
> 📖 README.md: fix formatting

- controllers/vmware/test/controllers_test.go
> 🌱 [release-1.8] controllers/vmware fix test to not contain data race

- test/e2e/data/kubetest/conformance-fast.yaml
- test/e2e/data/kubetest/conformance.yaml
Aligns to CAPI: https://github.com/kubernetes-sigs/cluster-api/issues/10171
Fixes #
> 🌱 test: Replace deprecated ginkgo flags

- controllers/svcdiscovery_controller_intg_test.go
Fix flakyness on test.
The service discrovery controller may already create the supervisor kubernetes service. In that case we only update the object.
Testgrid links:
- [periodic 1.7](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#periodic-test-release-1-7)
- [periodic 1.6](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#periodic-test-release-1-6)
Fixes #
> [release-1.7] 🐛 controllers: update the service in tests if it already exists

- .github/workflows/release.yaml
> 🌱 Add GitHub token for release notes action

- go.mod
- go.sum
- test/go.mod
- test/go.sum
> 🌱 Bump govmomi to v0.36.3

- Makefile
- go.mod
- go.sum
- test/go.mod
- test/go.sum
xref: https://groups.google.com/g/golang-announce/c/YgW0sx8mN3M
Fixes #
> 🌱 Bump golang to v1.21.9 and golang.org/x/net to mitigate CVE-2023-45288

- README.md
> 🌱 Link to new meeting notes

- .github/workflows/cover.yaml
codecov started to permanently fail on PRs with this error message:
> Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
I've now added a secret to the repository, but this won't work for PRs opened from forks. That's why we're dropping this action for PRs (it will still run against main to provide us data on test coverage of the main branch over time). …
> 🌱 Drop codecov from PRs, add token for main

- .github/workflows/cover.yaml
> 🐛 Fixup codecov action

- .github/workflows/pr-golangci-lint.yaml
> :seedling: bump golangci-lint to v1.57.2

- main.go
- pkg/constants/constants.go
For more details see: https://kubernetes.slack.com/archives/CKFGK3SSD/p1704964502960379?thread_ts=1704729665.056699&cid=CKFGK3SSD
Fixes #
> 🌱 Deprecate and disable keep alive handler for vSphere sessions

- .github/workflows/pr-md-link-check.yaml
We did just cut the release branch for the upcoming v1.10 release.
part of: [kubernetes-sigs/cluster-api-provider-vsphere@main/docs/release/release-tasks.md#create-a-release-branch](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/release/release-tasks.md?rgh-link-date=2024-04-12T14%3A06%3A49Z#create-a-release-branch)
Fixes #
> 🌱 github: adjust md-link check to refer release-1.10 branch

- README.md
Documents the migration os OVAs / templates over to Github releases.
Fixes #
> 📖 README: move links for templates over to github releases

- Makefile
Not entirely sure if this will work (permissions), but let's try :) 
Fixes #
> 🌱 Store nightly manifests in k8s-staging-capi-vsphere

- Makefile
Forgot to update a comment in #2930
Fixes #
> 🌱 Update Makefile doc about nightly manifests

- test/e2e/clusterctl_upgrade_test.go
- test/e2e/config/vsphere.yaml
Use release markers in e2e config to fetch the lastest releases. Please find more details in #2549 
Part of #2549
> 🌱 Use release markers in e2e config to fetch lastest releases

- config/manager/manager.yaml
This was missed in #2896
Fixes #2946
> 🐛 config: drop the deprecated --enable-keep-alive flag from the template

- Makefile
Same as https://github.com/kubernetes-sigs/cluster-api/pull/10521
Fixes #
> 🌱 Push manifests for main & release-.*

- README.md
manual cherry-pick of
* #2958
* #2641
> [release-1.10] 📖 README.md cherry-pick changes related to vm templates

- README.md
manual cherry-pick of
* #2958
* #2641
> [release-1.7] 📖 README.md cherry-pick changes related to vm templates

- README.md
manual cherry-pick of
* #2958
* #2641
> [release-1.9] 📖 README.md cherry-pick changes related to vm templates

- docs/ignition.md
Synced with the same file on >= release-1.0
This should fix the remaining broken links
Fixes #
> [release-1.9] 📖 Drop direct link to OVA in ignition.md

- .github/dependabot.yml
See https://github.com/kubernetes-sigs/cluster-api/pull/10571
Fixes #
> 🌱 Optimize dependabot config

- config/manager/manager.yaml
- test/infrastructure/net-operator/config/manager/manager.yaml
- test/infrastructure/vcsim/config/manager/manager.yaml
See: https://github.com/kubernetes-sigs/cluster-api/pull/10580
Just seems to make sense
Fixes #
> 🌱 Set terminationMessagePolicy to FallbackToLogsOnError for all managers

- .golangci.yml
- Makefile
- hack/e2e.sh
- test/e2e/clusterctl_upgrade_test.go
- test/e2e/config/vsphere-ci.yaml
- test/e2e/config/vsphere-dev.yaml
- test/e2e/data/infrastructure-vsphere/main/remote-management/image-injection.yaml
- test/e2e/data/infrastructure-vsphere/main/remote-management/kustomization.yaml
- test/framework/daemonset_helpers.go
- test/framework/image_preloading.go
- test/go.mod
- test/go.sum
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2955
> [release-1.9] 🌱 test: use a daemonset and kubectl exec to provide images to remote clusters

- controllers/serviceaccount_controller_intg_test.go
- controllers/svcdiscovery_controller_intg_test.go
- test/helpers/vmware/intg_test_context.go
> [release-1.8] 🌱 controllers: fix ProviderServiceAccount tests to create objects on-demand

- controllers/serviceaccount_controller_intg_test.go
- controllers/svcdiscovery_controller_intg_test.go
- test/helpers/vmware/intg_test_context.go
> [release-1.7] 🌱 controllers: fix ProviderServiceAccount tests to create objects on-demand

- hack/e2e.sh
Manual cherry-pick of #2989
Also syncs e2e.sh as good as possible to what we have on main.
> [release-1.9] 🌱 hack/e2e don't add binary files to artifacts and also censor base64 encoded values

- test/e2e/clusterclass_changes_test.go
- Enable test "When testing ClusterClass changes"
Part of #2995
> 🌱 Fill up supervisor e2e test - ClusterClass changes

- docs/node-ipam-demo.md
Fixes broken ova link since removing ova templates from the old location.
Fixes #
> 📖 docs: fix broken ova link

- hack/e2e.sh
- test/e2e/config/vsphere-ci.yaml
Manual, minimal cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3034
Fixes #
> [release-1.8] ✨ test/e2e: use vSphere projects from Boskos

- hack/e2e.sh
- test/e2e/config/vsphere-ci.yaml
Manual, minimal cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3034
Fixes #
> [release-1.7] ✨ test/e2e: use vSphere projects from Boskos

- Makefile
> 🌱 Makefile: add hack/tools to go test

- .github/workflows/pr-golangci-lint.yaml
- test/framework/log/collector.go
> 🌱 Bump to golangci-lint v1.59.0

- Makefile
> 🌱 Bump to Go 1.22.5

- pkg/services/vmoperator/vmopmachine.go
This makes our code resilient in case VirtualMachine conditons for pre-requisites changes after a VM is provisioned
> 🌱 Test VirtualMachine pre-requisites only before creation

- .github/workflows/weekly-md-link-check.yaml
- .github/workflows/weekly-security-scan.yaml
- .github/workflows/weekly-test-release.yaml
> 🌱 Add release-1.11 to GitHub actions

- packaging/flavorgen/flavors/crs/util.go
- packaging/flavorgen/flavors/env/envsubts_consts.go
- packaging/flavorgen/flavors/util/helpers.go
- templates/cluster-template-external-loadbalancer.yaml
- templates/cluster-template-ignition.yaml
- templates/cluster-template-node-ipam.yaml
- templates/cluster-template-topology.yaml
- templates/cluster-template.yaml
- test/e2e/config/vsphere-ci.yaml
> 🌱 [release-1.8] test: add env var to allow setting CPI to insecure and use it in CI

- pkg/util/testutil.go
> 🌱 testutil: fix import name for fake client library

- README.md
> 📖 README.md update supported versions to CAPI v1.8

- .golangci.yml
Was checking for "deprecate" and saw these very brought excludes
Fixes #
> 🌱 golangci-lint: only exclude specific deprecations

- go.mod
- go.sum
- pkg/services/network/network_test.go
- pkg/services/network/nsxt_vpc_provider.go
- test/go.sum
This is the final version of API SubnetSet.
Fixes #
> 🌱 Bump nsx-operator API mod

- .github/workflows/pr-verify.yaml
- hack/verify-pr-title.sh
Same change as in core CAPI
Fixes #
> 🌱 Verify PR titles with shell script

- README.md
Updates the CAPV office hour time, as discussed in the office hours / announced in Slack
Fixes #
> 📖 Update CAPV meeting time

- packaging/flavorgen/cloudprovider/csi/vsphere-csi-driver.yaml
- templates/cluster-template-external-loadbalancer.yaml
- templates/cluster-template-ignition.yaml
- templates/cluster-template-node-ipam.yaml
- templates/cluster-template-supervisor.yaml
- templates/cluster-template-topology-supervisor.yaml
- templates/cluster-template-topology.yaml
- templates/cluster-template.yaml
- test/e2e/data/infrastructure-vsphere-govmomi/v1.10/topology/cluster-template-topology.yaml
- test/e2e/data/infrastructure-vsphere-govmomi/v1.9/topology/cluster-template-topology.yaml
- test/e2e/data/infrastructure-vsphere-supervisor/v1.10/topology/cluster-template-topology-supervisor.yaml
- test/e2e/data/infrastructure-vsphere-supervisor/v1.9/topology/cluster-template-topology-supervisor.yaml
Manual cherry-pick of #3200 
Fixes #
> 🌱 [release-1.11] csi: use images from new location

- .github/workflows/pr-verify.yaml
Co-Authored-By: Aviv Keller <redyetidev@gmail.com>
Uses an environment variable for the pr-verifier.
Thanks to @RedYetiDev for reporting!
Fixes #
> 🌱 pr-verify: use env var for passing the PR title

- main.go
- pkg/manager/constants.go
I diffed CAPI's main.go and CAPV's, found this diff in the flags.
Fixes #
> 🌱 main.go: add flags for webhook cert-name and -key

- test/framework/vmoperator/vmoperator.go
Partial cherry-pick from #3059
> 🌱 [release-1.10] Improve ReconcileDependencies for VM Operator to handle concurrency on availabityZone changes

- pkg/session/session.go
> ✨ govmomi: support vCenter 9

- test/e2e/config/vsphere.yaml
> 🌱 Bump CPI to v1.32.0-beta.1

- go.mod
- go.sum
- packaging/go.sum
- test/go.sum
> ✨Bump nsx-operator API mod for the SubnetSet change

- .github/workflows/weekly-md-link-check.yaml
- .github/workflows/weekly-security-scan.yaml
- .github/workflows/weekly-test-release.yaml
Part of 1.12-rc.0 release tasks
> 🌱 Update branch matrix for weekly GitHub actions

- test/e2e/config/vsphere.yaml
> 🌱 CI: Bump Kubernetes version to v1.32.0-rc.0

- test/e2e/config/vsphere.yaml
…-base-branch
[release-1.12] 🌱 Set base branch correctly for link checker
Fixes #
> [release-1.12] 🌱 test: do not test latest-1.33 on 1.12 branch

- Makefile
> 🌱 [release-1.11] Bump go v1.22.10

- test/e2e/config/vsphere.yaml
> 🌱 [release-1.12] Bump kubernetes release to v1.32.0-rc.1

- hack/create-mirror-repository-pr.sh
> 🌱 hack: make create-mirror-repository-pr.sh executable and easier to use

- Makefile
- go.mod
- go.sum
- packaging/go.mod
- packaging/go.sum
- test/e2e/config/vsphere.yaml
- test/go.mod
- test/go.sum
* Bump sigs.k8s.io/cluster-api to v1.9.1
Fixes #
> 🌱 Bump sigs.k8s.io/cluster-api to v1.9.1

- Makefile
This includes a commit which then only checks out only a single commit instead of downloading the whole repository.
This makes the promo process way faster (and even makes it work at all on my bad internet connection)
xref: https://github.com/kubernetes-sigs/promo-tools/pull/1409
I'm also asking upstream for a new release but no traction on that yet :-) (xref: https://kubernetes.slack.com/archives/C2C40FMNF/p1734459016016769 )
Fixes #
> 🌱 Bump kpromo to 5ab0dbc74b0228c22a93d240596dff77464aee8f

- .github/ISSUE_TEMPLATE/release_tracking.md
- test/e2e/config/config-overrides-example.yaml
- test/e2e/config/vsphere.yaml
Tests on the mirror: https://github.com/team-cluster-api/cluster-api-provider-vsphere/pull/53
Fixes #
> 🌱 Minor fixups vsphere.yaml's

- test/e2e/data/infrastructure-vsphere-govmomi/main/install-on-bootstrap/inject-install-on-bootstrap.yaml
- test/e2e/data/infrastructure-vsphere-supervisor/main/install-on-bootstrap/inject-install-on-bootstrap.yaml
periodics are failing because of failing signature checks for apt.
Fixes #
> [release-1.10] 🌱 Cherry-pick install script from main which does not use apt

- test/e2e/e2e_setup_test.go
> 🌱 Cleanup copy of CopyAndAmendClusterctlConfig

- Makefile
> [release-1.12] 🌱 Bump to Go 1.22.11

- Makefile
> [release-1.11] 🌱 Bump to Go 1.22.11

- Makefile
> [release-1.10] 🌱 Bump to Go 1.22.11

- Makefile
> 🌱 Align ginkgo flags to core CAPI

- Makefile
Fix some CVEs: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/13240338353/job/36954115559
Fixes #
> 🌱 Bump to Go 1.23.6

- Makefile
> [release-1.12] 🌱 Bump to Go 1.22.12

- Makefile
> [release-1.10] 🌱 Bump to Go 1.22.12

- Makefile
> [release-1.11] 🌱 Bump to Go 1.22.12

- test/e2e/scale_test.go
> 🌱 scale: reduce replicas and amount of clusters as we test upgrades too to reduce load

- controllers/vspherecluster_reconciler.go
- controllers/vspherecluster_reconciler_test.go
Fixes a test-flake occuring since:
- #3388
xref: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-cluster-api-provider-vsphere-test-main/1900193124035072000
```
{Timed out after 30.073s.
Expected
<bool>: false
to be true failed [FAILED] Timed out after 30.073s.
Expected
<bool>: false
to be true
In [It] at: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-vsphere/controllers/vspherecluster_reconciler_test.go:308 @ 03/13/25 14:40:01.629
}
```
Note: reproducible by adding a time.Sleep just before the deletion, so the finalizer gets added before deleting again.
Fixes #
> 🌱 controllers: fix vspherecluster test flake on vspherecluster deletion

- test/e2e/config/vsphere.yaml
> 🌱 Bump CPI to v1.33.0-beta.0

- hack/ci-e2e-lib.sh
- test/e2e/clusterctl_upgrade_test.go
- test/e2e/config/vsphere.yaml
How to build an image and push it to the cache target registry:
```sh
VERSION=v1.32.0
for arch in arm64 amd64; do
kind build node-image --arch "${arch}" --type release --image "gcr.io/k8s-staging-capi-vsphere/extra/kindest/node-${arch}:${VERSION}" "${VERSION}"
done
for arch in arm64 amd64; do
docker push "gcr.io/k8s-staging-capi-vsphere/extra/kindest/node-${arch}:${VERSION}"
done
docker manifest create \
gcr.io/k8s-staging-capi-vsphere/extra/kindest/node:${VERSION} \
--amend gcr.io/k8s-staging-capi-vsphere/extra/kindest/node-amd64:${VERSION} \
--amend gcr.io/k8s-staging-capi-vsphere/extra/kindest/node-arm64:${VERSION}
docker manifest push gcr.io/k8s-staging-capi-vsphere/extra/kindest/node:${VERSION}
```
**Which issue(s) this PR fixes** *(optional, …
> 🌱 hack: try to pull from gcr.io/k8s-staging-capi-vsphere/extra/ instead of docker hub

- apis/v1beta1/vspheremachine_types.go
- apis/v1beta1/vspherevm_types.go
- apis/vmware/v1beta1/vspheremachine_types.go
- config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspheremachines.yaml
- config/default/crd/bases/infrastructure.cluster.x-k8s.io_vspherevms.yaml
- config/supervisor/crd/bases/vmware.infrastructure.cluster.x-k8s.io_vspheremachines.yaml
- controllers/vspheremachine_controller.go
- controllers/vspherevm_controller.go
- controllers/vspherevm_ipaddress_reconciler.go
- pkg/context/interfaces.go
- pkg/context/machine_context.go
- pkg/context/vm_context.go
- pkg/context/vmware/machine_context.go
- pkg/services/govmomi/power.go
- pkg/services/govmomi/service.go
- pkg/services/govmomi/util.go
- pkg/services/vimmachine.go
- pkg/services/vmoperator/vmopmachine.go
More work on v1beta2 conditions
> 🌱 Add v1beta2 conditions to VSphereMachine and VSphereVM

- .github/workflows/pr-md-link-check.yaml
- .github/workflows/weekly-md-link-check.yaml
- .github/workflows/weekly-security-scan.yaml
- .github/workflows/weekly-test-release.yaml
- docs/release/release-tasks.md
Preparing for release-1.13. We added the branch.
Fixes #
> 🌱 Adjust weekly gh actions to run for release-1.13 branch

- Makefile
- go.mod
- go.sum
- packaging/go.mod
- packaging/go.sum
- test/e2e/config/vsphere.yaml
- test/go.mod
- test/go.sum
Bumps:
* CAPI to `v1.10.0-rc.1`
* Bump K8s to `v1.33.0-rc.0`
* Bump CPI to `v1.33.0-rc.0`
Fixes #
> 🌱 Bump CAPI to v1.10.0-rc.1, K8S and CPI to v1.33.0-rc.0

- Makefile
- go.mod
- go.sum
- packaging/go.mod
- packaging/go.sum
- test/e2e/config/vsphere.yaml
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI v1.10.0

- internal/test/helpers/vcsim/model.go
- packaging/flavorgen/cloudprovider/cpi/cpi.yaml
- test/e2e/config/config-overrides-example.yaml
- test/e2e/config/vsphere.yaml
- test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass/patch-vsphere-template.yaml
- test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-vsphere-template.yaml
Bumps k8s to test v1.33.0
Fixes #
Part of #3307
> ✨ Bump Kubernetes to v1.33 and add new OVA's

- internal/test/helpers/vcsim/model.go
- packaging/flavorgen/cloudprovider/cpi/cpi.yaml
- test/e2e/config/config-overrides-example.yaml
- test/e2e/config/vsphere.yaml
- test/e2e/data/infrastructure-vsphere-govmomi/main/clusterclass/patch-vsphere-template.yaml
- test/e2e/data/infrastructure-vsphere-supervisor/main/clusterclass/patch-vsphere-template.yaml
Manual cherry pick of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3435
> 🌱 Bump Kubernetes to v1.33 and add new OVA's

- Makefile
- go.mod
- go.sum
- packaging/go.mod
- packaging/go.sum
- test/e2e/config/vsphere.yaml
- test/go.mod
- test/go.sum
> 🌱 Bump CAPI v1.10.1

- Makefile
- go.mod
- go.sum
- packaging/go.mod
- packaging/go.sum
- test/e2e/config/vsphere.yaml
- test/go.mod
- test/go.sum
> [release1-13] 🌱 Release 1.13 bump capi v1.10.1

- Makefile
Align with go version used in CAPI
Fixes #
> [release-1.13] 🌱 Bump go 1.23.8

- Makefile
Align with go version used in CAPI
Fixes #
> 🌱 Bump go 1.23.8

- test/e2e/config/vsphere.yaml
> 🌱 Use release artefacts for CAPI v1.10

- Makefile
> [release-1.11] 🌱 Bump govulncheck to v1.1.4

- .github/workflows/pr-golangci-lint.yaml
- .golangci.yml
- Makefile
- controllers/vspherecluster_reconciler.go
- controllers/vspherecluster_reconciler_test.go
- controllers/vspheremachine_controller_test.go
- packaging/flavorgen/flavors/clusterclass_generators.go
- pkg/services/govmomi/ipam/status_test.go
- test/e2e/multivc_test.go
- test/e2e/scale_test.go
- test/framework/ip/vcsim.go
> 🌱 Migrate config and bump golangci lint to v2

- Makefile
Better spread for main jobs: https://github.com/kubernetes/test-infra/pull/34960
Fixes #
> 🌱 prowjobs: reschedule main periodics at 23 and 1 UTC

- hack/e2e.sh
> 🌱 hack: debug vsphere connectivity

- test/e2e/data/cni/calico/calico.yaml
> :seedling: e2e: pull calico from a gcr.io mirror

- Makefile
- go.mod
- go.sum
- packaging/go.mod
- packaging/go.sum
- test/e2e/config/vsphere.yaml
- test/go.mod
- test/go.sum
> 🌱 Bump to CAPI v1.11.0-alpha.2

- .trivyignore
Same as https://github.com/kubernetes-sigs/cluster-api/pull/12508
Fixes #
> 🌱 Add CVE-2025-22868 to Trivy ignore file

- README.md
> 📖 Fix broken link to kubicorn

- test/e2e/config/vsphere.yaml
> ✨ Bump to CPI v1.34.0-rc.0

- Makefile
> 🌱 Bump to Go v1.24.6

- hack/govc-install.sh
> 🌱 Add retry for govc binary download during tests

- .github/workflows/weekly-md-link-check.yaml
- .github/workflows/weekly-security-scan.yaml
- .github/workflows/weekly-test-release.yaml
> 🌱 Update GitHub actions for CAPV v1.15

- .github/workflows/pr-golangci-lint.yaml
- .golangci-kal.yml
- Makefile
- hack/tools/.custom-gcl.yaml
> ✨ Enable KAL in CI

- .golangci-kal.yml
> 🌱 Fix KAL config

- controllers/vspheremachine_controller.go
- controllers/vspheremachine_controller_test.go
> 🐛 Remove finalizer from VSphereMachine during deletion if ownerRef was never set

- test/e2e/data/autoscaler/autoscaler-to-management-workload.yaml
> ✨ Bump autoscaler to a9cb59fdd

- README.md
> 🌱 Update OVA list with K8s v1.34 images
